---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur l'interface de ligne de commandes SANtricity
    url: "/index.html"
  - title: Quoi de neuf
    url: "/whats-new.html"
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
