---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 'what"s new' 
summary: Cette rubrique répertorie les modifications apportées aux dernières versions de SANtricity System Manager de la commande CLI et des commandes script. 
---
= Quoi de neuf
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cette rubrique répertorie les modifications apportées aux dernières versions de SANtricity System Manager de la commande CLI et des commandes script.

[NOTE]
====
Lors de l'émission de commandes SMcli à l'invite de commande, vous devez entrer une barre oblique inverse supplémentaire (`\`) Caractère comme caractère d'échappement dans le chemin d'accès d'un fichier d'entrée ou de sortie lors de l'utilisation du système d'exploitation Windows. La barre oblique inverse supplémentaire (`\`) Doit être inclus lors de l'utilisation de SMcli en mode sécurisé https, en fournissant l'option -u pour spécifier un utilisateur de gestion d'accès basé sur des rôles. Exemple : `C:\\dir\\subdir\\filename`

====
[NOTE]
====
Si vous utilisez actuellement SANtricity 11.52 ou une version antérieure, vous ne pouvez pas effectuer la mise à niveau vers la dernière version d'SANtricity par le biais de l'interface de ligne de commande héritée. Les mises à niveau de SANtricity 11.52 vers des versions ultérieures peuvent uniquement être effectuées via SMcli.

====


== SANtricity 11.90

Le tableau suivant répertorie les modifications apportées aux commandes CLI et script pour la version 11.90.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html["Définir la limite de taille d'intervention AutoSupport"]
 a| 
Commande ajoutée



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html["Enregistrez le contrôleur arrayManagementCSR"]
 a| 
Paramètre ajouté `KeySize`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-email-smtp-delivery-method.html["Définissez la méthode de livraison de courrier électronique (SMTP)"]
 a| 
Paramètre ajouté `destinationAddress`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples["Afficher les paramètres AutoSupport"]
 a| 
Ajout de limites de taille d'intervention et d'adresses e-mail de destination à l'exemple de sortie pour la commande.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html["Téléchargez le certificat de gestion de clé de baie de stockage"]
 a| 
Paramètre ajouté `privateKeyFile`.

|===


== SANtricity 11.81

Le tableau suivant répertorie les modifications apportées aux commandes CLI et script pour la version 11.81.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices["Identifier les périphériques"]
 a| 
Ajouté `identifyDevices` paramètre.

|===


== SANtricity 11.80

Le tableau suivant répertorie les modifications apportées aux commandes CLI et script pour la version 11.80.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[Enregistrer les erreurs de parité de la tâche de vérification du volume]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/start-check-vol-parity-job.adoc[Lancer la tâche de vérification de la parité du volume]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[Afficher les tâches de vérification de parité de volume]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/show-check-vol-parity-job.adoc[Affiche la tâche de vérification de la parité du volume]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/stop-check-vol-parity-job.adoc[Arrêter la vérification de la parité du volume]
 a| 
Commande ajoutée



 a| 
xref:./get-started/command-line-parameters.adoc[Paramètres de ligne de commande existants]
 a| 
Ajouté `-useLegacyTransferPort` paramètre.



 a| 
xref:./commands-a-z/autoconfigure-storagearray.adoc[Configurer automatiquement la matrice de stockage]
 a| 
Ajouté `blockSize` paramètre.



 a| 
xref:./commands-a-z/check-volume-parity.adoc[Vérifier la parité du volume]
 a| 
Commande obsolète.

|===


== SANtricity 11.70.5

Il n'y a pas de modification de l'interface de ligne de commande et de la commande de script pour la version 11.70.5.



== SANtricity 11.70.4

Le tableau suivant répertorie les modifications apportées à la CLI et aux commandes de script pour la version 11.70.4.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./get-started/downloadable-smcli-parameters.adoc[Télécharger les paramètres de ligne de commande SMcli]
 a| 
Ajouté `-t` et `-T` description des paramètres des jetons d'accès pour l'authentification multifactorielle.

|===


== SANtricity 11.70.3

Le tableau suivant répertorie les modifications apportées à la CLI et aux commandes de script pour la version 11.70.3.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[Démarrer le provisionnement de ressources de pool de disques]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[Démarrer l'approvisionnement des ressources du groupe de volumes]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[Démarrage du provisionnement complet du pool de disques]
 a| 
Mise à jour `disableResourceProvisioning` description du paramètre.



 a| 
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[Démarrer le provisionnement complet du groupe de volumes]
 a| 
Mise à jour `disableResourceProvisioning` description du paramètre.



 a| 
xref:./commands-a-z/recreate-storagearray-securitykey.html[Recréez la clé de sécurité externe]
 a| 
Ajouté `deleteOldKey` paramètre.



 a| 
xref:./commands-a-z/create-diskpool.html[Création d'un pool de disques]
 a| 
Mise à jour `driveCount` description du paramètre.

|===


== SANtricity 11.70.2

Le tableau suivant répertorie les modifications apportées à la CLI et aux commandes de script pour la version 11.70.2.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./commands-a-z/create-snmpuser-username.adoc[Enregistrer l'utilisateur SNMPv3 USM]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/set-snmpuser-username.adoc[Mettre à jour l'utilisateur SNMPv3 USM]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/show-allsnmpusers.adoc[Afficher l'utilisateur SNMPv3 USM]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/delete-snmpuser-username.adoc[Annuler l'inscription de l'utilisateur SNMPv3 USM]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/create-snmptrapdestination.adoc[Enregistrer la destination d'interruption SNMP]
 a| 
Ajouté `userName` et `engineid` paramètres.



 a| 
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[Mettre à jour la destination du trap SNMP]
 a| 
Ajouté `userName` et `engineid` paramètres.



 a| 
xref:./commands-a-z/start-snmptrapdestination.adoc[Tester la destination de l'interruption SNMP]
 a| 
Ajouté `userName` et `engineid` paramètres.

|===


== SANtricity 11.70.1

Le tableau suivant répertorie les modifications apportées à la CLI et aux commandes de script pour la version 11.70.1.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./commands-a-z/start-drive-erase.adoc[Commencez à effacer le lecteur]
 a| 
Commande ajoutée



 a| 
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[Importer la clé de sécurité de la matrice de stockage]
 a| 
Ajouté `forceOverwrite` paramètre.



 a| 
xref:./commands-a-z/set-controller-hostport.adoc[Définissez les propriétés du port hôte du contrôleur]
 a| 
Ajouté `fecMode` paramètre.



 a| 
xref:./commands-a-z/show-syslog-summary.adoc[Affiche la configuration syslog]
 a| 
Ajouté `syslogFormat` paramètre.



 a| 
xref:./commands-a-z/set-syslog.adoc[Configurer les paramètres syslog]
 a| 
Ajouté `syslogFormat` paramètre.



 a| 
xref:./commands-a-z/set-emailalert.adoc[Configurez les paramètres d'alerte par e-mail]
 a| 
Ajouté `serverEncryption`, `serverPort`, `serverUsername`, et `serverPassword` paramètres.



 a| 
xref:./commands-a-z/show-emailalert-summary.adoc[Affiche la configuration des alertes par e-mail]
 a| 
Ajouté `SMTP` chiffrement, port et données des paramètres d'identification.



 a| 
xref:./commands-a-z/recover-volume.adoc[Récupérer un volume RAID]
 a| 
Ajouté `blockSize` paramètre.

|===


== SANtricity 11.70

Le tableau suivant répertorie les modifications apportées à la CLI et aux commandes de script pour la version 11.70.

[cols="2*"]
|===
| Commande | Description de la modification 


 a| 
xref:./commands-a-z/download-storagearray-firmware.adoc[Téléchargez le micrologiciel de la matrice de stockage/NVSRAM]
 a| 
Ajouté `healthCheckNeedsAttnOverride` paramètre.



 a| 
xref:./commands-a-z/create-volume-diskpool.adoc[Créez le volume dans le pool de disques]
 a| 
Ajouté `raidLevel` paramètre.



 a| 
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[Activez la gestion externe des clés de sécurité]
 a| 
Ajouté `saveFile` paramètre.



 a| 
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[Désactivez la gestion externe des clés de sécurité]
 a| 
Ajouté `saveFile` paramètre.



 a| 
xref:./commands-a-z/recover-volume.adoc[Récupérer un volume RAID]
 a| 
Ajouté `hostUnmapEnabled` paramètre.

|===