---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: La commande Activer la fonctionnalité storageArray active la fonction de mise en miroir asynchrone. 
---
= Activer la mise en miroir asynchrone - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `activate storageArray feature` Commande active la fonction de mise en miroir asynchrone.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, à condition que tous les packages SMcli soient installés.

[NOTE]
====
Cette commande s'applique uniquement à la mise en miroir asynchrone sur Fibre Channel.

====


[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de stockage.



[[context]]
== Contexte

Après avoir activé la fonction de mise en miroir asynchrone, vous devez configurer un groupe de miroirs asynchrone et une paire de miroirs asynchrones.



[[syntax]]
== Syntaxe

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
