---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: La commande Activer la fonctionnalité storageArray active la fonction de mise en miroir asynchrone. 
---
= Activer la mise en miroir asynchrone - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `activate storageArray feature` Commande active la fonction de mise en miroir asynchrone.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.

[NOTE]
====
Cette commande s'applique uniquement à la mise en miroir asynchrone sur Fibre Channel.

====


== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Après avoir activé la fonction de mise en miroir asynchrone, vous devez configurer un groupe de miroirs asynchrone et une paire de miroirs asynchrones.



== Syntaxe

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


== Paramètres

Aucune.



== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
