---
permalink: commands-a-z/add-drives-to-ssd-cache.html 
sidebar: sidebar 
keywords: add drives ssd cache, supported arrays, syntax, parameters, minimum firmware level 
summary: 'La commande set ssdcache augmente la capacité d"un cache SSD existant en ajoutant des disques SSD supplémentaires.' 
---
= Ajout de disques à SSD cache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set ssdCache` Cette commande augmente la capacité d'un cache SSD existant en ajoutant davantage de disques SSD.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.

[NOTE]
====
Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du support.

====


== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[set ssdCache [_ssdCacheName_]]
pass:quotes[addDrives=(_trayID1_,[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_,]pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`ssdCache`
 a| 
Nom du cache SSD auquel vous souhaitez ajouter des disques SSD. Placez le nom entre crochets ([ ]). Si le nom du cache SSD contient des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom entre guillemets (") dans les crochets.



 a| 
`addDrives`
 a| 
Les lecteurs que vous souhaitez ajouter à la mémoire cache SSD.pour les tiroirs disques haute capacité, spécifiez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID du logement pour le lecteur. Pour les tiroirs disques basse capacité, spécifiez la valeur d'ID du bac et la valeur d'ID du logement pour le lecteur. Les valeurs d'ID du bac sont `0` à `99`. Les valeurs d'ID de tiroir sont `1` à `5`.

La capacité maximale de tous les emplacements est de 24. Les valeurs d'ID de fente commencent à 0 ou 1, selon le modèle de bac. Les tiroirs disques compatibles avec les contrôleurs E2800 et E5700 ont des numéros d'ID de slot commençant à 0. Les tiroirs disques compatibles avec les contrôleurs E2700 et E5600 possèdent des numéros d'ID de slot commençant à 1.

Placez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID de logement entre crochets ([ ]).

|===


== Remarques

Le cache SSD peut contenir tout nombre de disques SSD. La taille maximale du cache d'un SSD est de 5 To, mais elle peut être inférieure selon la taille du cache principal du contrôleur.



== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
