---
permalink: commands-a-z/autoconfigure-storagearray-hotspares.html 
sidebar: sidebar 
keywords: autoconfigure, storage, array, hot spares, supported, roles, syntax, parameters, minimum firmware level 
summary: La commande autoConfigure storageArray hotSpares définit et configure automatiquement les disques de secours dans une matrice de stockage. Vous pouvez exécuter cette commande à tout moment. Cette commande offre la meilleure couverture de disque de secours pour une matrice de stockage. 
---
= Configuration automatique des disques de secours de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `autoConfigure storageArray hotSpares` commande définit et configure automatiquement les disques de secours dans une matrice de stockage. Vous pouvez exécuter cette commande à tout moment. Cette commande offre la meilleure couverture de disque de secours pour une matrice de stockage.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[syntax]]
== Syntaxe

[source, cli]
----
autoConfigure storageArray hotSpares
----


[[parameters]]
== Paramètres

Aucune.



[[notes]]
== Remarques

Lorsque vous exécutez le `autoconfigure storageArray hotSpares` commande, le firmware du contrôleur détermine le nombre de disques de rechange à créer en fonction du nombre et du type de disques de la baie de stockage. Pour les disques SAS, le micrologiciel du contrôleur crée un disque de secours pour la matrice de stockage et un disque de secours supplémentaire pour chaque 60 disques de la matrice de stockage.



[[minimum-firmware-level]]
== Niveau minimal de firmware

6.10
