---
permalink: commands-a-z/clear-storagearray-firmwarependingarea.html 
sidebar: sidebar 
keywords: clear, storage array, firmware, pending, area 
summary: La commande Effacer storageArray firmawarePendingArea supprime une image de micrologiciel ou des valeurs NVSRAM que vous avez préalablement téléchargées à partir du tampon de zone en attente. 
---
= Effacer la zone d'attente du micrologiciel de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `clear storageArray firmwarePendingArea` Commande supprime une image de micrologiciel ou des valeurs NVSRAM que vous avez déjà téléchargées depuis la mémoire tampon de la zone en attente.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
*Dommages possibles à la configuration de la matrice de stockage* -- dès que vous exécutez cette commande, le contenu de la zone en attente existante de la matrice de stockage est supprimé.

====


== Syntaxe

[source, cli]
----
clear storageArray firmwarePendingArea
----


== Paramètres

Aucune.
