---
permalink: commands-a-z/clear-storagearray-eventlog.html 
sidebar: sidebar 
keywords: clear, storage array, event log 
summary: 'La commande Effacer le journal d"événements du système de stockage efface le journal des événements de la matrice de stockage en supprimant les données dans la mémoire tampon du journal des événements.' 
---
= Effacer le journal des événements de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `clear storageArray eventLog` Cette commande efface le journal des événements de la matrice de stockage en supprimant les données de la mémoire tampon du journal des événements.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Contexte

[NOTE]
====
*Dommages possibles à la configuration de la matrice de stockage* -- dès que vous exécutez cette commande, le journal des événements existant dans la matrice de stockage est supprimé.

====


== Syntaxe

[source, cli]
----
clear storageArray eventLog
----


== Paramètres

Aucune.
