---
permalink: commands-a-z/create-raid-volume-manual-drive-select.html 
sidebar: sidebar 
keywords: create, raid, volume, manual, drive, select 
summary: La commande create volume crée un nouveau groupe de volumes et un nouveau volume, et vous permet de spécifier les lecteurs du volume. 
---
= Créer un volume RAID (sélection manuelle du lecteur)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `create volume` commande crée un nouveau groupe de volumes et un nouveau volume, et vous permet de spécifier les lecteurs du volume.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Syntaxe

[listing, subs="+macros"]
----
create volume drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeName"_]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
[blockSize=blockSizeValue]

----
[listing, subs="+macros"]
----
create volume drives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_)]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
raidLevel=(0 | 1 | 5 | 6)
userLabel=pass:quotes[_"volumeName"_]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`drives`
 a| 
Les lecteurs que vous souhaitez attribuer au volume que vous souhaitez créer. Pour les tiroirs disques haute capacité, spécifiez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID du logement pour le lecteur. Pour les tiroirs disques basse capacité, spécifiez la valeur d'ID du bac et la valeur d'ID du logement pour le lecteur. Les valeurs d'ID du bac sont `0` à `99`. Les valeurs d'ID de tiroir sont `1` à `5`.

La capacité maximale de tous les emplacements est de 24. Les valeurs d'ID de fente commencent à 0 ou 1, selon le modèle de bac. Les tiroirs disques compatibles avec les contrôleurs E2800 et E5700 ont des numéros d'ID de slot commençant à 0. Les tiroirs disques compatibles avec les contrôleurs E2700 et E5600 possèdent des numéros d'ID de slot commençant à 1.

Placez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID de logement entre crochets ([ ]).



 a| 
`volumeGroupUserLabel`
 a| 
Nom que vous souhaitez attribuer au nouveau groupe de volumes. Placez le nom du groupe de volumes entre guillemets (" ").

[NOTE]
====
Si vous ne spécifiez pas d'étiquette d'utilisateur pour le groupe de volumes, le micrologiciel du contrôleur lui attribue un numéro.

====


 a| 
`raidLevel`
 a| 
Niveau RAID du groupe de volumes qui contient le volume. Les valeurs valides sont `0`, `1`, `3`, `5`, ou `6`.



 a| 
`userLabel`
 a| 
Nom à attribuer au nouveau volume. Placez le nouveau nom du volume entre guillemets (" ").

[NOTE]
====
Ce paramètre est obligatoire.

====


 a| 
`capacity`
 a| 
Taille du volume que vous ajoutez à la matrice de stockage. La taille est définie en unités de `bytes`, `KB`, `MB`, `GB`, ou `TB`.



 a| 
`owner`
 a| 
Contrôleur qui détient le volume. Les identifiants de contrôleur valides sont `a` ou `b`, où `a` Est le contrôleur dans le slot A, et `b` Est le contrôleur associé au slot B. Si vous ne spécifiez pas de propriétaire, le micrologiciel du contrôleur détermine le propriétaire.



 a| 
`cacheReadPrefetch`
 a| 
Paramètre permettant d'activer ou de désactiver la lecture préalable du cache. Pour désactiver la lecture préalable du cache, définissez ce paramètre sur `FALSE`. Pour activer la lecture préalable du cache, définissez ce paramètre sur `TRUE`.



 a| 
`segmentSize`
 a| 
Quantité de données (en Ko) que le contrôleur écrit sur un seul disque du volume avant d'écrire les données sur le disque suivant. Les valeurs valides sont``4 (SSD only)``/, `16`, `32`, `64`, `128`, `256`, ou `512`.



 a| 
`usageHint`
 a| 
Les paramètres pour les deux `cacheReadPrefetch` paramètre et le `segmentSize` paramètre devant être des valeurs par défaut. Les valeurs par défaut sont basées sur le modèle d'utilisation d'E/S type de l'application qui utilise le volume. Les valeurs valides sont `fileSystem`, `dataBase`, ou `multiMedia`.



 a| 
`trayLossProtect`
 a| 
Paramètre permettant d'appliquer la protection contre les pertes de bac lorsque vous créez le référentiel. Pour appliquer la protection contre les pertes de bac, définissez ce paramètre sur `TRUE`. La valeur par défaut est `FALSE`.



 a| 
`drawerLossProtect`
 a| 
Paramètre permettant d'appliquer la protection contre les pertes de tiroirs lorsque vous créez le volume de référentiel en miroir. Pour appliquer la protection contre les pertes de tiroirs, définissez ce paramètre sur `TRUE`. La valeur par défaut est `FALSE`.



 a| 
`dssPreAllocate`
 a| 
Paramètre permettant de s'assurer que la capacité de réserve est allouée pour la taille de segment future augmente. Cette valeur par défaut est `TRUE`.



 a| 
`securityType`
 a| 
Paramètre permettant de spécifier le niveau de sécurité lors de la création des groupes de volumes et de tous les volumes associés. Ces paramètres sont valides :

* `none` -- le groupe de volumes et les volumes ne sont pas sécurisés.
* `capable` -- le groupe de volumes et les volumes sont capables d'avoir la sécurité définie, mais la sécurité n'a pas été activée.
* `enabled` -- la sécurité est activée pour le groupe de volumes et les volumes.




 a| 
`resourceProvisioningCapable`
 a| 
Paramètre permettant de spécifier si les capacités de provisionnement des ressources sont activées. Pour désactiver le provisionnement de ressources, définissez ce paramètre sur `FALSE`. La valeur par défaut est `TRUE`.



 a| 
`mapping`
 a| 
Ce paramètre vous permet de mapper le volume à un hôte. Si vous souhaitez mapper ultérieurement, définissez ce paramètre sur `none`. Si vous souhaitez mapper maintenant, définissez ce paramètre sur `default`. Le volume est mappé à tous les hôtes ayant accès au pool de stockage. La valeur par défaut est `none`.



 a| 
`blockSize`
 a| 
Ce paramètre définit la taille de bloc du volume en cours de création. La valeur 0 ou le paramètre non défini utilise la taille de bloc par défaut.

|===


== Remarques

Le `drives` paramètre prend en charge à la fois les tiroirs disques haute capacité et les tiroirs disques basse capacité. Un tiroir de disque haute capacité est doté de tiroirs qui maintiennent les disques. Les tiroirs coulissent hors du tiroir du lecteur pour permettre l'accès aux lecteurs. Un tiroir de lecteur de faible capacité n'est pas doté de tiroirs. Pour un plateau de lecteur haute capacité, vous devez spécifier l'identifiant (ID) du plateau de lecteur, l'ID du tiroir et l'ID du logement dans lequel se trouve un lecteur. Dans le cas d'un plateau de lecteur de faible capacité, vous devez uniquement spécifier l'ID du plateau de lecteur et l'ID de l'emplacement dans lequel se trouve un lecteur. Pour un plateau de lecteur de faible capacité, une autre méthode d'identification d'un emplacement est de spécifier l'ID du plateau de lecteur, définissez l'ID du tiroir sur `0`, Et indiquez l'ID de l'emplacement dans lequel réside un lecteur.

Si vous définissez le `raidLevel` Paramètre au niveau RAID 1 :

* Il y a un nombre pair de disques dans le groupe, par définition RAID 1
* La première moitié du groupe, dans l'ordre indiqué (et dans l'ordre des bandes), sont des disques principaux
* La seconde moitié du groupe, dans l'ordre indiqué (et dans l'ordre des bandes), correspond aux entraînements de rétroviseur correspondants


Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.

Le `owner` le paramètre définit quel contrôleur détient le volume. La propriété de contrôleur préférée d'un volume est le contrôleur qui est actuellement propriétaire du groupe de volumes.

Si vous ne spécifiez pas de capacité à l'aide de l' `capacity` paramètre, toute la capacité du lecteur disponible dans le groupe de volumes est utilisée. Si vous ne spécifiez pas d'unités de capacité, `bytes` est utilisé comme valeur par défaut.



== Protection contre les pertes de bac et protection contre les pertes de tiroir

Pour que la protection contre les pertes de bac fonctionne, votre configuration doit respecter les directives suivantes :

|===
| Niveau | Critères pour la protection contre les pertes du plateau | Nombre minimum de bacs requis 


 a| 
`Disk Pool`
 a| 
Le pool de disques ne contient pas plus de deux lecteurs dans un bac unique
 a| 
6



 a| 
`RAID 6`
 a| 
Le groupe de volumes ne contient pas plus de deux lecteurs dans un bac unique
 a| 
3



 a| 
`RAID 3` ou `RAID 5`
 a| 
Chaque lecteur du groupe de volumes se trouve dans un bac distinct
 a| 
3



 a| 
`RAID 1`
 a| 
Chaque lecteur d'une paire RAID 1 doit se trouver dans un bac distinct
 a| 
2



 a| 
`RAID 0`
 a| 
Impossible d'obtenir la protection contre les pertes du bac.
 a| 
Sans objet

|===
Pour que la protection contre les pertes de tiroirs fonctionne (dans les environnements de boîtiers haute densité), votre configuration doit respecter les directives suivantes :

|===
| Niveau | Critères pour la protection contre les pertes de tiroirs | Nombre minimum de tiroirs requis 


 a| 
`Disk Pool`
 a| 
Le pool comprend des disques des cinq tiroirs et il y a un nombre égal de disques dans chaque tiroir. Un plateau de 60 lecteurs peut atteindre la protection contre les pertes de tiroirs lorsque le pool de disques contient 15, 20, 25, 30, 35, 40, 45, 50, 55 ou 60 disques.
 a| 
5



 a| 
`RAID 6`
 a| 
Le groupe de volumes ne contient pas plus de deux disques dans un tiroir unique.
 a| 
3



 a| 
`RAID 3` ou `RAID 5`
 a| 
Chaque lecteur du groupe de volumes se trouve dans un tiroir distinct.
 a| 
3



 a| 
`RAID 1`
 a| 
Chaque lecteur d'une paire symétrique doit être placé dans un tiroir séparé.
 a| 
2



 a| 
`RAID 0`
 a| 
Impossible d'obtenir la protection contre la perte de tiroir.
 a| 
Sans objet

|===


== Taille du segment

La taille d'un segment détermine le nombre de blocs de données que le contrôleur écrit sur un seul disque du volume avant d'écrire des données sur le disque suivant. Chaque bloc de données stocke 512 octets de données. Le bloc de données est la plus petite unité de stockage. La taille d'un segment détermine le nombre de blocs de données qu'il contient. Par exemple, un segment de 8 Ko contient 16 blocs de données. Un segment de 64 Ko contient 128 blocs de données.

Lorsque vous entrez une valeur pour la taille du segment, la valeur est vérifiée par rapport aux valeurs prises en charge fournies par le contrôleur au moment de l'exécution. Si la valeur saisie n'est pas valide, le contrôleur renvoie une liste de valeurs valides. L'utilisation d'un lecteur unique pour une seule demande laisse les autres lecteurs disponibles pour traiter simultanément d'autres demandes. Si le volume se trouve dans un environnement où un utilisateur unique transfère de grandes unités de données (comme le multimédia), les performances sont optimisées lorsqu'une seule demande de transfert de données est traitée avec une seule bande de données. (Une bande de données est la taille du segment multipliée par le nombre de disques du groupe de volumes utilisés pour le transfert de données.) Dans ce cas, plusieurs disques sont utilisés pour la même demande, mais chaque disque n'est accessible qu'une seule fois.

Pour des performances optimales dans une base de données multi-utilisateurs ou un environnement de stockage de système de fichiers, définissez la taille de votre segment afin de minimiser le nombre de lecteurs requis pour répondre à une demande de transfert de données.



== Conseils d'utilisation

[NOTE]
====
Il n'est pas nécessaire de saisir une valeur pour le `cacheReadPrefetch` ou le `segmentSize` paramètre. Si vous ne saisissez aucune valeur, le micrologiciel du contrôleur utilise le `usageHint` paramètre avec `fileSystem` comme valeur par défaut. Saisie d'une valeur pour le `usageHint` et une valeur pour le `cacheReadPrefetch` ou une valeur pour le `segmentSize` le paramètre n'entraîne pas d'erreur. La valeur que vous saisissez pour le `cacheReadPrefetch` ou le `segmentSize` le paramètre prend priorité sur la valeur de `usageHint` paramètre. La taille du segment et les paramètres de lecture préalable en cache pour différents conseils d'utilisation sont indiqués dans le tableau suivant :

====
|===
| Indice d'utilisation | Réglage de la taille du segment | Paramètre de préextraction de lecture dynamique du cache 


 a| 
Système de fichiers
 a| 
128 KO
 a| 
Activé



 a| 
Base de données
 a| 
128 KO
 a| 
Activé



 a| 
Multimédia
 a| 
256 KO
 a| 
Activé

|===


== Préextraction de lecture du cache

La lecture préalable en cache permet au contrôleur de copier des blocs de données supplémentaires dans le cache pendant que le contrôleur lit et copie les blocs de données requis par l'hôte depuis le disque vers le cache. Cette action augmente le risque d'une future demande de données à partir du cache. Le préchargement de lecture du cache est important pour les applications multimédia qui utilisent des transferts de données séquentiels. Valeurs valides pour le `cacheReadPrefetch` les paramètres sont `TRUE` ou `FALSE`. La valeur par défaut est `TRUE`.

Il n'est pas nécessaire de saisir une valeur pour le `cacheReadPrefetch` ou le `segmentSize` paramètre. Si vous ne saisissez aucune valeur, le micrologiciel du contrôleur utilise le `usageHint` paramètre avec `fileSystem` comme valeur par défaut. Saisie d'une valeur pour le `usageHint` et une valeur pour le `cacheReadPrefetch` ou une valeur pour le `segmentSize` le paramètre n'entraîne pas d'erreur. La valeur que vous saisissez pour le `cacheReadPrefetch` ou le `segmentSize` le paramètre prend priorité sur la valeur de `usageHint` paramètre.



== Type de sécurité

Utilisez le `securityType` paramètre pour spécifier les paramètres de sécurité de la matrice de stockage.

Avant de pouvoir régler le `securityType` paramètre à `enabled`, vous devez créer une clé de sécurité de la matrice de stockage. Utilisez le `create storageArray securityKey` commande permettant de créer une clé de sécurité de la matrice de stockage. Ces commandes sont liées à la clé de sécurité :

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Niveau minimal de firmware

7.10 ajoute la fonctionnalité RAID de niveau 6 et `dssPreAllocate` paramètre.

7.50 ajoute le `securityType` paramètre.

7.60 ajoute l'entrée utilisateur _drawerID_ et le `drawerLossProtect` paramètre.

7.75 ajoute le `dataAssurance` paramètre.

8.63 ajoute le `resourceProvisioningCapable` paramètre.

11.70 ajoute le `blockSize` paramètre.
