---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: La commande create Volume Group crée un groupe de volumes à capacité libre ou un groupe de volumes avec un volume lorsque vous entrez un ensemble de disques non assignés. 
---
= Créer un groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `create volumeGroup` lorsque vous entrez un ensemble de disques non assignés, une commande crée un groupe de volumes libre ou un groupe de volumes sur un volume.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Syntaxe

[listing, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`drives`
 a| 
Les lecteurs que vous souhaitez attribuer au groupe de volumes que vous souhaitez créer. Pour les tiroirs disques haute capacité, spécifiez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID du logement pour le lecteur. Pour les tiroirs disques basse capacité, spécifiez la valeur d'ID du bac et la valeur d'ID du logement pour le lecteur. Les valeurs d'ID du bac sont `0` à `99`. Les valeurs d'ID de tiroir sont `1` à `5`.

La capacité maximale de tous les emplacements est de 24. Les valeurs d'ID de fente commencent à 0 ou 1, selon le modèle de bac. Les tiroirs disques compatibles avec les contrôleurs E2800 et E5700 ont des numéros d'ID de slot commençant à 0. Les tiroirs disques compatibles avec les contrôleurs E2700 et E5600 possèdent des numéros d'ID de slot commençant à 1.

Placez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID de logement entre crochets ([ ]).



 a| 
`raidLevel`
 a| 
Niveau RAID du groupe de volumes qui contient le volume. Les valeurs valides sont `0`, `1`, `3`, `5`, ou `6`.



 a| 
`userLabel`
 a| 
Nom que vous souhaitez attribuer au nouveau groupe de volumes. Placez le nom du groupe de volumes entre guillemets (" ").



 a| 
`driveMediaType`
 a| 
Type de support de lecteur que vous souhaitez utiliser pour le groupe de volumes

Vous devez utiliser ce paramètre lorsque vous disposez de plusieurs types de support de lecteur dans votre matrice de stockage.

Ces supports de lecteur sont valides :

* `HDD` -- utilisez cette option lorsque vous avez des disques durs dans le plateau du lecteur
* `SSD` -- utilisez cette option lorsque vous disposez de disques SSD dans le plateau
* `unknown` -- utilisez cette option si vous ne savez pas quels types de support se trouvent dans le bac d'alimentation
* `allMedia` -- utilisez cette option lorsque vous souhaitez utiliser tous les types de support de lecteur qui se trouvent dans le bac de lecteur




 a| 
`driveType`
 a| 
Le type de lecteur que vous souhaitez utiliser dans le groupe de volumes. Vous ne pouvez pas combiner plusieurs types de disques.

Vous devez utiliser ce paramètre lorsque vous avez plusieurs types de lecteur dans votre matrice de stockage.

Ces types de disques sont valides :

* `SAS`
* `NVMe4K`


Si vous ne spécifiez pas de type de lecteur, le code ne vérifie pas que les lecteurs spécifiés sont de ce type de lecteur.



 a| 
`trayLossProtect`
 a| 
Paramètre pour appliquer la protection contre les pertes de bac lorsque vous créez le groupe de volumes. Pour appliquer la protection contre les pertes de bac, définissez ce paramètre sur `TRUE`. La valeur par défaut est `FALSE`.



 a| 
`drawerLossProtect`
 a| 
Paramètre permettant d'appliquer la protection contre la perte de tiroir lorsque vous créez le groupe de volumes. Pour appliquer la protection contre les pertes de tiroir, définissez ce paramètre sur `TRUE`. La valeur par défaut est `FALSE`.



 a| 
`securityType`
 a| 
Paramètre permettant de spécifier le niveau de sécurité lors de la création des groupes de volumes et de tous les volumes associés. Ces paramètres sont valides :

* `none` -- le groupe de volumes et les volumes ne sont pas sécurisés.
* `capable` -- le groupe de volumes et les volumes sont capables d'avoir la sécurité définie, mais la sécurité n'a pas été activée.
* `enabled` -- la sécurité est activée pour le groupe de volumes et les volumes.




 a| 
`resourceProvisioningCapable`
 a| 
Paramètre permettant de spécifier si les capacités de provisionnement des ressources sont activées. Pour désactiver le provisionnement de ressources, définissez ce paramètre sur `FALSE`. La valeur par défaut est `TRUE`.

|===


== Disques et groupes de volumes

Un groupe de volumes est un ensemble de disques regroupés de manière logique par les contrôleurs de la baie de stockage. Le nombre de disques d'un groupe de volumes est une limitation du niveau RAID et du micrologiciel du contrôleur. Lorsque vous créez un groupe de volumes, suivez les consignes suivantes :

* À partir de la version 7.10 du micrologiciel, vous pouvez créer un groupe de volumes vide afin de pouvoir réserver la capacité pour une utilisation ultérieure.
* Vous ne pouvez pas mélanger les types de disques au sein d'un même groupe de volumes.
* Vous ne pouvez pas combiner des disques HDD et SSD dans un même groupe de volumes.
* Le nombre maximum de disques dans un groupe de volumes dépend des conditions suivantes :
+
** Le type de contrôleur
** Niveau RAID


* Les niveaux RAID sont 0, 1, 3, 5 et 6 .
+
** Un groupe de volumes de niveau RAID 3, RAID de niveau 5 ou RAID de niveau 6 ne peut pas avoir plus de 30 disques.
** Un groupe de volumes RAID de niveau 6 doit comporter au moins cinq disques.
** Si un groupe de volumes RAID de niveau 1 comporte quatre disques ou plus, le logiciel de gestion du stockage convertit automatiquement le groupe de volumes en RAID de niveau 10, c'est-à-dire de niveau 1 + RAID de niveau 0.


* Pour activer la protection contre les pertes des tiroirs/bacs, reportez-vous aux tableaux suivants pour obtenir des critères supplémentaires :


|===
| Niveau | Critères pour la protection contre les pertes du plateau | Nombre minimum de bacs requis 


 a| 
`Disk Pool`
 a| 
Le pool de disques ne contient pas plus de deux lecteurs dans un bac unique
 a| 
6



 a| 
`RAID 6`
 a| 
Le groupe de volumes ne contient pas plus de deux lecteurs dans un bac unique
 a| 
3



 a| 
`RAID 3` ou `RAID 5`
 a| 
Chaque lecteur du groupe de volumes se trouve dans un bac distinct
 a| 
3



 a| 
`RAID 1`
 a| 
Chaque lecteur d'une paire RAID 1 doit se trouver dans un bac distinct
 a| 
2



 a| 
`RAID 0`
 a| 
Impossible d'obtenir la protection contre les pertes du bac.
 a| 
Sans objet

|===
|===
| Niveau | Critères pour la protection contre les pertes de tiroirs | Nombre minimum de tiroirs requis 


 a| 
`Disk Pool`
 a| 
Le pool comprend des disques des cinq tiroirs et il y a un nombre égal de disques dans chaque tiroir. Un plateau de 60 lecteurs peut atteindre la protection contre les pertes de tiroirs lorsque le pool de disques contient 15, 20, 25, 30, 35, 40, 45, 50, 55 ou 60 disques.
 a| 
5



 a| 
`RAID 6`
 a| 
Le groupe de volumes ne contient pas plus de deux disques dans un tiroir unique.
 a| 
3



 a| 
`RAID 3` ou `RAID 5`
 a| 
Chaque lecteur du groupe de volumes se trouve dans un tiroir distinct.
 a| 
3



 a| 
`RAID 1`
 a| 
Chaque lecteur d'une paire symétrique doit être placé dans un tiroir séparé.
 a| 
2



 a| 
`RAID 0`
 a| 
Impossible d'obtenir la protection contre la perte de tiroir.
 a| 
Sans objet

|===


== Disques de secours

Avec les groupes de volumes, une stratégie de protection des données intéressante consiste à attribuer les disques disponibles de la baie de stockage en tant que disques de secours. Un disque de secours est un disque, qui ne contient aucune donnée, qui agit comme un disque de secours dans la matrice de stockage en cas de panne d'un disque dans un groupe de volumes RAID 1, RAID 3, RAID 5 ou RAID 6. Le disque de secours ajoute un niveau supplémentaire de redondance à la matrice de stockage.

Généralement, les disques de secours doivent avoir des capacités égales ou supérieures à la capacité utilisée sur les disques qu'ils protègent. Les disques de secours doivent être du même type de support, du même type d'interface et de la même capacité que les lecteurs qu'ils protègent.

Si un disque tombe en panne dans la matrice de stockage, le disque de secours est normalement remplacé automatiquement par le disque défectueux sans intervention de votre part. Si un disque de secours est disponible en cas de panne, le contrôleur reconstruit les données sur le disque de secours à l'aide d'une parité de redondance. La prise en charge de l'évacuation des données permet également de copier les données sur un disque de secours avant que le logiciel ne marque l'échec du disque.

Une fois le disque défectueux remplacé physiquement, vous pouvez utiliser l'une des options suivantes pour restaurer les données :

Lorsque vous avez remplacé le disque défectueux, les données du disque de secours sont recopiées sur le disque de remplacement. Cette action est appelée recopie.

Si vous désignez le disque de secours comme membre permanent d'un groupe de volumes, l'opération de recopie n'est pas nécessaire.

La disponibilité de la protection contre les pertes de tiroirs et la protection contre les pertes de tiroirs pour un groupe de volumes dépend de l'emplacement des lecteurs qui constituent le groupe de volumes. La protection contre les pertes de tiroir et la protection contre les pertes de tiroir peuvent être perdues en raison d'un disque défectueux et de l'emplacement du disque de secours. Pour vous assurer que la protection contre les pertes de bac et la protection contre les pertes de tiroir ne sont pas affectées, vous devez remplacer un disque défectueux pour lancer le processus de copie.

La baie de stockage sélectionne automatiquement les disques compatibles Data assurance (DA) pour la couverture à chaud des volumes compatibles DA.

Assurez-vous que la matrice de stockage comporte des disques compatibles DA pour la couverture de remplacement à chaud des volumes compatibles DA. Pour plus d'informations sur les disques compatibles DA, consultez la fonction Data assurance.

Vous pouvez utiliser des disques de capacité sécurisée (FIPS et FDE) comme unité de rechange à chaud pour les disques compatibles et non sécurisés. Les disques non sécurisés peuvent couvrir d'autres disques non sécurisés et les disques sécurisés si la sécurité n'est pas activée dans le groupe de volumes. Un groupe de volumes FIPS ne peut utiliser qu'un disque FIPS comme unité de rechange à chaud. Cependant, vous pouvez utiliser un disque de rechange FIPS pour des groupes de volumes non sécurisés, sécurisés et sécurisés.

Si vous ne disposez pas d'un disque de secours, vous pouvez toujours remplacer un disque défectueux pendant que la matrice de stockage fonctionne. Si le disque fait partie d'un groupe de volumes RAID 1, RAID 3, RAID 5 ou RAID 6, le contrôleur utilise la parité des données de redondance pour reconstruire automatiquement les données sur le disque de remplacement. Cette action est appelée reconstruction.



== Taille du segment

La taille d'un segment détermine le nombre de blocs de données que le contrôleur écrit sur un seul disque du volume avant d'écrire des données sur le disque suivant. Chaque bloc de données stocke 512 octets de données. Le bloc de données est la plus petite unité de stockage. La taille d'un segment détermine le nombre de blocs de données qu'il contient. Par exemple, un segment de 8 Ko contient 16 blocs de données. Un segment de 64 Ko contient 128 blocs de données.

Lorsque vous entrez une valeur pour la taille du segment, la valeur est vérifiée par rapport aux valeurs prises en charge fournies par le contrôleur au moment de l'exécution. Si la valeur saisie n'est pas valide, le contrôleur renvoie une liste de valeurs valides. L'utilisation d'un lecteur unique pour une seule demande laisse les autres lecteurs disponibles pour traiter simultanément d'autres demandes. Si le volume se trouve dans un environnement où un utilisateur unique transfère de grandes unités de données (comme le multimédia), les performances sont optimisées lorsqu'une seule demande de transfert de données est traitée avec une seule bande de données. (Une bande de données est la taille du segment multipliée par le nombre de disques du groupe de volumes utilisés pour le transfert de données.) Dans ce cas, plusieurs disques sont utilisés pour la même demande, mais chaque disque n'est accessible qu'une seule fois.

Pour des performances optimales dans une base de données multi-utilisateurs ou un environnement de stockage de système de fichiers, définissez la taille de votre segment afin de minimiser le nombre de lecteurs requis pour répondre à une demande de transfert de données.



== Conseils d'utilisation

[NOTE]
====
Il n'est pas nécessaire de saisir une valeur pour le `cacheReadPrefetch` ou le `segmentSize` paramètre. Si vous ne saisissez aucune valeur, le micrologiciel du contrôleur utilise le `usageHint` paramètre avec `fileSystem` comme valeur par défaut. Saisie d'une valeur pour le `usageHint` et une valeur pour le `cacheReadPrefetch` ou une valeur pour le `segmentSize` le paramètre n'entraîne pas d'erreur. La valeur que vous saisissez pour le `cacheReadPrefetch` ou le `segmentSize` le paramètre prend priorité sur la valeur de `usageHint` paramètre. La taille du segment et les paramètres de lecture préalable en cache pour différents conseils d'utilisation sont indiqués dans le tableau suivant :

====
|===
| Indice d'utilisation | Réglage de la taille du segment | Paramètre de préextraction de lecture dynamique du cache 


 a| 
Système de fichiers
 a| 
128 KO
 a| 
Activé



 a| 
Base de données
 a| 
128 KO
 a| 
Activé



 a| 
Multimédia
 a| 
256 KO
 a| 
Activé

|===


== Préextraction de lecture du cache

La lecture préalable en cache permet au contrôleur de copier des blocs de données supplémentaires dans le cache pendant que le contrôleur lit et copie les blocs de données requis par l'hôte depuis le disque vers le cache. Cette action augmente le risque d'une future demande de données à partir du cache. Le préchargement de lecture du cache est important pour les applications multimédia qui utilisent des transferts de données séquentiels. Valeurs valides pour le `cacheReadPrefetch` les paramètres sont `TRUE` ou `FALSE`. La valeur par défaut est `TRUE`.



== Type de sécurité

Utilisez le `securityType` paramètre pour spécifier les paramètres de sécurité de la matrice de stockage.

Avant de pouvoir régler le `securityType` paramètre à `enabled`, vous devez créer une clé de sécurité de la matrice de stockage. Utilisez le `create storageArray securityKey` commande permettant de créer une clé de sécurité de la matrice de stockage. Ces commandes sont liées à la clé de sécurité :

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Sécuriser les disques

Les disques sécurisés peuvent être des disques FDE (Full Disk Encryption) ou FIPS (Federal information Processing Standard). Utilisez le `secureDrives` paramètre pour spécifier le type de disques sécurisés à utiliser. Les valeurs que vous pouvez utiliser sont les suivantes `fips` et `fde`.



== La gestion de la Data assurance

La fonctionnalité Data assurance (DA) renforce l'intégrité des données sur l'ensemble du système de stockage. DA permet à la matrice de stockage de vérifier si des erreurs peuvent se produire lorsque des données sont déplacées entre les hôtes et les lecteurs. Lorsque cette fonctionnalité est activée, la matrice de stockage ajoute des codes de vérification des erreurs (également appelés vérifications cycliques de redondance ou CRCS) à chaque bloc de données du volume. Après le déplacement d'un bloc de données, la matrice de stockage utilise ces codes CRC pour déterminer si des erreurs se sont produites au cours de la transmission. Les données potentiellement corrompues ne sont ni écrites sur le disque ni renvoyées à l'hôte.

Si vous souhaitez utiliser la fonction DA, commencez par un pool ou un groupe de volumes qui inclut uniquement les lecteurs qui prennent en charge DA. Ensuite, créez des volumes compatibles DA. Enfin, mappez ces volumes compatibles DA à l'hôte à l'aide d'une interface d'E/S capable de gérer DA. Les interfaces d'E/S qui peuvent être DA incluent Fibre Channel, SAS et iser over InfiniBand (iSCSI Extensions for RDMA/IB). DA n'est pas pris en charge par iSCSI over Ethernet ou par le SRP sur InfiniBand.

[NOTE]
====
Lorsque tous les lecteurs sont compatibles DA, vous pouvez définir le `dataAssurance` paramètre à `enabled` Puis utiliser DA avec certaines opérations. Par exemple, vous pouvez créer un groupe de volumes comprenant des disques compatibles DA, puis créer un volume au sein de ce groupe de volumes qui est activé par DA. Les autres opérations qui utilisent un volume activé par DA peuvent prendre en charge la fonction DA.

====
Si le `dataAssurance` le paramètre est défini sur `enabled`seuls les disques compatibles avec data assurance seront pris en compte pour les candidats aux volumes. sinon, ils seront pris en compte les disques avec data assurance et non data assurance. Si seuls les disques Data assurance sont disponibles, le nouveau groupe de volumes sera créé à l'aide des disques Data assurance activés.



== Niveau minimal de firmware

7.10

7.50 ajoute le `securityType` paramètre.

7.60 ajoute le `drawerID` entrée utilisateur, le `driveMediaType` paramètre, et le `drawerLossProtect` paramètre.

7.75 ajoute le `dataAssurance` paramètre.

8.63 ajoute le `resourceProvisioningCapable` paramètre.
