---
permalink: commands-a-z/create-storagearray-syslog.html 
sidebar: sidebar 
keywords: create, storage, array, syslog, configuration 
summary: 'La commande create storageArray syslog permet d’archiver les journaux d’audit sur un serveur syslog externe. Une fois la connexion établie entre la matrice de stockage et le serveur syslog, les journaux d"audit sont automatiquement enregistrés sur le serveur syslog.' 
---
= Créer une configuration syslog de matrice de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `create storageArray syslog` la commande vous permet d'archiver les journaux d'audit sur un serveur syslog externe. Une fois la connexion établie entre la matrice de stockage et le serveur syslog, les journaux d'audit sont automatiquement enregistrés sur le serveur syslog.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
create storageArray syslog serverAddress="<address>" port=<port> protocol=("udp" | "tcp" | "tls") components=(componentName=("auditLog") ...)
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`serverAddress`
 a| 
Nom d'hôte ou adresse IP du récepteur syslog.



 a| 
`port`
 a| 
Numéro de port du récepteur syslog.



 a| 
`protocol`
 a| 
Protocole de transmission Syslog Les valeurs acceptables incluent udp, tcp ou tls.



 a| 
`components`
 a| 
Liste des entrées de composant qui seront consignées sur le serveur syslog. Actuellement, seuls les journaux d'audit sont pris en charge.



 a| 
`componentName`
 a| 
Nom du composant ; actuellement, seul « auditlog » est pris en charge.

|===


=== Exemple

[listing]
----
SMcli -n Array1 -c "create storageArray syslog
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e
Server Address: 192.168.2.1.com
Port: 514
Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Niveau minimal de firmware

8.42
