---
permalink: commands-a-z/create-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency, group 
summary: 'La commande create conceGroup crée un groupe de cohérence vide, qui peut contenir des groupes de snapshots. Vous devez ajouter les groupes de snapshots à l"aide de la commande set ConsistenceGroup addCGMember.' 
---
= Créer un groupe de cohérence - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `create consistencyGroup` la commande crée un nouveau groupe de cohérence vide qui peut contenir des groupes de snapshots. Vous devez ajouter les groupes de snapshots à l'aide de `set consistencyGroup addCGMember` commande.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
create consistencyGroup userLabel=pass:quotes[_"consistencyGroupName"_]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapSchedule_])]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`userLabel`
 a| 
Nom du groupe de cohérence à créer. Placez le nouveau nom de groupe de cohérence entre guillemets ("").



 a| 
`repositoryFullPolicy`
 a| 
Comment souhaitez-vous que le traitement des instantanés se poursuive si les volumes du référentiel de snapshots sont pleins. Vous pouvez choisir de faire échouer les écritures dans le volume de base (`failBaseWrites`) ou supprimez (purgez) les images de snapshot  `purgeSnapImages`). L'action par défaut est `purgeSnapImages`.



 a| 
`repositoryFullLimit`
 a| 
Pourcentage de capacité du référentiel sur lequel vous recevez un avertissement indiquant que le volume du référentiel snapshot approche de son plein. Utiliser des valeurs entières. Par exemple, une valeur de 70 signifie 70 %. La valeur par défaut est 75.



 a| 
`autoDeleteLimit`
 a| 
Chaque groupe de snapshots peut être configuré de manière à effectuer une suppression automatique de ses images de snapshot afin de conserver le nombre total d'images de snapshot dans le groupe de snapshots au niveau ou en dessous d'un niveau désigné. Lorsque cette option est activée, chaque fois qu'une nouvelle image instantanée est créée dans le groupe de snapshots, le système supprime automatiquement l'image snapshot la plus ancienne du groupe pour qu'elle soit conforme à la valeur limite. Cette action libère de la capacité de l'espace de stockage afin de satisfaire les exigences de copie en écriture pour les images de snapshot restantes.



 a| 
`enableSchedule`
 a| 
La possibilité de planifier une opération d'instantané est activée ou désactivée. Pour activer la planification des snapshots, définissez ce paramètre sur `TRUE`. Pour désactiver la planification des snapshots, définissez ce paramètre sur `FALSE`.



 a| 
`rollBackPriority`
 a| 
Détermine si les ressources système doivent être allouées à l'opération de restauration, aux dépens des performances du système. Valeur de `high` Indique que l'opération de restauration est prioritaire sur toutes les autres E/S hôtes Valeur de `low` Indique que l'opération de restauration doit être effectuée avec un impact minimal sur les E/S de l'hôte

|===


== Remarques

Un groupe de cohérence est une entité logique qui vous permet de gérer toutes les images de snapshot que vous ajoutez à la collection sous forme de lots. Ce groupe de cohérence est un ensemble de groupes Snapshot ayant des exigences de cohérence mutuelle ou des dépendances pour leurs images Snapshot. Toutes les images de snapshot que vous créez et utilisez pour cette collection doivent être gérées conformément aux dépendances de cohérence.

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.

Les images de snapshot d'un groupe de cohérence peuvent être déduites en fonction de l'existence d'une image Snapshot au sein d'un groupe de cohérence. Toutes les images de snapshot résidant au sein d'un groupe de cohérence partagent un horodatage et un numéro de séquence communs.

Une opération située sur un groupe de cohérence d'image de snapshot est traitée comme une seule requête, et toutes les opérations d'E/S en attente doivent être supprimées et suspendues au volume de base associé de chaque membre avant de créer les images de snapshot. Si la création des images de snapshot ne peut pas être effectuée avec succès pour tous les membres du groupe de cohérence, l'opération échoue et n'a aucun effet (c'est-à-dire que les nouvelles images de snapshot ne sont pas créées).

En fonction de ce comportement, tous les membres d'un groupe de cohérence ont généralement le même nombre d'images de snapshot. Cependant, lorsqu'un nouveau membre est ajouté à un groupe de cohérence, ce nouveau membre ne dispose pas des images de snapshot précédemment créées sur les membres établis du groupe de cohérence. Le manque d'images snapshot n'est pas considéré comme une condition d'erreur. Les demandes de suppression ou de retour arrière d'images de snapshot qui n'existent que sur un sous-ensemble des membres du groupe de cohérence n'affectent que les membres pour lesquels les images de snapshot spécifiées existent réellement.



== Suppression automatique

Vous pouvez configurer chaque groupe de snapshots de manière à supprimer automatiquement ses images de snapshot afin de conserver le nombre total d'images de snapshot dans le groupe de snapshots à un nombre maximum d'images ou en dessous. Lorsque le nombre d'images de snapshot dans le groupe de snapshots est au maximum, le `autoDeleteLimit` le paramètre supprime automatiquement les images instantanées chaque fois qu'une nouvelle image instantanée est créée dans le groupe d'instantanés. Le `autoDeleteLimit` le paramètre supprime les images snapshot les plus anciennes du groupe d'instantanés jusqu'à ce que le nombre maximal d'images défini avec le paramètre soit atteint. Cette opération a pour effet de libérer de la capacité du référentiel, de sorte qu'elle puisse être utilisée pour satisfaire les exigences de copie en écriture pour les images snapshots restantes.



== Planification d'images de snapshot dans un groupe de cohérence

Le `enableSchedule` paramètre et le `schedule` paramètre vous permet de planifier les snapshots. Ces paramètres vous permettent de programmer des instantanés tous les jours, toutes les semaines ou tous les mois (par jour ou par date). Le `enableSchedule` paramètre active ou désactive la possibilité de planifier des snapshots. Lorsque vous activez la planification, vous utilisez le `schedule` paramètre pour définir l'heure à laquelle les snapshots doivent être effectués.

Ce tableau explique comment utiliser les options de l' `schedule` paramètre :

|===
| Paramètre | Description 


 a| 
`schedule`
 a| 
Requis pour spécifier les paramètres de planification.



 a| 
`immediate`
 a| 
Démarrer immédiatement l'opération. Cet élément s'excluent mutuellement avec tous les autres paramètres de planification.



 a| 
`enableSchedule`
 a| 
Lorsqu'il est réglé sur `true`, la programmation est activée. Lorsqu'il est réglé sur `false`, la programmation est désactivée.

[NOTE]
====
La valeur par défaut est `false`.

====


 a| 
`startDate`
 a| 
Date précise de démarrage de l'opération. Le format de saisie de la date est MM:JJ:AA. La valeur par défaut est la date actuelle. Voici un exemple de cette option `startDate=06:27:11`.



 a| 
`scheduleDay`
 a| 
Un jour de la semaine où commencer l'opération. Peut être une ou plusieurs des valeurs suivantes :

* `monday`
* `tuesday`
* `wednesday`
* `thursday`
* `friday`
* `saturday`
* `sunday`


[NOTE]
====
Placez la valeur entre parenthèses. Par exemple : `scheduleDay=(wednesday)`.

====
Plus d'un jour peut être spécifié en enfermant les jours dans un ensemble unique de parenthèses et en séparant chaque jour avec un espace. Par exemple : `scheduleDay=(monday wednesday friday)`.

[NOTE]
====
Ce paramètre n'est pas compatible avec un planning mensuel.

====


 a| 
`startTime`
 a| 
L'heure du jour de démarrage de l'opération. Le format de saisie de l'heure est HH:MM, où HH est l'heure et MM est la minute au-delà de l'heure. Utilise une horloge de 24 heures. Par exemple, 2:00 dans l'après-midi est 14:00. Voici un exemple de cette option `startTime=14:27`.



 a| 
`scheduleInterval`
 a| 
Durée, en minutes, d'au moins entre les opérations.l'intervalle de planification ne doit pas être supérieur à 1440 (24 heures) et doit être un multiple de 30.

Voici un exemple de cette option``scheduleInterval=180``.



 a| 
`endDate`
 a| 
Une date précise pour arrêter l'opération. Le format de saisie de la date est MM:JJ:AA. Si aucune date de fin n'est souhaitée, vous pouvez spécifier `noEndDate`. Voici un exemple de cette option `endDate=11:26:11`.



 a| 
`timesPerDay`
 a| 
Nombre de fois où effectuer l'opération dans un jour. Voici un exemple de cette option `timesPerDay=4`.



 a| 
`timezone`
 a| 
Spécifie le fuseau horaire à utiliser pour la planification. Peut être spécifié de deux manières :

* *GMT±HH:MM*
+
Décalage du fuseau horaire par rapport au GMT. Exemple : `timezone=GMT-06:00`.

* *Chaîne de texte*
+
Chaîne de texte de fuseau horaire standard, doit être entre guillemets. Exemple :``timezone="America/Chicago"``





 a| 
`scheduleDate`
 a| 
Un jour du mois où effectuer l'opération. Les valeurs des jours sont numériques et comprises dans la plage 1-31.

[NOTE]
====
Ce paramètre n'est pas compatible avec un planning hebdomadaire.

====
Un exemple du `scheduleDate` l'option est `scheduleDate=("15")`.



 a| 
`month`
 a| 
Mois précis pour effectuer l'opération. Les valeurs pour les mois sont les suivantes :

* `jan` - Janvier
* `feb` - Février
* `mar` - Mars
* `apr` - Avril
* `may` - Mai
* `jun` - Juin
* `jul` - Juillet
* `aug` - Août
* `sep` - Septembre
* `oct` - Octobre
* `nov` - Novembre
* `dec` - Décembre


[NOTE]
====
Placez la valeur entre parenthèses. Par exemple : `month=(jan)`.

====
Plus d'un mois peut être spécifié en enfermant les mois dans un ensemble unique de parenthèses et en séparant chaque mois par un espace. Par exemple : `month=(jan jul dec)`.

Utilisez ce paramètre avec le `scheduleDate` paramètre pour effectuer l'opération sur un jour spécifique du mois.

[NOTE]
====
Ce paramètre n'est pas compatible avec un planning hebdomadaire.

====
|===
Ce tableau explique comment utiliser le `timeZone` paramètre :

|===
| Nom du fuseau horaire | Décalage GMT 


 a| 
`Etc/GMT+12`
 a| 
`GMT-12:00`



 a| 
`Etc/GMT+11`
 a| 
`GMT-11:00`



 a| 
`Pacific/Honolulu`
 a| 
`GMT-10:00`



 a| 
`America/Anchorage`
 a| 
`GMT-09:00`



 a| 
`America/Santa_Isabel`
 a| 
`GMT-08:00`



 a| 
`America/Los_Angeles`
 a| 
`GMT-08:00`



 a| 
`America/Phoenix`
 a| 
`GMT-07:00`



 a| 
`America/Chihuahua`
 a| 
`GMT-07:00`



 a| 
`America/Denver`
 a| 
`GMT-07:00`



 a| 
`America/Guatemala`
 a| 
`GMT-06:00`



 a| 
`America/Chicago`
 a| 
`GMT-06:00`



 a| 
`America/Mexico_City`
 a| 
`GMT-06:00`



 a| 
`America/Regina`
 a| 
`GMT-06:00`



 a| 
`America/Bogota`
 a| 
`GMT-05:00`



 a| 
`America/New_York`
 a| 
`GMT-05:00`



 a| 
`Etc/GMT+5`
 a| 
`GMT-05:00`



 a| 
`America/Caracas`
 a| 
`GMT-04:30`



 a| 
`America/Asuncion`
 a| 
`GMT-04:00`



 a| 
`America/Halifax`
 a| 
`GMT-04:00`



 a| 
`America/Cuiaba`
 a| 
`GMT-04:00`



 a| 
`America/La_Paz`
 a| 
`GMT-04:00`



 a| 
`America/Santiago`
 a| 
`GMT-04:00`



 a| 
`America/St_Johns`
 a| 
`GMT-03:30`



 a| 
`America/Sao_Paulo`
 a| 
`GMT-03:00`



 a| 
`America/Buenos_Aires`
 a| 
`GMT-03:00`



 a| 
`America/Cayenne`
 a| 
`GMT-03:00`



 a| 
`America/Godthab`
 a| 
`GMT-03:00`



 a| 
`America/Montevideo`
 a| 
`GMT-03:00`



 a| 
`Etc/GMT+2`
 a| 
`GMT-02:00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01:00`



 a| 
`Atlantic/Cape_Verde`
 a| 
`GMT-01:00`



 a| 
`Africa/Casablanca`
 a| 
`GMT`



 a| 
`Etc/GMT`
 a| 
`GMT`



 a| 
`Europe/London`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`Europe/Berlin`
 a| 
`GMT+01:00`



 a| 
`Europe/Budapest`
 a| 
`GMT+01:00`



 a| 
`Europe/Paris`
 a| 
`GMT+01:00`



 a| 
`Europe/Warsaw`
 a| 
`GMT+01:00`



 a| 
`Africa/Lagos`
 a| 
`GMT+01:00`



 a| 
`Africa/Windhoek`
 a| 
`GMT+01:00`



 a| 
`Asia/Anman`
 a| 
`GMT+02:00`



 a| 
`Asia/Beirut`
 a| 
`GMT+02:00`



 a| 
`Africa/Cairo`
 a| 
`GMT+02:00`



 a| 
`Asia/Damascus`
 a| 
`GMT+02:00`



 a| 
`Africa/Johannesburg`
 a| 
`GMT+02:00`



 a| 
`Europe/Kiev`
 a| 
`GMT+02:00`



 a| 
`Asia/Jerusalem`
 a| 
`GMT+02:00`



 a| 
`Europe/Istanbul`
 a| 
`GMT+03:00`



 a| 
`Europe/Minsk`
 a| 
`GMT+02:00`



 a| 
`Asia/Baghdad`
 a| 
`GMT+03:00`



 a| 
`Asia/Riyadh`
 a| 
`GMT+03:00`



 a| 
`Africa/Nairobi`
 a| 
`GMT+03:00`



 a| 
`Asia/Tehran`
 a| 
`GMT+03:30`



 a| 
`Europe/Moscow`
 a| 
`GMT+04:00`



 a| 
`Asia/Dubai`
 a| 
`GMT+04:00`



 a| 
`Asia/Baku`
 a| 
`GMT+04:00`



 a| 
`Indian/Mauritius`
 a| 
`GMT+04:00`



 a| 
`Asia/Tbilisi`
 a| 
`GMT+04:00`



 a| 
`Asia/Yerevan`
 a| 
`GMT+04:00`



 a| 
`Asia/Kabul`
 a| 
`GMT+04:30`



 a| 
`Asia/Karachi`
 a| 
`GMT+05:00`



 a| 
`Asia//Tashkent`
 a| 
`GMT+05:00`



 a| 
`Asia/Calcutta`
 a| 
`GMT+05:30`



 a| 
`Asia/Colombo`
 a| 
`GMT+05:30`



 a| 
`Asia/Katmandu`
 a| 
`GMT+05:45`



 a| 
`Asia/Yekaterinburg`
 a| 
`GMT+06:00`



 a| 
`Asia/Almaty`
 a| 
`GMT+06:00`



 a| 
`Asia/Dhaka`
 a| 
`GMT+06:00`



 a| 
`Asia/Rangoon`
 a| 
`GMT+06:30`



 a| 
`Asia/Novosibirsk`
 a| 
`GMT+07:00`



 a| 
`Asia/Bangkok`
 a| 
`GMT+07:00`



 a| 
`Asia/Krasnoyarsk`
 a| 
`GMT+08:00`



 a| 
`Asia/Shanghai`
 a| 
`GMT+08:00`



 a| 
`Asia/Singapore`
 a| 
`GMT+08:00`



 a| 
`Australia/Perth`
 a| 
`GMT+08:00`



 a| 
`Asia/Taipei`
 a| 
`GMT+08:00`



 a| 
`Asia/Ulaanbaatar`
 a| 
`GMT+08:00`



 a| 
`Asia/Irkutsk`
 a| 
`GMT+09:00`



 a| 
`Asia/Tokyo`
 a| 
`GMT+09:00`



 a| 
`Asia/Seoul`
 a| 
`GMT+09:00`



 a| 
`Australia/Adelaide`
 a| 
`GMT+09:30`



 a| 
`Australia/Darwin`
 a| 
`GMT+09:30`



 a| 
`Asia/Yakutsk`
 a| 
`GMT+10:00`



 a| 
`Australia/Brisbane`
 a| 
`GMT+10:00`



 a| 
`Australia/Sydney`
 a| 
`GMT+10:00`



 a| 
`Pacific/Port Moresby`
 a| 
`GMT+10:00`



 a| 
`Australia/Hobart`
 a| 
`GMT+10:00`



 a| 
`Asia/Vladivostok`
 a| 
`GMT+11:00`



 a| 
`Pacific/Guadalcanal`
 a| 
`GMT+11:00`



 a| 
`Pacific/Auckland`
 a| 
`GMT+12:00`



 a| 
`Etc/GMT-12`
 a| 
`GMT+12:00`



 a| 
`Pacific/Fiji`
 a| 
`GMT+12:00`



 a| 
`Asia/Kamchatka`
 a| 
`GMT+12:00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13:00`

|===
La chaîne de code pour la définition d'un planning est similaire aux exemples suivants :

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
Si vous utilisez également le `scheduleInterval` le micrologiciel sélectionne l'option `timesPerDay` et le `scheduleInterval` en sélectionnant la valeur la plus basse des deux options. Le micrologiciel calcule une valeur entière pour l' `scheduleInterval` option en divisant 1440 par un `scheduleInterval` valeur d'option que vous définissez. Par exemple, 1440/180 = 8. Le micrologiciel compare ensuite le `timesPerDay` valeur entière calculée `scheduleInterval` valeur entière et utilise la valeur la plus petite.

Pour supprimer une planification, utilisez le `delete volume` commande avec `schedule` paramètre. Le `delete volume` commande avec `schedule` le paramètre supprime uniquement la planification, pas le volume snapshot.

Lors de l'exécution d'une restauration dans un groupe de cohérence, l'opération par défaut consiste à annuler la restauration de tous les membres du groupe de cohérence. Si une restauration ne peut pas être démarrée avec succès pour tous les membres du groupe de cohérence, la restauration échoue et n'a aucun effet. L'image d'instantané n'est pas annulée.



== Niveau minimal de firmware

7.83

7.86 ajoute le `scheduleDate` et le `month` option.
