---
permalink: commands-a-z/create-hostgroup.html 
sidebar: sidebar 
keywords: create, host group 
summary: 'La commande create hostGroup crée un nouveau groupe d"hôtes.' 
---
= Créer un groupe d'hôtes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `create hostGroup` commande crée un nouveau groupe d'hôtes.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
create hostGroup userLabel=pass:quotes[_"hostGroupName"_]
----


== Paramètre

|===
| Paramètre | Description 


 a| 
`userLabel`
 a| 
Nom que vous souhaitez attribuer au groupe d'hôtes que vous créez. Placez le nom du groupe d'hôtes entre guillemets (" ").

|===


== Remarques

Un groupe d'hôtes est un élément topologique facultatif que vous pouvez définir si vous souhaitez désigner une collection d'hôtes partageant l'accès aux mêmes volumes. Le groupe d'hôtes est une entité logique. Définissez un groupe d'hôtes uniquement si vous avez au moins deux hôtes qui peuvent partager l'accès aux mêmes volumes.

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits d'Union et de traits de soulignement pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



== Niveau minimal de firmware

5.20
