---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: La fonction Désactiver le réseau de stockage désactive la fonction de mise en miroir asynchrone. 
---
= Désactiver la mise en miroir asynchrone – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `deactivate storageArray feature` Désactive la fonction de mise en miroir asynchrone.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Tous les groupes de miroirs asynchrones ou paires de miroirs asynchrones existants doivent être supprimés de la baie de stockage locale et de la baie de stockage distante avant de pouvoir désactiver la fonction de mise en miroir asynchrone.



== Syntaxe

[source, cli]
----
deactivate storageArray feature=asyncRemoteMirror
----


== Paramètres

Aucune.



== Niveau minimal de firmware

7.84
