---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: La fonction Désactiver le réseau de stockage désactive la fonction de mise en miroir asynchrone. 
---
= Désactiver la mise en miroir asynchrone – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `deactivate storageArray feature` Désactive la fonction de mise en miroir asynchrone.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Tous les groupes de miroirs asynchrones ou paires de miroirs asynchrones existants doivent être supprimés de la baie de stockage locale et de la baie de stockage distante avant de pouvoir désactiver la fonction de mise en miroir asynchrone.



[[syntax]]
== Syntaxe

[source, cli]
----
deactivate storageArray feature=asyncRemoteMirror
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.84
