---
permalink: commands-a-z/delete-volume.html 
sidebar: sidebar 
keywords: delete, volume, command, one, standard, volume, supported, array, role 
summary: La commande delete volume supprime un ou plusieurs volumes standard. 
---
= Supprimer le volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `delete volume` commande supprime un ou plusieurs volumes standard.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
*Dommages possibles à la configuration de la matrice de stockage* -- toutes les données du volume sont perdues dès que vous exécutez cette commande.

====
[NOTE]
====
Lorsqu'un volume dépasse une taille donnée (actuellement 128 To), la suppression est effectuée en arrière-plan et l'espace libéré n'est peut-être pas disponible immédiatement.

====


== Syntaxe

[listing]
----
delete (allVolumes) |
volume [volumeName] |
volumes [volumeName1 ... volumeNameN]
[removeVolumeGroup=(TRUE | FALSE)]
[force=(TRUE | FALSE)]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allVolumes`
 a| 
Ce paramètre supprime tous les volumes d'une matrice de stockage.



 a| 
`volume`
 a| 
Nom du volume que vous souhaitez supprimer. Placez le nom du volume entre crochets ([ ]). Si le nom du volume comporte des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du volume entre guillemets (" ") à l'intérieur de crochets.



 a| 
`volumes`
 a| 
Les noms de plusieurs volumes que vous souhaitez supprimer. Entrez les noms des volumes à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Séparez chacun des noms par un espace.


Si les noms de volumes comportent des caractères spéciaux ou ne sont composés que de chiffres, entrez les noms à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.




 a| 
`removeVolumeGroup`
 a| 
La suppression du dernier volume d'un groupe de volumes ne supprime pas le groupe de volumes. Vous pouvez disposer d'un groupe de volumes autonome (moins tous les volumes). Pour supprimer le groupe de volumes autonome, définissez ce paramètre sur `TRUE`. Pour préserver l'intégrité des groupes de volumes autonomes, définissez ce paramètre sur `FALSE`.



 a| 
`force`
 a| 
Utilisez ce paramètre pour forcer la suppression immédiate d'un volume, même si les contrôleurs effectuent d'autres opérations. Pour forcer immédiatement la suppression d'un volume, définissez ce paramètre sur `TRUE`. Pour attendre que les contrôleurs aient terminé d'effectuer d'autres opérations, n'utilisez pas ce paramètre ou définissez ce paramètre sur `FALSE`.

|===


== Remarques

Lorsque vous utilisez le `allVolumes` paramètre, cette commande supprime les volumes jusqu'à ce que tous les volumes soient supprimés ou jusqu'à ce qu'une erreur s'affiche. En cas d'erreur, cette commande ne tente pas de supprimer les volumes restants. La suppression de volumes de différents groupes de volumes est possible. Tous les groupes de volumes qui deviennent vides sont supprimés si vous définissez le `removeVolumeGroup` paramètre à `TRUE`.

Si vous souhaitez supprimer un groupe de volumes entier, vous pouvez également utiliser le `delete volumeGroup` commande.



== Niveau minimal de firmware

6.10

7.10 ajoute le `removeVolumeGroup` paramètre.
