---
permalink: commands-a-z/delete-snmpcommunity.html 
sidebar: sidebar 
keywords: delete, snmpcommunity, command, existing, simple, network, management, protocol, community, previously, create, effective, unregister, trap, destination, associate, remove 
summary: 'La commande delete snmpCommunity supprime une communauté SNMP (simple Network Management Protocol) existante que vous avez précédemment créée et enregistrée à l"aide de la commande create snmpCommunity. La suppression d"une communauté SNMP annule efficacement l"enregistrement de la communauté. Toutes les destinations d"interruption associées à cette communauté sont également supprimées.' 
---
= Annuler l'enregistrement de la communauté SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `delete snmpCommunity` Commande supprime une communauté SNMP (simple Network Management Protocol) existante que vous avez précédemment créée et enregistrée à l'aide de `create snmpCommunity` commande. La suppression d'une communauté SNMP annule efficacement l'enregistrement de la communauté. Toutes les destinations d'interruption associées à cette communauté sont également supprimées.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[delete snmpCommunity communityName="_snmpCommunityName_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`communityName`
 a| 
Nom de la communauté SNMP que vous souhaitez supprimer. Placez le nom de la communauté SNMP entre guillemets (" ").

|===


== Niveau minimal de firmware

8.30
