---
permalink: commands-a-z/delete-snapvolume.html 
sidebar: sidebar 
keywords: delete, snapvolume, command, snapshot, volume, optionally, associate, repository, members 
summary: 'La commande delete snapVolume supprime un volume d"instantanés et éventuellement les membres associés au référentiel d"instantanés.' 
---
= Supprimer le volume d'instantané - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `delete snapVolume` la commande supprime un volume de snapshot et, le cas échéant, les membres de référentiel de snapshot associés.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
Vous ne pouvez pas utiliser cette commande pour les images Snapshot impliquées dans la copie de volume en ligne.

====


== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[delete snapVolume ["_snapVolumeName_"]]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume du snapshot que vous souhaitez supprimer. Placez le nom du volume de snapshot entre guillemets (" ") entre crochets ([ ]).



 a| 
`deleteRepositoryMembers`
 a| 
Paramètre pour enregistrer ou supprimer les membres du référentiel. Pour enregistrer les membres du référentiel, définissez ce paramètre sur `FALSE`. Pour supprimer les membres du référentiel, définissez ce paramètre sur `TRUE`. La valeur par défaut est `TRUE`. Si vous n'utilisez pas ce paramètre, les membres du référentiel sont automatiquement supprimés.

|===


== Niveau minimal de firmware

7.83
