---
permalink: commands-a-z/delete-hostport.html 
sidebar: sidebar 
keywords: delete, hostport, command, host, port, identification 
summary: La commande delete hostPort supprime une identification de port hôte. 
---
= Supprimer le port hôte
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `delete hostPort` commande supprime une identification de port hôte.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

L'identification est une valeur logicielle qui représente le port hôte physique vers le contrôleur. En supprimant l'identification, le contrôleur ne reconnaît plus les instructions et données du port hôte.

[IMPORTANT]
====
Cette commande ne fonctionne pas dans un environnement iSCSI où les ports hôtes sont considérés comme des initiateurs. Utilisez plutôt le `delete iscsiInitiator` commande. Voir xref:delete-iscsiinitiator.adoc[Supprimer l'initiateur iSCSI].

====


== Syntaxe

[listing]
----
delete hostPort [hostPortName]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`hostPort`
 a| 
Nom du port hôte que vous souhaitez supprimer. Placez le nom du port hôte entre crochets ([ ]). Si le nom du port hôte contient des caractères spéciaux ou se compose uniquement de nombres, vous devez également inclure le nom entre guillemets (" ") à l'intérieur des crochets.

|===


== Remarques

Un port hôte est une connexion physique sur une carte hôte qui réside dans un ordinateur hôte. Un port hôte fournit un accès hôte aux volumes d'une matrice de stockage.



== Niveau minimal de firmware

5.20
