---
permalink: commands-a-z/delete-volumegroup.html 
sidebar: sidebar 
keywords: delete, volume, group, command, entire, associated, support, role 
summary: La commande delete Volume Group supprime un groupe de volumes entier et ses volumes associés. 
---
= Supprimer le groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `delete volumeGroup` la commande supprime un groupe de volumes entier et ses volumes associés.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

[IMPORTANT]
====
*Dommages possibles à la configuration de la matrice de stockage* -- toutes les données du groupe de volumes sont perdues dès que vous exécutez cette commande.

====


== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[delete volumeGroup [_volumeGroupName_]]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes à supprimer. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


== Niveau minimal de firmware

6.10
