---
permalink: commands-a-z/delete-controller-cacertificate.html 
sidebar: sidebar 
keywords: remove, install, root, intermediate, ca, certificates 
summary: La commande delete Controller caCertificate supprime le certificat CA racine ou intermédiaire installé du contrôleur spécifié. 
---
= Supprimer les certificats d'autorité de certification racine/intermédiaire installés - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `delete controller caCertificate` Commande supprime le certificat d'autorité de certification racine/intermédiaire installé du contrôleur spécifié.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Security Admin.



[[syntax]]
== Syntaxe

[source, cli]
----
delete controller [(a|b)] caCertificate aliases=("alias1" ... "aliasN")
----


[[parameters]]
== Paramètres

|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur dont vous souhaitez supprimer le certificat signé. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`aliases`
 a| 
Permet de spécifier un ou plusieurs certificats CA à supprimer à l'aide des noms d'alias ou de spécifier tout. Les alias doivent être du contrôleur pour lequel le certificat est supprimé. Placez tous les alias entre parenthèses. Si vous saisissez plusieurs alias, séparez-les par un espace.

|===


[[examples]]
== Exemples

[listing]
----

SMcli -n Array1 -c "delete controller[a] caCertificate aliases=("myAlias" "anotherAlias");"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.40
