---
permalink: commands-a-z/delete-controller-cacertificate.html 
sidebar: sidebar 
keywords: remove, install, root, intermediate, ca, certificates 
summary: La commande delete Controller caCertificate supprime le certificat CA racine ou intermédiaire installé du contrôleur spécifié. 
---
= Supprimer les certificats CA racine/intermédiaire installés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `delete controller caCertificate` Commande supprime le certificat d'autorité de certification racine/intermédiaire installé du contrôleur spécifié.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
delete controller [(a|b)] caCertificate aliases=("alias1" ... "aliasN")
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur dont vous souhaitez supprimer le certificat signé. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`aliases`
 a| 
Permet de spécifier un ou plusieurs certificats CA à supprimer à l'aide des noms d'alias ou de spécifier tout. Les alias doivent être du contrôleur pour lequel le certificat est supprimé. Placez tous les alias entre parenthèses. Si vous saisissez plusieurs alias, séparez-les par un espace.

|===


== Exemples

[listing]
----

SMcli -n Array1 -c "delete controller[a] caCertificate aliases=("myAlias" "anotherAlias");"

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
