---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: La commande delete ssdcache supprime le cache SSD. Toutes les données du cache SSD sont supprimées. 
---
= Supprimer le cache SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `delete ssdCache` La commande supprime le cache SSD. Toutes les données du cache SSD sont supprimées.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez disposer du rôle Support Admin.



== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`ssdCache`
 a| 
Nom du cache SSD que vous souhaitez supprimer. Placez le nom du cache SSD entre crochets ([ ]). Si le nom du cache SSD contient des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du cache SSD entre guillemets (") dans les crochets.

|===


== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
