---
permalink: commands-a-z/download-controller-arraymanagementservercertificate.html 
sidebar: sidebar 
keywords: download, controller, array, management, server, certificate, command, install 
summary: La commande download Controller arrayManagementServerCertificate installe le certificat du serveur sur le contrôleur. 
---
= Installer un certificat signé par le serveur - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `download controller arrayManagementServerCertificate` commande installe le certificat du serveur sur le contrôleur.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Security Admin.



[[context]]
== Contexte

Effectuez cette action pour chaque contrôleur à l'aide du certificat signé applicable au contrôleur. Le certificat signé doit inclure les adresses IP/noms DNS du contrôleur.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
download controller [(a|b)] pass:quotes[arrayManagementServerCertificate file="_filename_"]
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet à l'utilisateur de spécifier le contrôleur pour lequel vous souhaitez installer le certificat signé par le serveur. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`file`
 a| 
Permet à l'utilisateur de spécifier le chemin d'accès au fichier et le nom du fichier contenant le certificat signé. Les extensions acceptables sont .cer, .crt, .der.

|===


[[examples]]
== Exemples

[listing]
----

SMcli -n Array1 -c "download controller [a] arrayManagementServerCertificate
   file="C:\serverSignedCertificateA.cer";"

SMcli -n Array1 -c "download controller [b] arrayManagementServerCertificate
   file="C:\serverSignedCertificateB.cer";"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.40
