---
permalink: commands-a-z/download-storagearray-drivefirmware-file.html 
sidebar: sidebar 
keywords: download, storage, array, drive, firmware, command, images, roles, supported 
summary: La commande download storageArray driveFirmware file télécharge les images du micrologiciel sur tous les lecteurs de la matrice de stockage. 
---
= Télécharger le micrologiciel du lecteur de baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `download storageArray driveFirmware file` commande télécharge les images du micrologiciel sur tous les lecteurs de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage ou d'administrateur du support.



== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[download storageArray driveFirmware file="_filename_"]
pass:quotes[[file="_filename2_"... file="_filenameN_"]]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier contenant l'image du micrologiciel. Placez le chemin du fichier et le nom du fichier de l'image du micrologiciel entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\dnld\sadrvfrm.dlp"`

Les noms de fichiers valides ont un `.dlp` extension.

|===


== Remarques

Lorsque vous exécutez cette commande, vous pouvez télécharger plusieurs fichiers image du micrologiciel vers les lecteurs d'une matrice de stockage. Le nombre de fichiers d'image de micrologiciel que vous pouvez télécharger dépend de la matrice de stockage. Le logiciel de gestion du stockage renvoie une erreur si vous essayez de télécharger plus de fichiers d'image de micrologiciel que la matrice de stockage ne peut accepter.

Vous pouvez planifier des téléchargements pour plusieurs disques simultanément, y compris plusieurs disques dans un groupe de volumes redondants. Chaque fichier image du micrologiciel contient des informations sur les types de lecteurs sur lesquels s'exécute l'image du micrologiciel. Les images du micrologiciel spécifiées peuvent être téléchargées uniquement sur un lecteur compatible. Utilisez le `download drive firmware` commande pour télécharger une image de firmware sur un disque spécifique.

Le `download storageArray driveFirmware` La commande bloque toutes les activités d'E/S jusqu'à ce que l'essai de téléchargement ait été effectué pour chaque lecteur candidat ou que vous exécutez le `stop storageArray downloadDriveFirmware` commande. Lorsque le `download storageArray driveFirmware` la commande termine le téléchargement de l'image du micrologiciel, chaque lecteur candidat affiche l'état du téléchargement de chaque lecteur. L'un de ces États est renvoyé :

* Réussi
* Échec avec raison
* Ne jamais tenter de raison




== Niveau minimal de firmware

5.20
