---
permalink: commands-a-z/download-tray-firmware-file.html 
sidebar: sidebar 
keywords: download, tray, firmware, file, command, environmental, service, module, array, role, context 
summary: 'La commande de téléchargement du fichier du micrologiciel du plateau de téléchargement télécharge le micrologiciel du module de services environnementaux (ESM).' 
---
= Téléchargez le micrologiciel de la carte environnementale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `download tray firmware file` Le firmware du module de services environnementaux (ESM) est téléchargé par commande.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage ou d'administrateur du support.



== Contexte

[IMPORTANT]
====
Sur les systèmes duplex gérés par System Manager (par exemple, E2800), un service de synchronisation automatique du module d'E/S s'exécute sur les contrôleurs. Il synchronise automatiquement le firmware du module avec la version contenue dans le bundle SANtricity OS chargée sur les contrôleurs. Si vous ne souhaitez pas que le firmware du module soit rétabli pour correspondre à la version chargée sur les contrôleurs, vous devez désactiver ce service. Le service de synchronisation automatique du module d'E/S peut être suspendu à l'aide de System Manager ou de l'API REST. Lors de la suspension de ce service, n'oubliez pas que le fait de laisser la synchronisation automatique activée garantit la mise à jour du firmware du module d'E/S.

====


== Syntaxe

[source, cli, subs="+macros"]
----
download (allTrays | tray [trayID])
pass:quotes[firmware file="_filename_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allTrays`
 a| 
Ce paramètre télécharge le nouveau micrologiciel sur tous les bacs compatibles de la matrice de stockage. Le progiciel que vous sélectionnez détermine les bacs compatibles. Les bacs incompatibles sont ignorés. Aucun message d'erreur ne s'affiche concernant les bacs incompatibles.



 a| 
`tray`
 a| 
Le plateau de lecteur qui contient la carte ESM vers laquelle vous souhaitez charger le nouveau micrologiciel. Les valeurs d'ID du bac sont `0` à `99`. Placez la valeur d'ID du bac entre crochets ([ ]).

[NOTE]
====
Il ne peut y avoir aucun zéro de tête dans l'ID du bac. Par exemple, si l'ID de bac affiché est « 02 », cette commande l'exige comme [2], et non [02].

====


 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier contenant l'image du micrologiciel. Placez le chemin du fichier et le nom du fichier de l'image du micrologiciel entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\dnld\esmfrm.esm"`

Les noms de fichiers valides ont un `.esm` extension.

|===


== Remarques

Le `tray` le paramètre télécharge le nouveau micrologiciel vers un plateau de lecteur spécifique Si vous devez télécharger le nouveau micrologiciel dans plusieurs tiroirs disques, mais pas tous les tiroirs, vous devez entrer cette commande pour chaque tiroir disque



== Niveau minimal de firmware

5.20
