---
permalink: commands-a-z/enable-controller-datatransfer.html 
sidebar: sidebar 
keywords: enable, controller, datatransfer, command, revive, quiesced, running, diagnostics, role, syntax, parameter, firmware level 
summary: 'La commande enable Controller DataTransfer fait revivre un contrôleur qui est mis au repos lors de l"exécution des diagnostics.' 
---
= Activer le transfert de données du contrôleur – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `enable controller dataTransfer` la commande réexécute un contrôleur qui est mis au repos lors de l'exécution des diagnostics.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Syntaxe

[source, cli]
----
enable controller [(a|b)] dataTransfer
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Le contrôleur que vous voulez relancer. Les identifiants de contrôleur valides sont `a` ou `b`, où `a` Est le contrôleur dans le slot A, et `b` Est le contrôleur associé au slot B. Placez l'identificateur du contrôleur entre crochets ([ ]). Si vous ne spécifiez pas de contrôleur, le logiciel de gestion du stockage renvoie une erreur de syntaxe.

|===


== Niveau minimal de firmware

6.10
