---
permalink: commands-a-z/enable-or-disable-autosupport-individual-arrays.html 
sidebar: sidebar 
keywords: command, enable, disable, autosupport, feature, storage, array, possible, transit, messages, technical, support, site, capable, automatically, prepare, collect, data, remote, troubleshooting, problem, analysis 
summary: 'Cette commande active ou désactive la fonction AutoSupport (ASUP) pour la baie de stockage et permet de transmettre des messages au site du support technique. Une fois la fonctionnalité ASUP activé, la baie de stockage ASUP est automatiquement prête à collecter et à envoyer des données relatives au support au support technique. Les données peuvent ensuite être utilisées pour le dépannage à distance et l"analyse des problèmes.' 
---
= Activer ou désactiver AutoSupport (toutes les baies individuelles) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande active ou désactive la fonction AutoSupport (ASUP) pour la baie de stockage et permet de transmettre des messages au site du support technique. Une fois la fonctionnalité ASUP activé, la baie de stockage ASUP est automatiquement prête à collecter et à envoyer des données relatives au support au support technique. Les données peuvent ensuite être utilisées pour le dépannage à distance et l'analyse des problèmes.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Après avoir activé cette fonction, vous pouvez ensuite activer la fonction AutoSupport OnDemand (si vous le souhaitez), puis activer la fonction AutoSupport Remote Diagnostics (diagnostic à distance) (si vous le souhaitez).

Vous devez activer les trois fonctions dans cet ordre :

. *Activer AutoSupport*
. *Activer AutoSupport OnDemand*
. *Activer les diagnostics à distance AutoSupport*




[[syntax]]
== Syntaxe

[source, cli]
----
set storageArray autoSupport (enable | disable)
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`enable | disable`
 a| 
Permet d'activer ou de désactiver AutoSupport. Si les fonctions OnDemand et Diagnostics à distance sont activées, l'action de désactivation désactive également les fonctions OnDemand et Diagnostics à distance.

|===


[[examples]]
=== Exemples

[listing]
----

   SMcli -n Array1 -c "set storageArray autoSupport enable;"

   SMcli completed successfully.
----


[[verification]]
== Vérification

Utilisez le `show storageArray autoSupport` commande pour voir si vous avez activé la fonction. La ligne initiale de la sortie affichée indique l'état d'activation :

[listing]
----
The AutoSupport feature is enabled on this storage array.
----


[[minimum-firmware-level]]
== Niveau minimal de micrologiciel

7.86 - Ajout d'une commande pour toutes les baies de stockage jusqu'au modèle E2700 et E5600

8.40 - prise en charge ajoutée des systèmes E2800 et E5700
