---
permalink: commands-a-z/establish-asyncmirror-volume.html 
sidebar: sidebar 
keywords: establish, asynmirror, volume, asynchronous, mirrored, remote, storage, array, secondary, existing 
summary: La commande fixer un volume asynchrone asynchrone au volume met fin à une paire asynchrone en miroir sur la matrice de stockage distante en ajoutant un volume secondaire à un groupe de miroirs asynchrone existant. 
---
= Établir une paire en miroir asynchrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `establish asyncMirror volume` la commande complète une paire asynchrone en miroir sur la baie de stockage distante en ajoutant un volume secondaire à un groupe de miroirs asynchrone existant.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Avant d'exécuter cette commande, le groupe de miroirs asynchrone doit exister et le volume primaire doit exister dans le groupe de miroirs asynchrone. Une fois cette commande terminée, la mise en miroir asynchrone commence entre le volume primaire et le volume secondaire.

Les deux volumes qui comprennent une paire asynchrone en miroir fonctionnent comme une entité unique. L'établissement d'une paire en miroir asynchrone vous permet d'effectuer des actions sur la paire en miroir entière par rapport aux deux volumes individuels.



== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[establish asyncMirror volume="_secondaryVolumeName_"]
pass:quotes[asyncMirrorGroup="_asyncMirrorGroupName_"]
pass:quotes[primaryVolume="_primaryVolumeName_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volume`
 a| 
Nom d'un volume existant sur la matrice de stockage distante que vous souhaitez utiliser pour le volume secondaire. Placez le nom du volume entre guillemets (" ").



 a| 
`asyncMirrorGroup`
 a| 
Nom d'un groupe de miroirs asynchrones existant que vous souhaitez utiliser pour contenir la paire de miroirs asynchrones. Placez le nom du groupe de miroirs asynchrones entre guillemets (" ").



 a| 
`primaryVolume`
 a| 
Nom d'un volume existant sur la matrice de stockage locale que vous souhaitez utiliser pour le volume principal. Placez le nom du volume entre guillemets (" ").

|===


== Remarques

Une paire mise en miroir asynchrone comprend deux volumes, un volume primaire et un volume secondaire, qui contiennent des copies identiques des mêmes données. La paire en miroir fait partie d'un groupe de miroirs asynchrone, qui permet à la paire en miroir de se synchroniser en même temps que toute autre paire en miroir dans le groupe de miroirs asynchrones.

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits d'Union et de traits de soulignement pour les noms. Les noms peuvent comporter un maximum de 30 caractères.

Lorsque vous choisissez le volume primaire et le volume secondaire, le volume secondaire doit être de taille supérieure ou égale à celle du volume primaire. Le niveau RAID du volume secondaire ne doit pas être identique au volume primaire.



== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
