---
permalink: commands-a-z/remove-member-volume-from-consistency-group.html 
sidebar: sidebar 
keywords: remove, member, volume, consistency group 
summary: 'La commande set ConsistenceGroup supprime un volume membre d"un groupe de cohérence snapshot existant.' 
---
= Supprimer le volume membre du groupe de cohérence - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set consistencyGroup` la commande supprime un volume membre d'un groupe de cohérence de snapshot existant.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Si vous le souhaitez, vous pouvez supprimer les membres du volume du référentiel du groupe de cohérence.



== Syntaxe

[source, cli, subs="+macros"]
----
set consistencyGroup pass:quotes[[_"consistencyGroupName"_]]
removeCGMemberVolume=pass:quotes["_memberVolumeName_"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`consistencyGroupName`
 a| 
Nom du groupe de cohérence depuis lequel vous souhaitez supprimer un membre. Placez le nom du groupe de cohérence entre guillemets (" ") dans les crochets ([ ]).



 a| 
`removeCGMemberVolume`
 a| 
Nom du volume membre à supprimer. Placez le nom du groupe de membres entre guillemets (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Détermine si tous les membres du référentiel doivent être supprimés du groupe de cohérence.

|===


== Niveau minimal de firmware

7.83
