---
permalink: commands-a-z/remove-syncmirror.html 
sidebar: sidebar 
keywords: remove, synchronous, mirror 
summary: 'La commande remove SyncMirror supprime la relation de miroir entre le volume primaire et le volume secondaire d"une paire mise en miroir à distance.' 
---
= Supprimer la mise en miroir synchrone – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `remove syncMirror` cette commande supprime la relation de miroir entre le volume primaire et le volume secondaire dans une paire mise en miroir à distance.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800 et E5700, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800 ou E5700, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
Dans les versions précédentes de cette commande, l'identifiant de fonction était `remoteMirror`. Cet identifiant de fonction n'est plus valide et est remplacé par `syncMirror`.

====


== Syntaxe

[source, cli, subs="+macros"]
----
remove syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1 ... volumeNameN_]])
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`localVolume`
 a| 
Le nom du volume primaire (le volume de la matrice de stockage locale) que vous souhaitez supprimer. Placez le nom du volume entre crochets ([ ]). Si le nom du volume comporte des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du volume entre guillemets (" ") à l'intérieur de crochets.



 a| 
`localVolumes`
 a| 
Les noms de plusieurs volumes primaires (les volumes de la matrice de stockage locale) que vous souhaitez supprimer. Entrez les noms des volumes primaires à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Séparez chacun des noms par un espace.


Si les noms de volumes primaires comportent des caractères spéciaux ou ne sont composés que de chiffres, entrez les noms à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.


|===


== Niveau minimal de firmware

6.10
