---
permalink: commands-a-z/remove-volumecopy-target.html 
sidebar: sidebar 
keywords: remove, volume, copy 
summary: La commande Remove VolumeCopy target supprime une paire de copies de volume. 
---
= Supprimer la copie du volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `remove volumeCopy target` commande supprime une paire de copies de volume.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Cette commande est valide pour les paires de copies de volume de snapshot.

[NOTE]
====
Avec la version 7.83 du micrologiciel `copyType=(online | offline)` paramètre n'est plus utilisé.

====


[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
remove volumeCopy target pass:quotes[[_targetName_]] [source pass:quotes[[_sourceName_]]]
----


[[parameters]]
== Paramètres

|===
| Paramètre | Description 


 a| 
`target`
 a| 
Nom du volume cible que vous souhaitez supprimer. Placez le nom du volume cible entre crochets ([ ]). Si le nom du volume cible comporte des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du volume cible entre guillemets (" ") entre crochets.



 a| 
`source`
 a| 
Nom du volume source que vous souhaitez supprimer. Placez le nom du volume source entre crochets ([ ]). Si le nom du volume source comporte des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du volume source entre guillemets (" ") entre crochets.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

5.40

7.83 supprime le `copyType=(online | offline)` paramètre.
