---
permalink: commands-a-z/remove-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, volume, asynchronous, mirror, group 
summary: 'La commande remove volume asynchrones MirrorGroup supprime un volume membre d"un groupe de miroirs asynchrone existant.' 
---
= Supprimer un volume d'un groupe de miroirs asynchrones - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `remove volume asyncMirrorGroup` commande supprime un volume membre d'un groupe de miroirs asynchrone existant.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de stockage.



[[context]]
== Contexte

Vous pouvez également supprimer les membres du volume de référentiel du groupe miroir asynchrone.

Cette commande n'est valide que sur la matrice de stockage locale qui contient le groupe de miroirs asynchrones dont le volume membre à supprimer.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
remove volume pass:quotes[[_"volumeName"_]] asyncMirrorGroup=pass:quotes[_"asyncMirrorGroupName"_]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


[[parameters]]
== Paramètres

|===
| Paramètre | Description 


 a| 
`volume`
 a| 
Nom du volume spécifique que vous souhaitez supprimer du groupe de miroirs asynchrone. Placez le nom du volume entre guillemets (" ") dans les crochets ([ ]).



 a| 
`asyncMirrorGroup`
 a| 
Nom du groupe de miroirs asynchrones qui contient le volume membre que vous souhaitez supprimer. Placez le nom du groupe de miroirs asynchrones entre guillemets (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Détermine si tous les membres du référentiel doivent être supprimés du groupe miroir asynchrone.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
