---
permalink: commands-a-z/reset-storagearray-socbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, soc, baseline 
summary: 'La commande reset storageArray SOCBaseline réinitialise la ligne de base de tous les périphériques SOC (switch on-a-chip) auxquels on accède via les contrôleurs.' 
---
= Réinitialiser la ligne de base SOC de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `reset storageArray SOCBaseline` Commande réinitialise la configuration de base de toutes les unités SOC (switch on-a-chip) accessibles via les contrôleurs.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Cette commande réinitialise la ligne de base en définissant tous les comptages SOC sur 0. Cette commande n'est valide que pour les périphériques Fibre Channel dans une topologie de boucle arbitrée.



[[syntax]]
== Syntaxe

[source, cli]
----
reset storageArray SOCBaseline
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

6.16
