---
permalink: commands-a-z/reset-storagearray-volumedistribution.html 
sidebar: sidebar 
keywords: reset, storage array, volume, distribution 
summary: 'La commande reset storageArray volume distribution (« reset storageArray volume distribution ») réassigne (déplace) tous les volumes vers leur contrôleur préféré.' 
---
= Réinitialiser la distribution des volumes de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `reset storageArray volumeDistribution` réassigne les commandes (déplace) tous les volumes vers leur contrôleur préféré.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Syntaxe

[source, cli]
----
reset storageArray volumeDistribution
----


== Paramètres

Aucune.



== Remarques

Si vous utilisez cette commande sur un hôte sans pilote multichemin, vous devez arrêter les opérations d'E/S vers les volumes jusqu'à ce que cette commande soit terminée pour éviter les erreurs d'application.

Dans certains environnements de système d'exploitation hôte, vous devrez peut-être reconfigurer le pilote d'hôte à chemins multiples. Vous devrez peut-être aussi apporter des modifications au système d'exploitation pour reconnaître le nouveau chemin d'E/S vers les volumes.



== Niveau minimal de firmware

5.20
