---
permalink: commands-a-z/reset-storagearray-socbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, soc, baseline 
summary: 'La commande reset storageArray SOCBaseline réinitialise la ligne de base de tous les périphériques SOC (switch on-a-chip) auxquels on accède via les contrôleurs.' 
---
= Réinitialiser la configuration de base du SOC de la baie de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `reset storageArray SOCBaseline` Commande réinitialise la configuration de base de toutes les unités SOC (switch on-a-chip) accessibles via les contrôleurs.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Cette commande réinitialise la ligne de base en définissant tous les comptages SOC sur 0. Cette commande n'est valide que pour les périphériques Fibre Channel dans une topologie de boucle arbitrée.



== Syntaxe

[source, cli]
----
reset storageArray SOCBaseline
----


== Paramètres

Aucune.



== Niveau minimal de firmware

6.16
