---
permalink: commands-a-z/reset-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: reset, installed, signed, certificate 
summary: La commande reset Controller arrayManagementSignedCertificate réinitialise le certificat signé et les certificats racine/intermédiaire installés sur le contrôleur. Tous les certificats racine et intermédiaire ainsi que tous les certificats signés seront remplacés par un seul certificat auto-signé. 
---
= Réinitialise le certificat signé installé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `reset controller arrayManagementSignedCertificate` commande réinitialise le certificat signé installé et les certificats racine/intermédiaire sur le contrôleur. Tous les certificats racine et intermédiaire ainsi que tous les certificats signés seront remplacés par un seul certificat auto-signé.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
reset controller [(a|b)] arrayManagementSignedCertificate
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet à l'utilisateur de spécifier le contrôleur sur lequel vous souhaitez récupérer les certificats racine/intermédiaire. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).

|===


== Exemples

[listing]
----

SMcli -n Array1 -c "reset controller [a] arrayManagementSignedCertificate;"

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
