---
permalink: commands-a-z/reset-storagearray-sasphybaseline.html 
sidebar: sidebar 
keywords: reset, storage array, sas, phy, baseline 
summary: 'La commande reset storageArray SASPHYBaseline réinitialise la ligne de base SAS Physical Layer (SAS PHY) pour tous les périphériques et supprime la liste des erreurs du fichier .csv.' 
---
= Réinitialiser la ligne de base PHY SAS de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `reset storageArray SASPHYBaseline` Commande réinitialise la ligne de base de la couche physique SAS (SAS PHY) pour tous les périphériques et supprime la liste des erreurs du `.csv` fichier.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Contexte

Le `.csv` le fichier est généré lorsque vous exécutez le `save storageArray SASPHYCounts` commande.

[NOTE]
====
La version précédente de la `reset storageArray SASPHYBaseline` commande effacée compte d'erreurs pour tous les périphériques à l'exception des lecteurs. Le `reset storageArray SASPHYBaseline` Commande réinitialise maintenant la ligne de base du PHY SAS pour les lecteurs et les autres périphériques. Toutes les erreurs sont supprimées du `.csv` fichier.

====


== Syntaxe

[source, cli]
----
reset storageArray SASPHYBaseline
----


== Paramètres

Aucune.



== Niveau minimal de firmware

6.10

7.83 réinitialise la ligne de base du PHY SAS pour les lecteurs.
