---
permalink: commands-a-z/resume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: resume, asynchronous, mirror, group 
summary: La commande RESUME asynchrones MirrorGroup reprend le transfert de données entre toutes les paires symétriques dans un groupe de miroirs asynchrone. 
---
= Reprendre le groupe de miroirs asynchrone
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `resume asyncMirrorGroup` la commande reprend le transfert de données entre toutes les paires mises en miroir d'un groupe de miroirs asynchrone.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les baies E2700, E5600, E2800 et E5700 Tant que tous les paquets SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800 ou E5700, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Les données écrites sur les volumes primaires alors que le groupe de miroirs asynchrone a été suspendu sont immédiatement écrites sur les volumes secondaires. La synchronisation périodique reprend si un intervalle de synchronisation automatique a été défini.



== Syntaxe

[listing, subs="+macros"]
----
resume asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
[deleteRecoveryPointIfNecessary]
----


== Paramètres

|===
| Paramètre | Description 


 a| 
`asyncMirrorGroup`
 a| 
Nom du groupe de miroirs asynchrones pour lequel vous souhaitez démarrer la synchronisation. Placez le nom du groupe de miroirs asynchrones entre guillemets (« ») dans les crochets ([ ]").



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
Paramètre permettant de supprimer le point de récupération si les données de synchronisation récupérables ont dépassé le seuil de récupération. L'âge du point de restauration est mesuré à partir de la période de gel des données sur la baie de stockage primaire.

|===


== Niveau minimal de firmware

7.84

8.10 ajoute le `deleteRecoveryPointIfNecessary` paramètre.
