---
permalink: commands-a-z/resume-snapimage-rollback.html 
sidebar: sidebar 
keywords: resume, snapshot, image, rollback 
summary: 'La commande reprise de l"annulation SnapImage reprend une opération de retour arrière qui est entrée en pause.' 
---
= Reprendre la restauration de l'image instantanée
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `resume snapImage rollback` la commande reprend une opération de retour arrière qui est entrée en pause.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

Une opération de retour arrière peut entrer un état suspendu en raison d'erreurs de traitement, ce qui provoque une condition d'attention requise pour la matrice de stockage.

Si l'opération de retour arrière ne peut pas être reprise, l'image d'instantané sélectionnée revient en pause et la condition d'attention requise s'affiche.

[NOTE]
====
Vous ne pouvez pas utiliser cette commande pour les images Snapshot impliquées dans la copie de volume en ligne.

====


== Syntaxe

[listing, subs="+macros"]
----
resume snapImage pass:quotes[[_snapImageName_]] rollback
----


== Paramètre

|===
| Paramètre | Description 


 a| 
`snapImage`
 a| 
Nom de l'image instantanée pour laquelle vous souhaitez redémarrer une opération de restauration. Le nom d'une image instantanée se compose de deux parties :

* Nom du groupe de snapshots
* Identificateur de l'image snapshot dans le groupe de snapshots


L'identifiant de l'image snapshot peut être l'un des suivants :

* Valeur entière qui est le numéro de séquence du snapshot dans le groupe de snapshots.
* `NEWEST` - Utilisez cette option lorsque vous souhaitez afficher la dernière image instantanée créée dans le groupe de snapshots.
* `OLDEST` - Utilisez cette option lorsque vous souhaitez afficher l'image de snapshot la plus ancienne créée dans le groupe de snapshots.


Placez le nom de l'image snapshot entre guillemets (" ") entre crochets ([ ]).

|===


== Remarques

Le nom d'une image instantanée comporte deux parties séparées par deux points (:) :

* Identifiant du groupe de snapshots
* Identifiant de l'image snapshot


Par exemple, si vous souhaitez redémarrer une opération de restauration pour l'image snapshot 12345 dans un groupe de snapshots qui porte le nom snapgroupe1, utilisez la commande suivante :

[listing]
----
resume snapImage ["snapgroup1:12345"] rollback;
----


== Niveau minimal de firmware

7.83
