---
permalink: commands-a-z/resume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: resume, asynchronous, mirror, group 
summary: La commande RESUME asynchrones MirrorGroup reprend le transfert de données entre toutes les paires symétriques dans un groupe de miroirs asynchrone. 
---
= Reprendre le groupe de miroirs asynchrones - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `resume asyncMirrorGroup` la commande reprend le transfert de données entre toutes les paires mises en miroir d'un groupe de miroirs asynchrone.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de stockage.



[[context]]
== Contexte

Les données écrites sur les volumes primaires alors que le groupe de miroirs asynchrone a été suspendu sont immédiatement écrites sur les volumes secondaires. La synchronisation périodique reprend si un intervalle de synchronisation automatique a été défini.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
resume asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
[deleteRecoveryPointIfNecessary]
----


[[parameters]]
== Paramètres

|===
| Paramètre | Description 


 a| 
`asyncMirrorGroup`
 a| 
Nom du groupe de miroirs asynchrones pour lequel vous souhaitez démarrer la synchronisation. Placez le nom du groupe de miroirs asynchrones entre guillemets (« ») dans les crochets ([ ]").



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
Paramètre permettant de supprimer le point de récupération si les données de synchronisation récupérables ont dépassé le seuil de récupération. L'âge du point de restauration est mesuré à partir de la période de gel des données sur la baie de stockage primaire.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

7.84

8.10 ajoute le `deleteRecoveryPointIfNecessary` paramètre

11.80 baies EF600 et EF300 prises en charge
