---
permalink: commands-a-z/revive-volumegroup.html 
sidebar: sidebar 
keywords: revive, volume, group 
summary: 'La commande ressusciter le groupe de volumes force le groupe de volumes spécifié et ses disques défectueux associés à l"état optimal.' 
---
= Ressusciter le groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `revive volumeGroup` La commande force le groupe de volumes spécifié et ses disques défectueux associés à l'état optimal.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage ou de support.



== Contexte

[NOTE]
====
*Perte possible d'accès aux données* -- l'utilisation correcte de cette commande dépend de la configuration des données de tous les lecteurs du groupe de volumes. Ne tentez jamais de relancer un lecteur à moins que vous ne soyez supervisé par le support technique.

====


== Syntaxe

[listing, subs="+macros"]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----


== Paramètre

|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes à définir sur l'état optimal. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


== Niveau minimal de firmware

6.10
