---
permalink: commands-a-z/revive-volumegroup.html 
sidebar: sidebar 
keywords: revive, volume, group 
summary: 'La commande ressusciter le groupe de volumes force le groupe de volumes spécifié et ses disques défectueux associés à l"état optimal.' 
---
= Réactiver le groupe de volumes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `revive volumeGroup` La commande force le groupe de volumes spécifié et ses disques défectueux associés à l'état optimal.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Support Admin.



[[context]]
== Contexte

[NOTE]
====
*Perte possible d'accès aux données* -- l'utilisation correcte de cette commande dépend de la configuration des données de tous les lecteurs du groupe de volumes. Ne tentez jamais de relancer un lecteur à moins que vous ne soyez supervisé par le support technique.

====


[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----


[[parameter]]
== Paramètre

|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes à définir sur l'état optimal. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

6.10
