---
permalink: commands-a-z/save-controller-nvsram-file.html 
sidebar: sidebar 
keywords: save, controller, nvsram 
summary: La commande Enregistrer le fichier NVSRAM du contrôleur enregistre un ensemble sélectionné de régions NVSRAM du contrôleur dans un fichier. 
---
= Contrôleur de sauvegarde NVSRAM - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `save controller NVSRAM file` Commande enregistre un ensemble sélectionné de régions NVSRAM de contrôleur dans un fichier.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Support Admin.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
save controller [(a|b)] NVSRAM file=pass:quotes["_filename_"]
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Le contrôleur avec les valeurs NVSRAM que vous souhaitez enregistrer. Les identifiants de contrôleur valides sont `a` ou `b`, où `a` Est le contrôleur dans le slot A, et `b` Est le contrôleur associé au slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier dans lequel vous souhaitez enregistrer les valeurs NVSRAM. Placez le nom du fichier NVSRAM entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\logs\nvsramb.txt"`

Le nom par défaut du fichier contenant les valeurs NVSRAM est `nvsram-data.txt`. Cette commande n'ajoute pas automatiquement une extension de fichier au fichier enregistré. Vous devez spécifier une extension de fichier lors de la saisie du nom de fichier.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

6.10
