---
permalink: commands-a-z/save-alltrays-logfile.html 
sidebar: sidebar 
keywords: save, tray log 
summary: La commande enregistrer le fichier journal allplateaux enregistre les données de détection du journal dans un fichier. 
---
= Enregistrer journal bac
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `save allTrays logFile` la commande enregistre les données de détection du journal dans un fichier.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

Les données de log SENSE sont conservées par les cartes environnementales pour chaque bac Toutes les cartes environnementales ne contiennent pas de données de détection de journal.



== Syntaxe

[listing, subs="+macros"]
----
save allTrays logFile=pass:quotes["_filename_"]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`*logFile*`
 a| 
Le chemin du fichier et le nom du fichier dans lequel vous souhaitez enregistrer les données de détection du journal. Placez le nom du fichier entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\logs\traylogdat.txt"`

Cette commande n'ajoute pas automatiquement une extension de fichier au fichier enregistré. Vous devez spécifier une extension de fichier lors de la saisie du nom de fichier.

|===


== Niveau minimal de firmware

6.50
