---
permalink: commands-a-z/save-storagearray-statecapture.html 
sidebar: sidebar 
keywords: save, storage, array, state, capture 
summary: 'La commande Save storageArray State Capture enregistre l"état de la capture d"un tableau de stockage dans un fichier.' 
---
= Enregistrer la capture d'état de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `save storageArray stateCapture` la commande enregistre la capture d'état d'une matrice de stockage dans un fichier.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Syntaxe

[source, cli, subs="+macros"]
----
save storageArray stateCapture file=pass:quotes["_filename_"]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier dans lequel vous souhaitez enregistrer la capture d'état. Placez le nom du fichier entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\logs\state.txt"`

Vous pouvez utiliser n'importe quel nom de fichier, mais vous devez utiliser le `.txt` extension.

Le nom par défaut du fichier contenant la capture d'état est `state-capture-data.txt`. Cette commande n'ajoute pas automatiquement une extension de fichier au fichier enregistré. Vous devez spécifier une extension de fichier lors de la saisie du nom de fichier.

|===