---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, server, certificate, sign, request, csr 
summary: 'La commande save Controller arrayManagementCSR récupère la requête de signature de certificat (RSC) du serveur installé pour le contrôleur afin que vous puissiez afficher les détails du certificat.' 
---
= Récupère le certificat du serveur installé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save controller arrayManagementCSR` commande récupère la requête de signature de certificat (RSC) du serveur installé pour le contrôleur afin que vous puissiez afficher les détails du certificat.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli, subs="+macros"]
----

save controller [(a|b)] arrayManagementCSR file=pass:quotes["_filename_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur à partir duquel vous souhaitez télécharger le certificat signé. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`file`
 a| 
Permet de spécifier le fichier pour lequel enregistrer le fichier de certificat signé du contrôleur.

|===


== Exemples

[listing]
----

SMcli -n Array1 -c "save controller [a] aarrayManagementCSR
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementCSR
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
