---
permalink: commands-a-z/save-storagearray-configuration.html 
sidebar: sidebar 
keywords: save, storage, array, configuration 
summary: La commande save storageArray configuration crée un fichier script que vous pouvez utiliser pour recréer la configuration actuelle du volume de la matrice de stockage. 
---
= Enregistrer la configuration de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `save storageArray configuration` commande crée un fichier script que vous pouvez utiliser pour recréer la configuration actuelle du volume de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage. Cependant, l'utilisation de cette commande avec le paramètre LDAP est limitée aux personnes disposant du rôle d'administrateur de sécurité.



== Contexte

[NOTE]
====
Cette commande n'enregistre pas les données de mise en miroir à distance ou de configuration de copie de volume de la matrice de stockage actuelle dans un fichier.

====


== Syntaxe

[source, cli, subs="+macros"]
----
save storageArray configuration file=pass:quotes["_filename_"]
(allconfig|[globalSettings=(TRUE | FALSE)]
[volumeConfigAndSettings=(TRUE | FALSE)]
[hostTopology=(TRUE | FALSE)]
[lunMappings=(TRUE | FALSE)])
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier dans lequel vous souhaitez enregistrer les paramètres de configuration. Placez le nom du fichier entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\logs\saconf.cfg"`

Le nom par défaut du fichier contenant les paramètres de configuration est `storage-array-configuration.cfg`. Cette commande n'ajoute pas automatiquement une extension de fichier au fichier enregistré. Vous devez spécifier une extension de fichier lors de la saisie du nom de fichier.



 a| 
`allConfig`
 a| 
Paramètre permettant d'enregistrer toutes les valeurs de configuration dans le fichier. (Si vous choisissez ce paramètre, tous les paramètres de configuration sont définis sur `TRUE` .)



 a| 
`globalSettings`
 a| 
Paramètre permettant d'enregistrer les paramètres globaux dans le fichier. Pour enregistrer les paramètres globaux, définissez ce paramètre sur `TRUE`. Pour éviter d'enregistrer les paramètres globaux, définissez ce paramètre sur `FALSE`. La valeur par défaut est `TRUE`.



 a| 
`volumeConfigAndSettings`
 a| 
Paramètre permettant d'enregistrer les paramètres de configuration du volume et tous les paramètres globaux dans le fichier. Pour enregistrer les paramètres de configuration du volume et les paramètres globaux, définissez ce paramètre sur `TRUE`. Pour éviter d'enregistrer les paramètres de configuration du volume et les paramètres globaux, définissez ce paramètre sur `FALSE`. La valeur par défaut est `TRUE`.



 a| 
`hostTopology`
 a| 
Paramètre permettant d'enregistrer la topologie hôte dans le fichier. Pour enregistrer la topologie hôte, définissez ce paramètre sur `TRUE`. Pour éviter d'enregistrer la topologie hôte, définissez ce paramètre sur `FALSE`. La valeur par défaut est `FALSE`.



 a| 
`lunMappings`
 a| 
Paramètre permettant d'enregistrer le mappage LUN ou NSID dans le fichier. Pour enregistrer le mappage de LUN ou NSID, définissez ce paramètre sur `TRUE`. Pour empêcher l'enregistrement du mappage de LUN ou NSID, définissez ce paramètre sur `FALSE`. La valeur par défaut est `FALSE`.

|===


== Remarques

Lorsque vous utilisez cette commande, vous pouvez spécifier n'importe quelle combinaison de paramètres pour le paramètre global, le paramètre de configuration du volume, la topologie hôte ou le mappage de LUN. Si vous souhaitez entrer tous les paramètres, utilisez le `allConfig` paramètre. Vous devez utiliser le `allConfig` ou un ou plusieurs des quatre autres paramètres.



== Niveau minimal de firmware

6.10
