---
permalink: commands-a-z/save-alltrays-logfile.html 
sidebar: sidebar 
keywords: save, tray log 
summary: La commande enregistrer le fichier journal allplateaux enregistre les données de détection du journal dans un fichier. 
---
= Enregistrer le journal du plateau - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `save allTrays logFile` la commande enregistre les données de détection du journal dans un fichier.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Les données de log SENSE sont conservées par les cartes environnementales pour chaque bac Toutes les cartes environnementales ne contiennent pas de données de détection de journal.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
save allTrays logFile=pass:quotes["_filename_"]
----


[[parameter]]
== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`*logFile*`
 a| 
Le chemin du fichier et le nom du fichier dans lequel vous souhaitez enregistrer les données de détection du journal. Placez le nom du fichier entre guillemets (" "). Par exemple :

`file="C:\Program Files\CLI\logs\traylogdat.txt"`

Cette commande n'ajoute pas automatiquement une extension de fichier au fichier enregistré. Vous devez spécifier une extension de fichier lors de la saisie du nom de fichier.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

6.50
