---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, server, certificate 
summary: La commande save Controller arrayManagementSignedCertificate récupère le certificat de serveur installé pour le contrôleur afin que vous puissiez afficher les détails du certificat. 
---
= Récupère le certificat du serveur installé
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `save controller arrayManagementSignedCertificate` la commande récupère le certificat du serveur installé pour le contrôleur afin que vous puissiez afficher les détails du certificat.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de sécurité.



== Syntaxe

[listing, subs="+macros"]
----

save controller [(a|b)] arrayManagementSignedCertificate
     file=pass:quotes["_filename_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur à partir duquel vous souhaitez télécharger le certificat signé. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`file`
 a| 
Permet de spécifier le fichier pour lequel enregistrer le fichier de certificat signé du contrôleur.

|===


== Exemples

[listing]
----

SMcli -n Array1 -c "save controller [a] arrayManagementSignedCertificate
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementSignedCertificate
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
