---
permalink: commands-a-z/set-storagearray-syslog.html 
sidebar: sidebar 
keywords: update, storage, array, syslog, configuration 
summary: 'La commande set storageArray syslog permet de modifier l"adresse, le protocole ou le numéro de port du serveur syslog.' 
---
= Mettre à jour la configuration du journal système de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray syslog` commande permet de modifier l'adresse du serveur syslog, le protocole ou le numéro de port.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
set storageArray syslog id="<id>"
serverAddress="<address>"
port=<port> protocol=("udp" | "tcp" | "tls")
components=(componentName=("auditLog") ...)
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`serverAddress`
 a| 
Nom d'hôte ou adresse IP du récepteur syslog.



 a| 
`port`
 a| 
Numéro de port du récepteur syslog.



 a| 
`protocol`
 a| 
Protocole de transmission Syslog Les valeurs acceptables incluent UDP, TCP ou TLS.



 a| 
`components`
 a| 
Liste des entrées de composant qui seront consignées sur le serveur syslog. Actuellement, seuls les journaux d'audit sont pris en charge.



 a| 
`componentName`
 a| 
Nom du composant ; actuellement, seul « auditlog » est pris en charge.

|===


=== Exemple

[listing]
----
SMcli -n Array1 -c "set storageArray syslog
id=\"331998fe-3154-4489-b773-b0bb60c6b48e\"
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e Server Address: 192.168.2.1
Port: 514 Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Niveau minimal de firmware

8.42
