---
permalink: commands-a-z/set-snapvolume-increase-decreaserepositorycapacity.html 
sidebar: sidebar 
keywords: set, snapshot, volume, repository, capacity 
summary: 'La commande set snapVolume augmentée/decreRepositoryCapacity augmente ou diminue la capacité d"un volume de référentiel de volume de snapshot.' 
---
= Définir la capacité du volume du référentiel de volumes instantanés - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set snapVolume increase/decreaseRepositoryCapacity` la commande permet d'augmenter ou de réduire la capacité d'un volume de référentiel de volumes snapshot.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe permettant d'augmenter la capacité

[source, cli, subs="+macros"]
----
set snapVolume[“snapVolumeName”] increaseRepositoryCapacity
(repositoryVolumes="repos_xxxx" |
repositoryVolumes=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]] |
repositoryVolumes=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]])
----


== Syntaxe pour la réduction de la capacité

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] decreaseRepositoryCapacity
count=pass:quotes[_numberOfVolumes_]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume de snapshot pour lequel vous définissez les propriétés. Placez l'identificateur de volume de snapshot entre guillemets (" ") à l'intérieur de crochets ([ ]).



 a| 
`repositoryVolume`
 a| 
Nom du volume du référentiel pour lequel vous souhaitez augmenter la capacité. Un volume standard disponible est ajouté au volume du référentiel pour augmenter la capacité du volume du référentiel.

Vous disposez de deux options pour définir le nom d'un volume de référentiel :

* Utiliser un volume de référentiel existant : nom
* Créez un nouveau volume de référentiel lorsque vous exécutez cette commande


Le nom d'un volume de référentiel existant comprend deux parties :

* Le terme « repos »
* Un identificateur numérique à quatre chiffres que vous attribuez au nom du volume du référentiel


Placez le nom du volume de référentiel existant entre guillemets (" ").

Si vous souhaitez créer un nouveau volume de référentiel lorsque vous exécutez cette commande, vous devez entrer le nom d'un groupe de volumes ou d'un pool de disques dans lequel vous voulez que le volume de référentiel soit. Vous pouvez également définir la capacité du volume du référentiel. Si vous souhaitez définir la capacité, vous pouvez utiliser les valeurs suivantes :

* Valeur entière représentant un pourcentage de la capacité du volume de base
* Valeur décimale représentant un pourcentage de la capacité du volume de base
* Taille spécifique du volume du référentiel. La taille est définie en unités de `bytes`, `KB`, `MB`, `GB`, ou `TB`.


Si vous n'utilisez pas l'option Capacity, le logiciel de gestion du stockage définit la capacité sur 20 % de la capacité du volume de base.

Placez le nom du nouveau volume de référentiel entre parenthèses.



 a| 
`count`
 a| 
Le nombre de volumes à supprimer. Utiliser des valeurs entières.

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.

Un volume de référentiel de snapshot est un volume extensible structuré comme une collection concaténée de 16 entités de volumes standard au maximum. Dans un premier temps, un volume de référentiel extensible ne comporte qu'un seul élément. La capacité du volume de référentiel extensible est exactement celle de l'élément unique. Vous pouvez augmenter la capacité d'un volume de référentiel extensible en y ajoutant des volumes standard. La capacité du volume de référentiel extensible composite devient alors la somme des capacités de tous les volumes standard concaténés.

Un volume de référentiel de groupe de snapshots doit répondre à une exigence de capacité minimale pouvant somme des éléments suivants :

* 32 Mo pour la prise en charge de la surcharge fixe pour le groupe de snapshots et pour le traitement de la copie sur écriture.
* Capacité pour le traitement de retour arrière, qui correspond à 1/5000e de la capacité du volume de base.


La capacité minimale est respectée par le micrologiciel du contrôleur et le logiciel de gestion du stockage.



== Niveau minimal de firmware

7.83
