---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: 'La commande set volume Volume Group définit les propriétés d"un groupe de volumes.' 
---
= Définissez le groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set volumeGroup` commande définit les propriétés d'un groupe de volumes.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
Vous ne devez effectuer qu'une seule opération (ajout de disques, modification du niveau RAID ou modification de la propriété du groupe de volumes) par commande. Vous ne pouvez pas effectuer plusieurs opérations avec une seule commande.

====


== Syntaxe

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes pour lequel vous souhaitez définir les propriétés. Placez le nom du groupe de volumes entre crochets ([ ]).



 a| 
`addDrives`
 a| 
L'emplacement du lecteur que vous souhaitez ajouter au groupe de volumes. Pour les tiroirs disques haute capacité, spécifiez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID du logement pour le lecteur. Pour les tiroirs disques basse capacité, spécifiez la valeur d'ID du bac et la valeur d'ID du logement pour le lecteur. Les valeurs d'ID du bac sont `0` à `99`. Les valeurs d'ID de tiroir sont `1` à `5`.

La capacité maximale de tous les emplacements est de 24. Les valeurs d'ID de fente commencent à 0 ou 1, selon le modèle de bac. Les tiroirs disques compatibles avec les contrôleurs E2800 et E5700 ont des numéros d'ID de slot commençant à 0. Les tiroirs disques compatibles avec les contrôleurs E2700 et E5600 possèdent des numéros d'ID de slot commençant à 1.

Placez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID de logement entre crochets ([ ]).



 a| 
`raidLevel`
 a| 
Niveau RAID du groupe de volumes. Les valeurs valides sont `0`, `1`, `3`, `5`, ou `6`.



 a| 
`owner`
 a| 
Contrôleur qui possède le groupe de volumes. Les identifiants de contrôleur valides sont `a` ou `b`, où `a` Est le contrôleur dans le slot A , et `b` Est le contrôleur associé au slot B. Utilisez ce paramètre uniquement si vous souhaitez modifier le propriétaire du groupe de volumes.

|===


== Remarques

Des erreurs d'E/S hôte peuvent entraîner des groupes de volumes comprenant plus de 32 volumes. Cette opération peut également entraîner le redémarrage du contrôleur interne, car la période d'expiration se termine avant que la définition du groupe de volumes ne soit définie. Si vous rencontrez ce problème, effectuez une mise au repos des opérations d'E/S de l'hôte, puis réessayez la commande.

Lorsque vous utilisez cette commande, vous ne pouvez spécifier qu'un seul des paramètres.

[NOTE]
====
Spécification du `addDrives` ou le `raidLevel` paramètre démarre une opération de longue durée que vous ne pouvez pas arrêter.

====
Le `addDrives` paramètre prend en charge à la fois les tiroirs disques haute capacité et les tiroirs disques basse capacité. Un tiroir de disque haute capacité est doté de tiroirs qui maintiennent les disques. Les tiroirs coulissent hors du tiroir du lecteur pour permettre l'accès aux lecteurs. Un tiroir de lecteur de faible capacité n'est pas doté de tiroirs. Pour un plateau de lecteur haute capacité, vous devez spécifier l'identifiant (ID) du plateau de lecteur, l'ID du tiroir et l'ID du logement dans lequel se trouve un lecteur. Dans le cas d'un plateau de lecteur de faible capacité, vous devez uniquement spécifier l'ID du plateau de lecteur et l'ID de l'emplacement dans lequel se trouve un lecteur. Pour un plateau de lecteur de faible capacité, une autre méthode d'identification d'un emplacement est de spécifier l'ID du plateau de lecteur, définissez l'ID du tiroir sur `0`, Et indiquez l'ID de l'emplacement dans lequel réside un lecteur.



== Dépannage

Toute tentative d'extension de groupes de volumes importants par l'ajout de lecteurs, également appelés DCE (Dynamic Capacity extension), peut échouer avec le message suivant :

`Return code: Error 26 - The modification operation cannot complete because of the number of drives in the volume group and the segment size of the associated volumes. Reduce the segment size of all volumes in the volume group to 128 KB or below using the Change Segment Size option. Then, retry the operation.`

Les systèmes exécutant le micrologiciel 7.35.xx.xx peuvent échouer avec le message suivant au lieu de celui indiqué ci-dessus :

`Return code: Error 462 - A SYMbol procedure could not be carried out because the firmware could not allocate sufficient cache memory. Operation when error occurred: PROC_startVolum`

Outre les messages ci-dessus, un événement MEL (Major Event Log) indiquant un cache insuffisant pour terminer l'opération DCE peut se produire.

Tout contrôleur exécutant le micrologiciel 7.xx peut rencontrer ce problème.

Le DCE requiert suffisamment de mémoire tampon pour mettre en mémoire tampon les données lues à partir du volume d'origine et les données à écrire dans le volume étendu. La combinaison du nombre de lecteurs dans l'opération d'extension, de la taille des bandes et de l'activation ou non des opérations de miroir peut entraîner un manque de mémoire disponible pour terminer l'opération DCE.

Si la situation ci-dessus est présente, les solutions possibles sont les suivantes :

* Créez la taille de groupe souhaitée à l'aide d'autres disques non assignés.
* Supprimez le groupe de volumes actuel, puis recréez le groupe de volumes avec le nombre de lecteurs souhaité.
* Réduisez la taille du segment utilisé, puis recommencez l'opération.
* Si possible, ajoutez de la mémoire supplémentaire au contrôleur, puis réessayez l'opération.




== Niveau minimal de firmware

7.10 ajoute la fonction RAID 6.

7.30 supprime le `availability` paramètre.

7.60 ajoute le `drawerID` saisie utilisateur.
