---
permalink: commands-a-z/set-storagearray-resourceprovisionedvolumes.html 
sidebar: sidebar 
keywords: set, storage, array, resource, provisioned, volumes 
summary: La commande set storageArray resourceprovisionnédvolumes désactive la fonction DULBE. 
---
= Définir les volumes provisionnés des ressources de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray resourceProvisionedVolumes` La commande désactive la fonction DULBE.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les baies EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage EF600, EF300, EF50 et EF80, vous devez disposer du rôle Storage Admin.



[[context]]
== Contexte

Le provisionnement des ressources est une fonctionnalité disponible qui permet d'initialiser rapidement de grands volumes.

Un volume provisionné de ressource est un volume lourd dans un groupe ou un pool de volume SSD, où la capacité de disque est allouée (affectée au volume) lors de la création du volume, mais la désallocation des blocs de disque est effectuée (non mappée). Lorsqu'un volume de ressource est provisionné, il n'y a pas d'initialisation en arrière-plan limitée dans le temps. À la place, chaque bande RAID est initialisée lors de la première écriture sur un bloc de volume dans la bande

Les volumes provisionnés de ressource ne sont pris en charge que sur les pools et les groupes de volumes SSD, où tous les disques du groupe ou du pool prennent en charge la fonction de récupération d'erreur DULBE (Logical Block Error Enable, deallocalisé ou non écrit) de NVMe. Lors de la création d'un volume provisionné de ressource, tous les blocs de disques attribués au volume sont désalloué (non mappés). La gestion de la conservation des blocs peut améliorer la durée de vie du disque SSD et accroître des performances d'écriture maximales. L'amélioration varie selon le modèle de disque et la capacité.



[[syntax]]
== Syntaxe

[source, cli]
----
set storageArray resourceProvisionedVolumes=(enable|disable)
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`resourceProvisionedVolumes`
 a| 
Paramètre permettant de spécifier si les capacités de provisionnement des ressources sont activées. Pour désactiver le provisionnement de ressources, définissez ce paramètre sur `disable`. La valeur par défaut est `enable`.

[NOTE]
====
La modification de cette valeur s'applique uniquement aux groupes de volumes et aux pools créés ultérieurement. Elle ne modifie pas la valeur des groupes de volumes et des pools existants.

====
|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.63
