---
permalink: commands-a-z/set-volumegroup-forcedstate.html 
sidebar: sidebar 
keywords: set, volume, group, forced, state 
summary: La commande set Volume Group forcedState déplace un groupe de volumes à un état forcé. 
---
= Définir l'état forcé du groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set volumeGroup forcedState` Commande déplace un groupe de volumes à un état forcé.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Utilisez cette commande si `start volumeGroup import` La commande ne déplace pas le groupe de volumes vers un état importé ou si l'opération d'importation ne fonctionne pas en raison d'erreurs matérielles. Dans un état forcé, le groupe de volumes peut être importé et vous pouvez ensuite identifier les erreurs matérielles.



== Syntaxe

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]] forcedState
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes que vous souhaitez placer à l'état forcé. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


== Remarques

Vous pouvez déplacer les lecteurs qui composent un groupe de volumes d'une matrice de stockage vers une autre matrice de stockage. L'interface de ligne de commande propose trois commandes qui vous permettent de déplacer les disques. Les commandes sont `start volumeGroup export`, `start volumeGroup import`, et `set volumeGroup forcedState`.

Dans l'état forcé, vous pouvez effectuer une opération d'importation sur le groupe de volumes.



== Niveau minimal de firmware

7.10
