---
permalink: commands-a-z/set-autosupport-https-delivery-method.html 
sidebar: sidebar 
keywords: 'Specify AutoSupport HTTP(S) delivery method' 
summary: 'La commande set storageArray AutoSupport livyMethod définit la méthode de livraison pour l"envoi des messages AutoSupport au protocole HTTP(S).' 
---
= Spécifier la méthode de livraison http(s) AutoSupport - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray autoSupport deliveryMethod` Commande configure la méthode de distribution pour l'envoi des messages AutoSupport au protocole HTTP(S).



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage ou d'administrateur du support.



== Syntaxe

[source, cli, subs="+macros"]
----

set storageArray autoSupport deliveryMethod=email mailRelayServer="mail.example.com" senderEmail="sender@example.com"
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`deliveryMethod`
 a| 
Permet à l'utilisateur de spécifier la méthode de livraison de la collection AutoSupport. Les choix valides sont les suivants :

* e-mail
* HTTPS


[NOTE]
====
Si la méthode de messagerie est configurée, AutoSupport OnDemand et diagnostic à distance sont désactivés.

====


 a| 
`direct`
 a| 
Permet à l'utilisateur de se connecter directement aux systèmes de support technique de destination à l'aide du protocole HTTP ou HTTPS.



 a| 
`proxyConfigScript`
 a| 
Permet à l'utilisateur de spécifier l'emplacement d'un fichier de script PAC (Proxy Auto-Configuration)



 a| 
`proxyServer`
 a| 
Permet à l'utilisateur de spécifier les détails du serveur proxy HTTP(S) requis pour établir la connexion avec le système de support technique de destination.



 a| 
`hostAddress`
 a| 
Permet à l'utilisateur de spécifier l'adresse hôte du serveur proxy. Requis si le proxyserver est utilisé.



 a| 
`portNumber`
 a| 
Permet à l'utilisateur de spécifier le numéro de port du serveur proxy. Requis si le proxyserver est utilisé.



 a| 
`username`
 a| 
Permet à l'utilisateur de spécifier le nom d'utilisateur du serveur proxy s'il est configuré.



 a| 
`password`
 a| 
Permet à l'utilisateur de spécifier le mot de passe du serveur proxy s'il est configuré.

|===


== Niveau minimal de micrologiciel

8.40



== Exemples

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


== Vérification

Envoyer un message de test à l'aide du `start storageArray autoSupport deliveryTest` commande pour vérifier que vos méthodes de livraison sont correctement configurées.



== Niveau minimal de firmware

8.40
