---
permalink: commands-a-z/set-cgsnapvolume.html 
sidebar: sidebar 
keywords: set, consistency, group, snapshot, volume 
summary: 'La commande set cgSnapVolume crée un nom unique pour un volume snapshot d"un groupe de cohérence.' 
---
= Définissez le volume Snapshot du groupe de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set cgSnapVolume` la commande crée un nom unique pour un volume de snapshot d'un groupe de cohérence.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
set cgSnapVolume pass:quotes[[_cgSnapVolumeName_]]
userLabel=pass:quotes["_cgSnapVolumeName_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`cgSnapVolume`
 a| 
Nom du volume de groupe de cohérence à renommer. Placez le nom du volume de snapshot du groupe de cohérence entre crochets ([ ]).



 a| 
`userLabel`
 a| 
Nouveau nom à attribuer au volume Snapshot du groupe de cohérence. Placez le nouveau nom du volume snapshot entre guillemets (" ").

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



== Niveau minimal de firmware

7.83
