---
permalink: commands-a-z/set-storagearray-hostconnectivityreporting.html 
sidebar: sidebar 
keywords: enable, disable, host, connectivity, report 
summary: La commande set storageArray hostConnectivtyReporting active ou désactive les rapports de connectivité hôte sur le contrôleur. 
---
= Activer ou désactiver les rapports de connectivité de l'hôte - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray hostConnectivityReporting` la commande active ou désactive les rapports de connectivité hôte sur le contrôleur.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli]
----
set storageArray hostConnectivityReporting (enable | disable)
----


== Contexte

Lorsque vous activez les rapports sur la connectivité hôte sur la baie de stockage, la baie de stockage surveille en permanence la connexion entre les contrôleurs de la baie de stockage et les hôtes configurés et vous alerte si la connexion est interrompue en raison d'un câble desserré, endommagé ou manquant ou d'autres problèmes au niveau de l'hôte. Vous êtes également averti si le type d'hôte n'est pas spécifié correctement sur la matrice de stockage (ce qui peut entraîner des problèmes de basculement).

[NOTE]
====
Pour désactiver les rapports sur la connectivité hôte, vous devez d'abord désactiver l'équilibrage automatique de la charge.

====
[NOTE]
====
Si l'équilibrage automatique de la charge est désactivé, le reporting de la connectivité hôte reste activé.

====
[NOTE]
====
Les rapports de connectivité hôte et la fonction d'équilibrage automatique de la charge ne sont disponibles que sur les types d'hôtes Linux DHALUA, Windows/Windows clustered et VMware.

====


== Paramètres

Aucune.



== Niveau minimal de firmware

8.42 Nouveau paramètre de commande.
