---
permalink: commands-a-z/set-snapvolume-mediascanenabled.html 
sidebar: sidebar 
keywords: set, snapshot, volume, media, scan 
summary: La commande set snapVolume mediaScanEnabled exécute une analyse des supports sur les lecteurs utilisés pour un volume de snapshot. 
---
= Définir l'analyse multimédia du volume d'instantanés - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set snapVolume mediaScanEnabled` commande exécute une analyse des supports sur les lecteurs utilisés pour un volume de snapshot.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Vous pouvez également effectuer une vérification de redondance sur les données.



== Syntaxe

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]]
mediaScanEnabled=(TRUE | FALSE) [redundancyCheckEnabled=(TRUE | FALSE)]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume de snapshot pour lequel vous définissez les propriétés. Placez l'identificateur de volume de snapshot entre guillemets (" ") à l'intérieur de crochets ([ ]).



 a| 
`mediaScanEnabled`
 a| 
Paramètre permettant d'activer ou de désactiver la recherche multimédia pour le volume d'instantané. Pour activer l'analyse des supports, définissez ce paramètre sur `TRUE`. Pour désactiver la numérisation de support, définissez ce paramètre sur `FALSE`. (Si l'analyse des supports est désactivée au niveau de la matrice de stockage, ce paramètre n'a aucun effet.)



 a| 
`redundancyCheckEnabled`
 a| 
Paramètre permettant d'activer ou de désactiver la vérification de redondance lors d'une analyse de support. Pour activer la vérification de redondance, définissez ce paramètre sur `TRUE` . Pour désactiver la vérification de redondance, définissez ce paramètre sur `FALSE`.

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



== Niveau minimal de firmware

7.83
