---
permalink: commands-a-z/set-storagearray-usersession.html 
sidebar: sidebar 
keywords: set, storage, array, user, session 
summary: La commande set storageArray usersession vous permet de définir un délai dans System Manager, de sorte que les sessions inactives des utilisateurs soient déconnectées après un délai spécifié. 
---
= Définir la session utilisateur de la baie de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `set storageArray userSession` La commande vous permet de définir une temporisation dans System Manager, afin que les sessions inactives des utilisateurs soient déconnectées au bout d'une heure spécifiée.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de sécurité.



== Contexte

Utilisez cette commande pour effectuer l'une des opérations suivantes :

* Définissez un délai d'attente en secondes pour les sessions utilisateur. La valeur minimale de temporisation est de 900 secondes (15 minutes).
* Désactivez les délais d'expiration de session en définissant la valeur sur 0.




== Paramètres

Aucune.



== Syntaxe

[listing]
----
set storageArray userSession sessionTimeout=n
----


== Niveau minimal de firmware

8.41
