---
permalink: commands-a-z/set-snapvolume.html 
sidebar: sidebar 
keywords: rename, snapshot, volume 
summary: La commande set snapVolume renomme un instantané existant. 
---
= Renommer le volume snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `set snapVolume` commande renomme un volume snapshot existant.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Syntaxe

[listing, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] userLabel=pass:quotes["_snapImageVolumeName_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume de snapshot à renommer. Placez le nom du volume de snapshot entre guillemets (" ") à l'intérieur de crochets ([ ]).



 a| 
`userLabel`
 a| 
Nouveau nom à attribuer au volume snapshot. Placez le nouveau nom du volume snapshot entre guillemets (" ").

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



== Niveau minimal de firmware

7.83
