---
permalink: commands-a-z/set-snmptrapdestination-trapreceiverip.html 
sidebar: sidebar 
keywords: update, snmp, trap, destination 
summary: 'La commande set snmpTrapdestination trapReceiverIP active ou désactive l"envoi de messages d"échec d"authentification pour une destination d"interruption SNMP. L"échec se produit lorsque l"agent SNMP a reçu un message d"un gestionnaire SNMP, mais que le message contenait un nom de communauté ou un nom d"utilisateur non valide.' 
---
= Mettre à jour la destination du trap SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set snmpTrapDestination trapReceiverIP` La commande active ou désactive l'envoi de messages d'échec d'authentification pour une destination d'interruption SNMP. L'échec se produit lorsque l'agent SNMP a reçu un message d'un gestionnaire SNMP, mais que le message contenait un nom de communauté ou un nom d'utilisateur non valide.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage ou d'administrateur du support.



== Syntaxe

[source, cli, subs="+macros"]
----
set snmpTrapDestination trapReceiverIP=ipAddress
(communityName=pass:quotes["_communityName_"] | (userName=pass:quotes["_userName_"] [engineId=(local | engineId)]))
[sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`trapReceiverIP`
 a| 
Adresse IP du gestionnaire SNMP auquel vous souhaitez envoyer des messages d'interruption.



 a| 
`communityName`
 a| 
Nom de la communauté SNMP pour laquelle vous voulez envoyer des messages d'interruption.



 a| 
`userName`
 a| 
Nom de l'utilisateur SNMP pour lequel vous voulez envoyer des messages d'interruption.



 a| 
`engineId`
 a| 
ID du moteur de l'utilisateur SNMP pour lequel vous voulez envoyer des messages d'interruption. L'ID du moteur est requis si plusieurs utilisateurs USM ont le même nom d'utilisateur. La valeur peut être «[.code]``local``" Pour spécifier l'agent SNMP local est l'agent faisant autorité ou une chaîne de chiffres hexadécimaux pour spécifier un ID de moteur d'agent SNMP distant.



 a| 
`sendAuthenticationFailureTraps`
 a| 
Ce paramètre active ou désactive l'envoi de messages d'échec d'authentification à un gestionnaire SNMP. Pour envoyer des messages d'échec d'authentification, définissez le paramètre sur `TRUE`. Pour empêcher l'envoi de messages d'échec d'authentification, définissez le paramètre sur `FALSE`. La valeur par défaut est `TRUE`.

|===


== Niveau minimal de firmware

8.30
