---
permalink: commands-a-z/set-iscsitarget.html 
sidebar: sidebar 
keywords: set, iscsi, target, properties 
summary: 'La commande set iscsiTarget définit les propriétés d"une cible iSCSI.' 
---
= Définissez les propriétés de la cible iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `set iscsiTarget` Commande définit les propriétés d'une cible iSCSI.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.

[NOTE]
====
Cette commande est obsolète et est remplacée par le xref:set-target.adoc[Définissez les propriétés de la cible] commande.

====


== Syntaxe

[listing, subs="+macros"]
----
set iscsiTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`iscsiTarget`
 a| 
Cible iSCSI pour laquelle vous souhaitez définir les propriétés. Placez le `_userLabel_` en guillemets doubles (" "). Vous devez également inclure le `_userLabel_` Entre crochets ([ ]) si le libellé de l'utilisateur est un alias cible ou des crochets d'angle ( ) si le libellé de l'utilisateur est un nom qualifié iSCSI (IQN).



 a| 
`authenticationMethod`
 a| 
Les moyens d'authentification de votre session iSCSI.



 a| 
`chapSecret`
 a| 
Clé de sécurité que vous souhaitez utiliser pour authentifier une connexion homologue.



 a| 
`targetAlias`
 a| 
Le nouveau nom que vous souhaitez utiliser pour la cible. Placez le nom entre guillemets (" ").

|===


== Remarques

Le protocole CHAP (Challenge Handshake Authentication Protocol) est un protocole qui authentifie l'homologue d'une connexion. CHAP est basé sur les pairs partageant un _secret_. Un secret est une clé de sécurité similaire à un mot de passe.

Utilisez le `chapSecret` paramètre pour configurer les clés de sécurité des initiateurs qui exigent une authentification mutuelle. Le secret CHAP doit comporter entre 12 et 57 caractères. Ce tableau répertorie les caractères valides.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Espace
 a| 
!
 a| 
«
 a| 
#
 a| 
$
 a| 
%
 a| 
Et
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
A
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
JE
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
Q
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
a
 a| 
b
 a| 
c
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
je
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p
 a| 
q
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== Niveau minimal de firmware

7.10

8.41 cette commande est obsolète.
