---
permalink: commands-a-z/set-storagearray-loginbanner.html 
sidebar: sidebar 
keywords: set, storage, array, login, banner 
summary: 'La commande set storageArray loginBanner vous permet de télécharger un fichier texte à utiliser comme bannière de connexion. Le texte de la bannière peut inclure un avis d"avertissement et un message de consentement qui sont présentés aux utilisateurs avant d"établir des sessions dans SANtricity System Manager ou avant d"exécuter des commandes.' 
---
= Définir la bannière de connexion à la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray loginBanner` commande vous permet de télécharger un fichier texte à utiliser comme bannière de connexion. Le texte de la bannière peut inclure un avis d'avertissement et un message de consentement qui sont présentés aux utilisateurs avant d'établir des sessions dans SANtricity System Manager ou avant d'exécuter des commandes.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
set storageArray loginBanner file="path_to_login_banner"
----


== Contexte

Une fois le fichier texte chargé, il est enregistré dans la matrice de stockage. Le texte de la bannière apparaît avant l'écran de connexion de SANtricity System Manager ou avant d'exécuter des commandes.



== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`file`
 a| 
Le chemin du fichier et le nom du fichier dans lequel le fichier texte de la bannière de connexion est stocké.

[NOTE]
====
Le fichier de bannière de connexion ne peut pas être vide et doit être inférieur ou supérieur à 5 Ko.

====
|===


== Niveau minimal de firmware

8.41
