---
permalink: commands-a-z/set-snmpsystemvariables.html 
sidebar: sidebar 
keywords: update, snmp, mib, system, group, variables 
summary: 'La commande set snmpSystemvariables modifie les variables système du protocole SNMP (simple Network Management Protocol).' 
---
= Mettre à jour les variables du groupe système SNMP MIB II - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set snmpSystemVariables` Commande modifie les variables système du protocole SNMP (simple Network Management Protocol).



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Support Admin.



[[context]]
== Contexte

Les variables système suivantes sont conservées dans une base de données MIB-II (Management information base II) :

* Nom du système
* Nom du contact système
* Emplacement du système




[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
set snmpSystemVariables
[sysName=pass:quotes[_newSystemName_]]
[sysContact=pass:quotes[_contactName_]]
[sysLocation=pass:quotes[_systemLocation_]]
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`sysName`
 a| 
Le nouveau nom que vous souhaitez donner au système SNMP. Utiliser les conventions SNMP et MIB standard pour le nom du système. Placez le nom du système SNMP entre crochets ([ ]).



 a| 
`sysContact`
 a| 
Nom de la personne à contacter pour le système géré avec des informations sur la façon de contacter cette personne. Placez le nom du contact SNMP entre crochets ([ ]).



 a| 
`sysLocation`
 a| 
L'emplacement physique du système, tel que « 3rd flr ». Placez l'emplacement du système SNMP entre crochets ([ ]).

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.30
