---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: 'La commande set storageArray passwordlength permet à l"utilisateur admin de définir une longueur minimale pour tous les mots de passe nouveaux ou mis à jour sur la matrice de stockage.' 
---
= Définir la longueur du mot de passe de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `set storageArray passwordlength` commande permet à l'utilisateur admin de définir une longueur minimale pour tous les mots de passe nouveaux ou mis à jour sur la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur de sécurité.



== Syntaxe

[source, cli]
----
set storageArray passwordLength=<INTEGER>
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`password length`
 a| 
Permet de définir la longueur minimale requise pour tous les mots de passe nouveaux ou mis à jour.



 a| 
`INTEGER`
 a| 
Permet de définir la longueur minimale requise, entre 0 et 30, pour tous les mots de passe nouveaux ou mis à jour.

|===


== Exemples

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


== Niveau minimal de firmware

8.41 ajoute la commande.
