---
permalink: commands-a-z/show-storagearray-dbmdatabase.html 
sidebar: sidebar 
keywords: show, storage, array, dbm, database 
summary: 'La commande show storageArray dbmDatabase récupère et affiche les métadonnées pour les emplacements de sauvegarde intégrés d"une matrice de stockage. Lorsque plusieurs emplacements de sauvegarde sont disponibles, les métadonnées sont affichées pour chaque emplacement.' 
---
= Afficher la base de données DBM de la matrice de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray dbmDatabase` la commande récupère et affiche les métadonnées pour les emplacements de sauvegarde intégrés d'une matrice de stockage. Lorsque plusieurs emplacements de sauvegarde sont disponibles, les métadonnées sont affichées pour chaque emplacement.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle Administrateur du stockage ou moniteur de stockage.



== Syntaxe

[source, cli]
----
show storageArray dbmDatabase
----


== Paramètres

Aucune.



== Remarques

Cette commande renvoie les informations de la base de données de configuration dans un format similaire à cet exemple.

`Configuration Database MetadataLast Host Backup: <date stamp>`

[cols="7*"]
|===
| CTL | EMPLACEMENT | RÉVISION | ID | NUMÉRO DE GÉNÉRATION | ÉTAT | MODE D'ACCÈS 


 a| 
A
 a| 
Cache
 a| 
X.Y
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Optimale



 a| 
B
 a| 
Cache
 a| 
X.Y
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Optimale



 a| 
S/O
 a| 
Disque
 a| 
X.Y
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Optimale

|===


== Niveau minimal de firmware

7.83
