---
permalink: commands-a-z/show-storagearray-unconfiguredinitiators.html 
sidebar: sidebar 
keywords: show, unconfigured, initiators 
summary: La commande show storageArray unconfigurerdInitiators renvoie une liste des initiateurs détectés par la matrice de stockage, mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage. 
---
= Afficher les initiateurs non configurés - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray unconfiguredInitiators` commande renvoie une liste d'initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.

Cette commande remplace le link:show-storagearray-unconfigurediscsiinitiators.html["Affiche storageArray unconfigdIssiInitiators"] commande.



[[syntax]]
== Syntaxe

[source, cli]
----
show storageArray unconfiguredInitiators
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

8.50
