---
permalink: commands-a-z/show-storagearray-powerinfo.html 
sidebar: sidebar 
keywords: show, storage, array, power, information 
summary: 'La commande show storageArray powerInfo renvoie des informations sur la quantité d"énergie consommée par l"ensemble de la matrice de stockage et chaque bac de la matrice de stockage.' 
---
= Affiche les informations d'alimentation de la matrice de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray powerInfo` la commande renvoie des informations sur la quantité d'énergie consommée par l'ensemble de la matrice de stockage et chaque plateau de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle Administrateur du stockage ou moniteur de stockage.



== Syntaxe

[source, cli]
----
show storageArray powerInfo
----


== Paramètres

Aucune.



== Remarques

Cette commande renvoie des informations de consommation d'énergie similaires à cet exemple.

[listing]
----
total power drawn: 310 watts
number of trays: 1
tray power input details:
   tray id  power supply serial number  input power
   0        0                           160 watts
   0        1                           150 watts
----


== Niveau minimal de firmware

8.10
