---
permalink: commands-a-z/show-volumecopy-sourcecandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, source, candidates 
summary: La commande show VolumeCopy sourceCandidates renvoie des informations sur les volumes candidats que vous pouvez utiliser comme source pour une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot. 
---
= Afficher les candidats sources de copie de volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show volumeCopy sourceCandidates` commande renvoie des informations sur les volumes candidats que vous pouvez utiliser comme source pour une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



== Syntaxe

[source, cli]
----
show volumeCopy sourceCandidates
----


== Paramètres

Aucune.



== Remarques

Cette commande renvoie les informations de source de copie de volume comme indiqué dans cet exemple.

[listing]
----
Volume Name: finance
   Capacity: 4.0 GB
   Volume Group: 1
Volume Name: engineering
   Capacity: 4.0 GB
   Volume Group: 2
----