---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: La commande show allDrives renvoie des informations sur les lecteurs de la matrice de stockage. 
---
= Afficher le lecteur
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show allDrives` la commande renvoie des informations sur les lecteurs de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

Pour chaque lecteur de la matrice de stockage, cette commande renvoie les informations suivantes :

* Nombre total de disques
* Le type de disque (SAS, ou NVMe4K)
* Informations sur le lecteur de base :
+
** L'emplacement du bac et l'emplacement du logement
** Le statut
** La capacité
** Vitesse de transfert des données
** L'ID du produit
** Niveau du micrologiciel


* Informations sur la durée de vie des disques SSD (ces informations sont uniquement valides pour les systèmes E2800 et E5700/EF570, et ne sont pas affichées si la baie ne contient pas de disques SSD) :
+
** Nombre moyen d'effacement.
** Les blocs de rechange restants.
** Le pourcentage d'endurance utilisé (nouveauté dans la version 11.41). Le pourcentage d'endurance utilisé est la quantité de données écrites sur les disques SSD à ce jour divisée par la limite théorique totale d'écriture des disques.


* Informations sur le canal du lecteur :
+
** L'emplacement du bac et l'emplacement du logement
** Le canal préféré
** Le canal redondant


* Couverture des disques de secours
* Détails de chaque disque
+
[NOTE]
====
Les informations de date de fabrication ne sont pas disponibles pour les disques NVMe.

====




== Syntaxe

[listing, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allDrives`
 a| 
Paramètre permettant de renvoyer des informations sur tous les lecteurs de la matrice de stockage.



 a| 
`driveMediaType`
 a| 
Type de support de lecteur pour lequel vous souhaitez récupérer des informations. Les valeurs suivantes sont des types de support de lecteur valides :

* `HDD` -- utilisez cette option lorsque vous avez des disques durs dans le plateau du lecteur
* `SSD` -- utilisez cette option lorsque vous disposez de disques SSD dans le plateau
* `unknown` -- utilisez cette option si vous ne savez pas quels types de support se trouvent dans le bac d'alimentation
* `allMedia` -- utilisez cette option lorsque vous souhaitez utiliser tous les types de support de lecteur qui se trouvent dans le bac de lecteur




 a| 
`driveType`
 a| 
Type de lecteur pour lequel vous souhaitez récupérer des informations. Vous ne pouvez pas combiner plusieurs types de disques.

Les types de disques valides sont les suivants :

* `SAS`
* `NVMe4K`


Si vous ne spécifiez pas de type de lecteur, la commande est définie par défaut sur n'importe quel type.



 a| 
`drive` ou `drives`
 a| 
Pour les tiroirs disques haute capacité, spécifiez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID du logement pour le lecteur. Pour les tiroirs disques basse capacité, spécifiez la valeur d'ID du bac et la valeur d'ID du logement pour le lecteur. Les valeurs d'ID du bac sont `0` à `99`. Les valeurs d'ID de tiroir sont `1` à `5`.

La capacité maximale de tous les emplacements est de 24. Les valeurs d'ID de fente commencent à 0 ou 1, selon le modèle de bac. Les tiroirs disques compatibles avec les contrôleurs E2800 et E5700 ont des numéros d'ID de slot commençant à 0. Les tiroirs disques compatibles avec les contrôleurs E2700 et E5600 possèdent des numéros d'ID de slot commençant à 1.

Placez la valeur d'ID du bac, la valeur d'ID du tiroir et la valeur d'ID de logement entre crochets ([ ]).



 a| 
`summary`
 a| 
Paramètre permettant de renvoyer l'état, la capacité, le taux de transfert de données, l'ID du produit et la version du micrologiciel pour les lecteurs spécifiés.

|===


== Remarques

Pour déterminer le type et l'emplacement de tous les lecteurs de la matrice de stockage, utilisez le `allDrives` paramètre.

Pour déterminer les informations relatives aux lecteurs SAS de la matrice de stockage, utilisez le `driveType` paramètre.

Pour déterminer le type de lecteur dans un emplacement spécifique, utilisez le `drive` Et entrez l'ID du bac et l'ID du logement pour le lecteur.

Le `drive` paramètre prend en charge à la fois les tiroirs disques haute capacité et les tiroirs disques basse capacité. Un tiroir de disque haute capacité est doté de tiroirs qui maintiennent les disques. Les tiroirs coulissent hors du tiroir du lecteur pour permettre l'accès aux lecteurs. Un tiroir de lecteur de faible capacité n'est pas doté de tiroirs. Pour un plateau de lecteur haute capacité, vous devez spécifier l'identifiant (ID) du plateau de lecteur, l'ID du tiroir et l'ID du logement dans lequel se trouve un lecteur. Dans le cas d'un plateau de lecteur de faible capacité, vous devez uniquement spécifier l'ID du plateau de lecteur et l'ID de l'emplacement dans lequel se trouve un lecteur. Pour un plateau de lecteur de faible capacité, une autre méthode d'identification d'un emplacement est de spécifier l'ID du plateau de lecteur, définissez l'ID du tiroir sur `0`, Et indiquez l'ID de l'emplacement dans lequel réside un lecteur.



== Niveau minimal de firmware

5.43

7.60 ajoute le `drawerID` entrée utilisateur et `driveMediaType` paramètre.

8.41 ajoute des informations sur la durée de vie des disques, en pourcentage de longévité utilisée, pour les disques SSD d'un système E2800, E5700 ou EF570.
