---
permalink: commands-a-z/show-snapvolume.html 
sidebar: sidebar 
keywords: show, snapshot, volumes 
summary: La commande show snapVolume renvoie des informations sur un ou plusieurs volumes de snapshot. 
---
= Affiche les volumes snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show snapVolume` la commande renvoie des informations sur un ou plusieurs volumes de snapshot.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
show (allSnapVolumes | snapVolume pass:quotes[["_snapVolumeName_"]] |
snapVolumes pass:quotes[["_snapVolumeName1_" ... "_snapVolumeNamen_"]])
[summary]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allSnapVolumes`
 a| 
Paramètre pour renvoyer des informations sur tous les volumes de snapshot de la matrice de stockage.



 a| 
`snapVolume`
 a| 
Nom du volume d'instantané sur lequel vous souhaitez récupérer des informations. Placez le nom du volume de snapshot entre guillemets (" ") à l'intérieur de crochets ([ ]).



 a| 
`snapVolumes`
 a| 
Noms de plusieurs volumes de snapshot pour lesquels vous souhaitez récupérer des informations. Entrez les noms des volumes du snapshot à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.




 a| 
`summary`
 a| 
Le paramètre pour renvoyer une liste concise d'informations concernant les volumes du snapshot.

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.

Cette commande renvoie les informations relatives au volume de snapshot comme indiqué dans cet exemple :

[listing]
----
SNAPSHOT VOLUME (SNAPSHOT-IMAGE BASED) SUMMARY
----
[listing]
----
SUMMARY

 Total Snapshot Volumes: 1
   Most Recent Snapshot Volume: Day month date hh:mm:ss yyyy
   Status: 1 Optimal, 0 Non Optimal

   Name        Type       Status     Capacity    Associated Base Volume
   2_SV_0001   Standard   Optimal    3.000 GB    2
----
[listing]
----
   Snapshot Volume Timestamp   Snapshot Image Timestamp    Mode
   1/23/12 6:44:31 PM IST      1/23/12 6:27:36 PM IST      Read Write
----
[listing]
----
   Total Repository Capacity   Available Repository Capacity
   1.199 GB                    0.125 MB (0%)
----
La taille de votre moniteur détermine la manière dont les informations sont enveloppées et affectent la manière dont elles apparaissent.



== Niveau minimal de firmware

7.83
