---
permalink: commands-a-z/show-alldrives-downloadprogress.html 
sidebar: sidebar 
keywords: show, drive, download, progress 
summary: 'La commande show allDrives downloadProgress renvoie l"état des téléchargements de micrologiciel pour les lecteurs ciblés par la commande download drive firmware ou la commande download storageArray driveFirmware.' 
---
= Afficher la progression du téléchargement du lecteur - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show allDrives downloadProgress` commande renvoie l'état des téléchargements de micrologiciel pour les lecteurs qui sont ciblés par le `download drive firmware` commande ou le `download storageArray driveFirmware` commande.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Syntaxe

[source, cli]
----
show allDrives downloadProgress
----


== Paramètres

Aucune.



== Remarques

Lorsque tous les téléchargements de micrologiciel ont réussi, cette commande renvoie un état correct. En cas d'échec du téléchargement du micrologiciel, cette commande affiche l'état de téléchargement du micrologiciel de chaque lecteur ciblé. Cette commande renvoie les États affichés dans ce tableau.

[cols="2*"]
|===
| État | Définition 


 a| 
`Successful`
 a| 
Les téléchargements ont été terminés sans erreur.



 a| 
`Not Attempted`
 a| 
Les téléchargements n'ont pas démarré.



 a| 
`Partial Download`
 a| 
Les téléchargements sont en cours.



 a| 
`Failed`
 a| 
Les téléchargements sont terminés avec des erreurs.

|===


== Niveau minimal de firmware

6.10
