---
permalink: commands-a-z/show-volume-reservations.html 
sidebar: sidebar 
keywords: show, volume, reservations 
summary: La commande show volume reservations renvoie des informations sur les volumes ayant des réservations permanentes. 
---
= Afficher les réservations de volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show volume reservations` la commande renvoie des informations sur les volumes qui ont des réservations permanentes.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage ou de contrôle du stockage.



== Syntaxe

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) reservations
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allVolumes`
 a| 
Paramètre permettant de renvoyer les statistiques de performances relatives à tous les volumes de la baie de stockage.



 a| 
`volume`
 a| 
Nom du volume pour lequel vous souhaitez récupérer des informations. Placez le nom du volume entre crochets ([ ]). Si le nom du volume contient des caractères ou des chiffres spéciaux, vous devez inclure le nom entre guillemets (" ") à l'intérieur des crochets.



 a| 
`volumes`
 a| 
Les noms de plusieurs volumes pour lesquels vous souhaitez récupérer des informations. Entrez les noms des volumes à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Séparez chacun des noms par un espace.


Si les noms de volumes comportent des caractères spéciaux ou des chiffres, entrez les noms à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.


|===


== Niveau minimal de firmware

5.40
