---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: La commande show storageArray unconfigredIssiInitiators renvoie une liste des initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage. 
---
= Affiche les initiateurs iSCSI non configurés de la baie de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show storageArray unconfiguredIscsiInitiators` commande renvoie une liste d'initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage ou de contrôle du stockage.

Cette commande est obsolète. La commande qui la remplace est link:show-storagearray-unconfiguredinitiators.html["Affiche StorageArray unconfigurerdinitiateurs"].



== Syntaxe

[listing]
----
show storageArray unconfiguredIscsiInitiators
----


== Paramètres

Aucune.



== Niveau minimal de firmware

7.10

8.50 obsolète cette commande.
