---
permalink: commands-a-z/show-volume-performancestats.html 
sidebar: sidebar 
keywords: show, volume, performance, statistics 
summary: La commande show volume PerformancesStats renvoie des informations sur les performances du volume. 
---
= Affiche les statistiques de performances des volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show volume performanceStats` la commande renvoie des informations sur les performances du volume.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage ou de contrôle du stockage.



== Contexte

Pour chaque volume de la matrice de stockage, cette commande renvoie les informations suivantes :

* Baies de stockage
* Nombre total d'E/S
* En lecture %
* Baisse du taux de réussite par le cache de lecture primaire
* Taux de réussite du cache d'écriture primaire : %
* Baisse du taux de réussite SSD cache
* Mo/s actuels
* NB max. Mo/s
* E/S actuelles
* Nombre maximum d'E/S
* Nombre minimal d'E/S
* E/S moyennes
* Mo/s minimum
* Mo/s moyens
* Latence d'E/S actuelle
* Latence d'E/S maximale
* Latence d'E/S minimale
* Latence d'E/S moyenne




== Syntaxe

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[["_volumeName_"]]
volumes pass:quotes[["_volumeName1_" ... "_volumeNameN_"]]) performanceStats
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allVolumes`
 a| 
Paramètre permettant de renvoyer les statistiques de performances relatives à tous les volumes de la baie de stockage.



 a| 
`volume`
 a| 
Nom du volume pour lequel vous souhaitez récupérer des informations. Placez le nom du volume entre crochets ([ ]). Si le nom du volume contient des caractères ou des chiffres spéciaux, vous devez inclure le nom entre guillemets (" ") à l'intérieur des crochets.



 a| 
`volumes`
 a| 
Les noms de plusieurs volumes pour lesquels vous souhaitez récupérer des informations. Entrez les noms des volumes à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Séparez chacun des noms par un espace.


Si les noms de volumes comportent des caractères spéciaux ou des chiffres, entrez les noms à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.


|===


== Remarques

Avant d'exécuter le `show volume performanceStat` exécutez la commande `set session performanceMonitorInterval` commande et le `set session performanceMonitorIterations` commande pour définir la fréquence de collecte des statistiques.

Le `show volume performanceStat` la commande renvoie les statistiques de performances du volume comme indiqué dans cet exemple :

[listing]
----
Performance Monitor Statistics for Storage Array: Tyler -
Date/Time: 11/6/12 10:00: 34 AM - Polling interval in seconds: 5


"Storage Arrays","Total IOs","Read %","Primary Read Cache Hit %",
"Primary Write Cache Hit %","SSD Read Cache Hit %","Current MBs/sec",
"Maximum MBs/sec","Current IOs/sec","Maximum IOs/sec","Minimum IOs/sec",
"Average IOs/sec","Minimum MBs/sec","Average MBs/sec","Current IO Latency",
"Maximum IO Latency","Minimum IO Latency","Average IO Latency"

"Capture Iteration: 1","","","","","","","","","","","","","","","","",""
"Date/Time: 11/6/12 10:00:34 AM","","","","","","","","","","","","","","",
   "","","""Volume Unnamed","0.0","","0.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0",
   "0.0","0.0","0.0","0.0","0.0","0.0","0.0"
----


== Niveau minimal de firmware

6.10
