---
permalink: commands-a-z/show-storagearray-powerinfo.html 
sidebar: sidebar 
keywords: show, storage, array, power, information 
summary: 'La commande show storageArray powerInfo renvoie des informations sur la quantité d"énergie consommée par l"ensemble de la matrice de stockage et chaque bac de la matrice de stockage.' 
---
= Afficher les informations d'alimentation de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray powerInfo` la commande renvoie des informations sur la quantité d'énergie consommée par l'ensemble de la matrice de stockage et chaque plateau de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



== Syntaxe

[source, cli]
----
show storageArray powerInfo
----


== Paramètres

Aucune.



== Remarques

Cette commande renvoie des informations de consommation d'énergie similaires à cet exemple.

[listing]
----
total power drawn: 310 watts
number of trays: 1
tray power input details:
   tray id  power supply serial number  input power
   0        0                           160 watts
   0        1                           150 watts
----


== Niveau minimal de firmware

8.10
