---
permalink: commands-a-z/show-controller-arraymanagementsignedcertificate-summary.html 
sidebar: sidebar 
keywords: show, signed, certificate 
summary: La commande show Controller arrayManagementSignedCertificate Summary affiche le résumé du certificat signé en cours à partir du contrôleur spécifié. 
---
= Affiche le certificat signé
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show controller arrayManagementSignedCertificate summary` la commande affiche le récapitulatif du certificat signé actuel depuis le contrôleur spécifié.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de sécurité.



== Syntaxe

[listing]
----

show controller [(a|b)] arrayManagementSignedCertificate summary
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur sur lequel vous souhaitez récupérer les certificats racine/intermédiaire. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).

|===


== Exemple

La sortie de l'échantillon peut être différente de celle illustrée ci-dessous.

[listing]
----

SMcli -n Array1 -c "show controller[a] arrayManagementSignedCertificate all summary;"

============================
Controller A Signed Certificate
============================
Subject DN:   CN=Corp Issuing CA 1
Issuer DN:    CN=Corp Root CA
Start:        <date>
Expire:       <date>

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
