---
permalink: commands-a-z/show-storagearray-lunmappings.html 
sidebar: sidebar 
keywords: show, storage, array, lun, map 
summary: 'La commande show storageArray lunAdressages renvoie des informations du profil de la matrice de stockage concernant les mappages de numéro d"unité logique (LUN) ou d"ID d"espace de noms (NSID) dans la matrice de stockage.' 
---
= Afficher les mappages LUN des baies de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray lunMappings` La commande renvoie des informations du profil de la matrice de stockage concernant les mappages de numéro d'unité logique (LUN) ou d'ID d'espace de noms (NSID) dans la matrice de stockage.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



[[context]]
== Contexte

Les mappages de LUN ou de NSID par défaut sont toujours affichés. Si vous exécutez cette commande sans paramètre, cette commande renvoie tous les mappages de LUN ou de NSID.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
show storageArray lunMappings (host pass:quotes[["_hostName_"]] |
hostgroup pass:quotes[["_hostGroupName_"]])
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`host`
 a| 
Nom d'un hôte spécifique pour lequel vous souhaitez afficher les mappages de LUN ou NSID. Placez le nom d'hôte entre guillemets (" ") à l'intérieur de crochets ([ ]).



 a| 
`hostGroup`
 a| 
Nom d'un groupe d'hôtes spécifique dont vous souhaitez afficher les mappages de LUN ou NSID. Placez le nom du groupe d'hôtes entre guillemets (" ") à l'intérieur de crochets ([ ]).

|===


[[notes]]
== Remarques

Cette commande renvoie des informations de topologie hôte similaires à cet exemple.

[listing]
----
MAPPINGS (Storage Partitioning - Enabled (0 of 16 used))
VOLUME NAME  LUN  CONTROLLER  ACCESSIBLE BY  VOLUME STATUS
Access Volume 7   A,B         Default Group  Optimal
21           21   B           Default Group  Optimal
22           22   B           Default Group  Optimal
----


[[minimum-firmware-level]]
== Niveau minimal de firmware

6.10
