---
permalink: commands-a-z/show-controller-arraymanagementsignedcertificate-summary.html 
sidebar: sidebar 
keywords: show, signed, certificate 
summary: La commande show Controller arrayManagementSignedCertificate Summary affiche le résumé du certificat signé en cours à partir du contrôleur spécifié. 
---
= Afficher le certificat signé - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show controller arrayManagementSignedCertificate summary` la commande affiche le récapitulatif du certificat signé actuel depuis le contrôleur spécifié.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Security Admin.



[[syntax]]
== Syntaxe

[source, cli]
----
show controller [(a|b)] arrayManagementSignedCertificate summary
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet de spécifier le contrôleur sur lequel vous souhaitez récupérer les certificats racine/intermédiaire. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).

|===


[[example]]
== Exemple

La sortie de l'échantillon peut être différente de celle illustrée ci-dessous.

[listing]
----

SMcli -n Array1 -c "show controller[a] arrayManagementSignedCertificate all summary;"

============================
Controller A Signed Certificate
============================
Subject DN:   CN=Corp Issuing CA 1
Issuer DN:    CN=Corp Root CA
Start:        <date>
Expire:       <date>

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.40
