---
permalink: commands-a-z/show-volume-summary.html 
sidebar: sidebar 
keywords: show, volume 
summary: La commande show volume summary renvoie des informations sur un volume. 
---
= Afficher le volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show volume summary` la commande renvoie des informations sur un volume.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage ou de contrôle du stockage.



== Contexte

Pour les volumes d'une matrice de stockage, cette commande renvoie les informations suivantes :

* Le nombre de volumes
* Le nom
* Le statut
* La capacité
* Niveau RAID
* Groupe de volumes où se trouve le volume
* Détails :
+
** ID du volume
** L'ID du sous-système
** Type de disque (SAS)
** Protection contre les pertes du plateau
** Propriétaire préféré
** Propriétaire actuel
** La taille du segment
** Priorité de modification
** État du cache de lecture (activé ou désactivé)
** État du cache d'écriture (activé ou désactivé)
** Le cache d'écriture sans état des piles (activé ou désactivé)
** Cache d'écriture avec état miroir (activé ou désactivé)
** Le cache d'écriture de vidage après le temps
** Le paramètre de lecture préalable de la mémoire cache (VRAI ou FAUX)
** L'état d'activation de l'analyse des supports en arrière-plan (activé ou désactivé)
** Analyse des supports avec état de vérification de redondance (activé ou désactivé)


* Les volumes du référentiel miroir




== Syntaxe

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allVolumes`
 a| 
Ce paramètre renvoie les statistiques de performances de tous les volumes de la matrice de stockage.



 a| 
`volume`
 a| 
Nom du volume pour lequel vous souhaitez récupérer des informations. Placez le nom du volume entre crochets ([ ]). Si le nom du volume contient des caractères ou des chiffres spéciaux, vous devez inclure le nom entre guillemets (" ") à l'intérieur des crochets.



 a| 
`volumes`
 a| 
Les noms de plusieurs volumes pour lesquels vous souhaitez récupérer des informations. Entrez les noms des volumes à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Séparez chacun des noms par un espace.


Si les noms de volumes comportent des caractères spéciaux ou des chiffres, entrez les noms à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.




 a| 
`summary`
 a| 
Paramètre permettant de renvoyer une liste concise d'informations sur les volumes.

|===