---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: La commande show storageArray iscsideNegoticationDefaults renvoie des informations sur les paramètres de niveau de connexion qui sont sujets à la négociation initiateur-cible. 
---
= Afficher les paramètres par défaut de négociation de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray iscsiNegotiationDefaults` la commande renvoie des informations sur les paramètres de niveau de connexion soumis à la négociation initiateur-cible.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle Administrateur du stockage ou moniteur de stockage.



== Syntaxe

[source, cli]
----
show storageArray iscsiNegotiationDefaults
----


== Paramètres

Aucune.



== Remarques

Les informations renvoyées incluent les paramètres par défaut de la barre d'état du contrôleur (c'est-à-dire les paramètres qui constituent le point de départ de la négociation) et les paramètres actifs actuels.



== Niveau minimal de firmware

7.10
