---
permalink: commands-a-z/show-storagearray-unconfiguredinitiators.html 
sidebar: sidebar 
keywords: show, unconfigured, initiators 
summary: La commande show storageArray unconfigurerdInitiators renvoie une liste des initiateurs détectés par la matrice de stockage, mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage. 
---
= Affiche les initiateurs non configurés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray unconfiguredInitiators` commande renvoie une liste d'initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à une baie de stockage E4000, E2800, E5700, EF600 ou EF300 individuelle. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle Administrateur du stockage ou moniteur de stockage.

Cette commande remplace le link:show-storagearray-unconfigurediscsiinitiators.html["Affiche storageArray unconfigdIssiInitiators"] commande.



== Syntaxe

[source, cli]
----
show storageArray unconfiguredInitiators
----


== Paramètres

Aucune.



== Niveau minimal de firmware

8.50
