---
permalink: commands-a-z/show-allsnmpcommunities.html 
sidebar: sidebar 
keywords: show, snmp, communities 
summary: 'La commande show allSnmpCommunities renvoie des informations sur les communautés SNMP (simple Network Management Protocol) définies pour la matrice de stockage. Les communautés SNMP sont des ensembles de périphériques, tels que des routeurs, des commutateurs, des imprimantes, des périphériques de stockage, regroupées pour gérer et surveiller les périphériques.' 
---
= Afficher les communautés SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show allSnmpCommunities` La commande renvoie des informations sur les communautés SNMP (simple Network Management Protocol) définies pour la baie de stockage. Les communautés SNMP sont des ensembles de périphériques, tels que des routeurs, des commutateurs, des imprimantes, des périphériques de stockage, regroupées pour gérer et surveiller les périphériques.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle Administrateur du stockage ou Administrateur du support ou moniteur de stockage.



== Contexte

Les informations renvoyées incluent les éléments suivants :

* Le nombre total de communautés
* Nombre total de destinations d'interruption
* Noms des communautés SNMP




== Syntaxe

[listing, subs="+macros"]
----
show pass:quotes[(allSnmpCommunities |
snmpCommunity communityName="_snmpCommunityName_"] |
snmpCommunities pass:quotes[[_snmpCommunityName1_ ... _snmpCommunityNameN_]])
[summary]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`allSnmpCommunities`
 a| 
Ce paramètre renvoie des informations sur toutes les communautés SNMP de la matrice de stockage.



 a| 
`communityName`
 a| 
Nom de la communauté SNMP pour laquelle vous souhaitez récupérer des informations. Placez le nom de la communauté SNMP entre guillemets (" ").



 a| 
`snmpCommunities`
 a| 
Les noms de plusieurs communautés SNMP pour lesquelles vous souhaitez récupérer des informations. Entrez les noms des communautés SNMP à l'aide des règles suivantes :

* Placez tous les noms entre crochets ([ ]).
* Placez chacun des noms entre guillemets (" ").
* Séparez chacun des noms par un espace.




 a| 
`summary`
 a| 
Ce paramètre renvoie une liste du nombre total de communautés SNMP et du nombre total de destinations de déroutement SNMP. Lorsque vous utilisez ce paramètre, toutes les informations détaillées sont omises.

|===


== Remarques

SNMP prend en charge une ou plusieurs _communautés_ auxquelles appartiennent les gestionnaires et les périphériques gérés. Les requêtes SNMP contiennent une _communauté string_ dans les paquets de données transmis sur le réseau qui agit comme un mot de passe brut. Les agents SNMP peuvent rejeter ou DÉFINIR des requêtes GET avec une chaîne de communauté non reconnue. Une chaîne de communauté est également incluse dans les notifications DE DÉROUTEMENT envoyées par l'agent au responsable.

L'agent SNMP intégré prend en charge IPV4 et IPV6.

Cette commande renvoie des informations de communauté SNMP similaires à cet exemple.

[listing]
----
SNMP COMMUNITIES------------------------------
SUMMARY
   Total SNMP Communities: 2
   Total SNMP Trap Destinations: 1
DETAILS
   SNMP Community: TestComm1
   SNMP Permission: Read Only
      Associated Trap Destination:
      Trap Receiver IP Address: 10.113.173.133
      Send Authentication Failure Traps: true
   SNMP Community: Test2
   SNMP Permission: Read Only
      Associated Trap Destination:
----


== Niveau minimal de firmware

8.30
