---
permalink: commands-a-z/show-volumecopy-source-targetcandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, target, candidates 
summary: La commande show VolumeCopy source targetCandidates renvoie des informations sur les volumes candidats que vous pouvez utiliser comme cible pour une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot. 
---
= Afficher les cibles de copie de volume candidates - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show volumeCopy source targetCandidates` commande renvoie des informations sur les volumes candidats que vous pouvez utiliser comme cible pour une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
show volumeCopy source pass:quotes[["_sourceName_"]] targetCandidates
----


[[parameter]]
== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`source`
 a| 
Nom du volume source pour lequel vous essayez de trouver un volume cible candidat. Placez le nom du volume entre crochets ([ ]). Si le nom du volume contient des caractères ou des chiffres spéciaux, vous devez inclure le nom du volume entre guillemets (" ") entre crochets.

|===