---
permalink: commands-a-z/show-storagearray-odxsetting.html 
sidebar: sidebar 
keywords: show, storage, array, odx, set 
summary: 'La commande show storageArray odxsetting renvoie les paramètres actuels de Offloaded Data Transfer (ODX) et de VMware vStorage API Array Architecture (VAAI) sur la baie de stockage.' 
---
= Afficher les paramètres ODX de la matrice de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray odxsetting` La commande renvoie les paramètres actuels de Offloaded Data Transfer (ODX) et de VMware vStorage API Array Architecture (VAAI) sur la baie de stockage.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



== Contexte

Les paramètres de cette commande peuvent être les suivants :

* True : ODX et VAAI sont activés.
* FALSE : ODX et VAAI sont désactivés.
* Incohérent -- les contrôleurs ne possèdent pas les mêmes paramètres.
* Inconnu -- le paramètre pour ODX ou VAAI ne peut pas être déterminé.




== Syntaxe

[source, cli]
----
show storageArray odxsetting
----


== Paramètres

Aucune.



== Remarques

Cette commande renvoie les informations ODX et VAAI similaires à cet exemple.

[listing]
----
Windows ODX Setting Status
odxEnabled  True | False | Inconsistent | Unknown
vaaiEnabled True | False | Inconsistent | Unknown
----


== Niveau minimal de firmware

8.20
