---
permalink: commands-a-z/show-storagearray-controllerhealthimage.html 
sidebar: sidebar 
keywords: show, storage, array, controller, health, image 
summary: 'La commande show storageArray controllerHealthImage affiche les détails de l"image d"état du contrôleur sur le cache du contrôleur, si une image d"intégrité du contrôleur est disponible, sur les baies de stockage prenant en charge l"image d"état du contrôleur.' 
---
= Afficher l'image d'état du contrôleur de baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray controllerHealthImage` la commande affiche les détails de l'image d'état du contrôleur sur le cache du contrôleur, si une image d'intégrité du contrôleur est disponible, sur les baies de stockage qui prennent en charge l'image d'état du contrôleur.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.



[[context]]
== Contexte

[NOTE]
====
Avec la version 8.20 du micrologiciel `coreDump` le paramètre est remplacé par le `controllerHealthImage` paramètre.

====
Si la matrice de stockage ne prend pas en charge la fonction d'image d'intégrité du contrôleur, cette commande renvoie une erreur.



[[syntax]]
== Syntaxe

[source, cli]
----
show storageArray controllerHealthImage
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.83

8.20 remplace le `coreDump` paramètre avec le `controllerHealthImage` paramètre.
