---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: La commande show storageArray unconfigredIssiInitiators renvoie une liste des initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage. 
---
= Afficher les initiateurs iSCSI non configurés de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `show storageArray unconfiguredIscsiInitiators` commande renvoie une liste d'initiateurs détectés par la matrice de stockage mais qui ne sont pas encore configurés dans la topologie de la matrice de stockage.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Storage Monitor.

Cette commande est obsolète. La commande qui la remplace est link:show-storagearray-unconfiguredinitiators.html["Affiche StorageArray unconfigurerdinitiateurs"].



== Syntaxe

[source, cli]
----
show storageArray unconfiguredIscsiInitiators
----


== Paramètres

Aucune.



== Niveau minimal de firmware

7.10

8.50 obsolète cette commande.
