---
permalink: commands-a-z/show-controller-cacertificate.html 
sidebar: sidebar 
keywords: show, installed, root, intermediate, ca, certificates, summary 
summary: 'La commande show Controller caCertificate affiche le résumé des certificats CA installés à partir du contrôleur spécifié. Cette commande est utile avant d"exécuter la commande delete Controller caCertificate afin de connaître les noms d"alias des certificats à supprimer.' 
---
= Affiche le récapitulatif des certificats CA racine/intermédiaire installés
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `show controller caCertificate` Commande affiche le récapitulatif des certificats CA installés à partir du contrôleur spécifié. Cette commande est utile à utiliser avant d'exécuter le `delete controller caCertificate` commande pour connaître les noms d'alias des certificats à supprimer.



== Baies prises en charge

Cette commande s'applique à une seule baie de stockage E2800, E5700, EF600 ou EF300. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur de sécurité.



== Syntaxe

[listing, subs="+macros"]
----
show controller [(a|b)] caCertificate [all | aliases=pass:quotes[("_alias1_" ... "_aliasN_")]] summary
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`controller`
 a| 
Permet à l'utilisateur de spécifier le contrôleur sur lequel vous souhaitez récupérer les certificats racine/intermédiaire. Des identifiants de contrôleur valides sont a ou b, où a est le contrôleur dans le slot A, et b le contrôleur dans le slot B. Placez l'identificateur du contrôleur entre crochets ([ ]).



 a| 
`all`
 a| 
Permet à l'utilisateur de spécifier la récupération de tous les certificats racine/intermédiaire.



 a| 
`aliases`
 a| 
Permet à l'utilisateur de spécifier le certificat racine/intermédiaire à récupérer par alias. Placez tous les alias entre parenthèses. Si vous saisissez plusieurs alias, séparez-les par un espace.

|===


== Exemples

[listing, subs="+macros"]
----

SMcli -n Array1 -c "show controller[a] caCertificate all summary;"

SMcli -n Array1 -c "show controller[b] caCertificate alias=("myAlias" "anotherAlias") summary;"
============================
Controller A Authority Certificates
============================
Alias:        19527b38-8d26-44e5-8c7f-5bf2ca9db7cf
Subject DN:   CN=My Corp Issuing CA 1
Issuer DN:    CN=My Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]
---------------------
Alias:        myAliasName
Subject DN:   CN=My Corp Issuing CA 1
Issuer DN:    CN=My Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]

SMcli completed successfully.
----


== Niveau minimal de firmware

8.40
