---
permalink: commands-a-z/smcli-enable-disable-autosupportremotediag.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, remote, diagnostics, feature, emw, management, domain, level, smcli 
summary: 'La commande SMcli enable|disable autoSupportRemoteDiag active ou désactive la fonction de diagnostic à distance AutoSupport. Cette fonctionnalité permet au support technique de demander des données de support afin d"identifier les problèmes à distance.' 
---
= Activation ou désactivation de la fonctionnalité de diagnostic à distance AutoSupport au niveau du domaine de gestion EMW (SMcli uniquement).
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `SMcli enable|disable autoSupportRemoteDiag` Active ou désactive la fonction de diagnostic à distance AutoSupport. Cette fonctionnalité permet au support technique de demander des données de support afin d'identifier les problèmes à distance.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage E2700 et E5600 du domaine de gestion à la fois. Elle ne s'applique pas aux baies de stockage E2800 ou E5700.



== Contexte

[NOTE]
====
Cette commande est une commande SMcli, pas une commande script. Vous devez exécuter cette commande à partir d'une ligne de commande. Vous ne pouvez pas exécuter cette commande à partir de l'éditeur de script dans le logiciel de gestion du stockage.

====
[NOTE]
====
Cette commande a des répercussions sur toutes les baies de stockage compatibles avec ASUP du domaine de gestion.

====
Avant d'activer cette fonctionnalité, activez d'abord la fonctionnalité AutoSupport, puis la fonctionnalité AutoSupport OnDemand sur le domaine de gestion.

Vous devez activer les trois fonctions dans cet ordre.

. *Activer AutoSupport*
. *Activer AutoSupport OnDemand*
. *Activer les diagnostics à distance AutoSupport*




== Syntaxe

[listing]
----
SMcli enable|disable autoSupportRemoteDiag
----


== Paramètres

Aucune.



== Vérification

Utilisez le `SMcli -autoSupportConfig show` commande pour voir si vous avez activé la fonction. Les trois premières lignes de la sortie affichée indiquent l'état d'activation de la fonctionnalité AutoSupport, suivi de la fonction AutoSupport OnDemand, suivi de l'état de la fonction AutoSupport Remote Diagnostics :

[listing]
----
The AutoSupport feature is activated on this storage management
station.
The AutoSupport OnDemand feature is activated on this storage management
station.
The AutoSupport Remote Diagnostics feature is activated on this storage
management station.
----


== Niveau minimal de micrologiciel

8.25
