---
permalink: commands-a-z/start-asyncmirrorgroup-synchronize.html 
sidebar: sidebar 
keywords: start, asynchronous, mirror, synchronization 
summary: La commande start asynchrones MirrorCsynchronize démarre la synchronisation asynchrone de la mise en miroir. 
---
= Démarrer la synchronisation de mise en miroir asynchrone - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start asyncMirrorGroup synchronize` La commande démarre la synchronisation de mise en miroir asynchrone.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Syntaxe

[source, cli, subs="+macros"]
----
start asyncMirrorGroup pass:quotes[["_asyncMirrorGroupName_"]] synchronize [deleteRecoveryPointIfNecessary]
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`asyncMirrorGroup`
 a| 
Nom du groupe de miroirs asynchrones pour lequel vous souhaitez démarrer la synchronisation. Placez le nom du groupe de miroirs asynchrones entre guillemets (« ») à l'intérieur des crochets ([« » »]).



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
Paramètre permettant de supprimer le point de récupération si les données de synchronisation récupérables ont dépassé le seuil de récupération. L'âge du point de restauration est mesuré à partir de la période de gel des données sur la baie de stockage primaire.

|===


== Niveau minimal de firmware

7.84

8.10 ajoute le `deleteRecoveryPointIfNecessary` paramètre.

11.80 baies EF600 et EF300 prises en charge
