---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: 'La commande start volume initialize démarre le formatage d"un volume dans une matrice de stockage.' 
---
= Démarrer l'initialisation du volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `start volume initialize` commande lance le formatage d'un volume dans une matrice de stockage.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
Le formatage d'un volume démarre une opération de longue durée que vous ne pouvez pas arrêter.

====


== Syntaxe

[listing, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volume`
 a| 
Nom du volume à formater. Placez le nom du volume entre crochets ([ ]). Si le nom du volume contient des caractères ou des chiffres spéciaux, vous devez inclure le nom entre guillemets (" ") à l'intérieur des crochets.

|===


== Niveau minimal de firmware

6.10
