---
permalink: commands-a-z/start-volumegroup-locate.html 
sidebar: sidebar 
keywords: start, volume, group, locate 
summary: La commande start Volume Volume Group Locate identifie les lecteurs qui sont regroupés de manière logique pour former le groupe de volumes spécifié en faisant clignoter les voyants des lecteurs. 
---
= Démarrer la localisation du groupe de volumes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start volumeGroup locate` la commande identifie les lecteurs qui sont regroupés de manière logique pour former le groupe de volumes spécifié en faisant clignoter les voyants des lecteurs.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Utilisez le `stop volumeGroup locate` commande pour éteindre les voyants lumineux des lecteurs.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] locate
----


[[parameter]]
== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes pour lequel vous souhaitez localiser les lecteurs appartenant à ce groupe de volumes. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

6.16
