---
permalink: commands-a-z/start-storagearray-isnsserverrefresh.html 
sidebar: sidebar 
keywords: start, storage, array, isns, server, refresh 
summary: 'La commande start storageArray isnsServerRefresh lance une actualisation des informations d"adresse réseau pour le serveur iSNS.' 
---
= Démarrer l'actualisation du serveur iSNS de la baie de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start storageArray isnsServerRefresh` Commande lance une actualisation des informations d'adresse réseau pour le serveur iSNS.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Si le serveur DHCP est marginal ou ne répond pas, l'opération de renouvellement peut prendre de deux à trois minutes.

[NOTE]
====
Cette commande s'applique uniquement à IPv4.

====


[[syntax]]
== Syntaxe

[source, cli]
----
start storageArray isnsServerRefresh
----


[[parameter]]
== Paramètre

Aucune.



[[notes]]
== Remarques

Si vous avez utilisé `set storageArray isnsIPv4ConfigurationMethod` Commande pour définir la configuration, mais n'a pas défini la configuration sur DHCP, exécutant le `start storageArray isnsServerRefresh` renvoie une erreur.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.10
