---
permalink: commands-a-z/start-ssdcache-locate.html 
sidebar: sidebar 
keywords: start, ssd, cache, locate 
summary: La commande start ssdcache locate identifie les disques SSD regroupés logiquement pour former le cache SSD en faisant clignoter les voyants des disques SSD. 
---
= Démarrer la localisation du cache SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start ssdCache locate` Cette commande identifie les disques SSD regroupés de manière logique pour former le cache SSD en clignotants les voyants des disques SSD.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez disposer du rôle Support Admin.



[[context]]
== Contexte

Utilisez le `stop ssdCache locate` commande pour éteindre les voyants lumineux des lecteurs.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`ssdCache`
 a| 
Nom du cache SSD auquel vous souhaitez localiser. Placez le nom du cache SSD entre crochets ([ ]). Si le nom du cache SSD contient des caractères spéciaux ou se compose uniquement de nombres, vous devez inclure le nom du cache SSD entre guillemets (") dans les crochets.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

7.84

11.80 baies EF600 et EF300 prises en charge
