---
permalink: commands-a-z/start-diskpool-locate.html 
sidebar: sidebar 
keywords: start, disk pool, locate 
summary: La commande start DISKPOOL Locate identifie les lecteurs qui sont regroupés logiquement ensemble pour former le pool de disques spécifié en faisant clignoter les voyants des lecteurs. 
---
= Démarrer la localisation du pool de disques - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start diskPool locate` la commande identifie les lecteurs qui sont regroupés de manière logique pour former le pool de disques spécifié en faisant clignoter les voyants des lecteurs.



== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



== Contexte

(Utilisez le `stop diskPool locate` commande pour éteindre les voyants lumineux sur les lecteurs.)



== Syntaxe

[source, cli, subs="+macros"]
----
start diskPool pass:quotes[[_diskPoolName_]] locate
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`diskPool`
 a| 
Nom du pool de disques pour lequel vous souhaitez le localiser. Placez le nom du pool de disques entre crochets ([ ]). Si le nom du pool de disques contient des caractères spéciaux ou des chiffres, vous devez inclure le nom du pool de disques entre guillemets (" ") entre crochets.

|===


== Niveau minimal de firmware

7.83
