---
permalink: commands-a-z/start-diskpool-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, resource, provision 
summary: 'La commande start DISKPOOL resourceProvisioning active le provisionnement des ressources sur un pool de disques donné et lance une opération asynchrone d"activation du provisionnement des ressources sur chaque volume du pool de disques. Le provisionnement des ressources nécessite que tous les disques du pool prennent en charge la fonction DULBE de NVMe.' 
---
= Démarrer le provisionnement des ressources du pool de disques - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start diskPool resourceProvisioning` la commande active le provisionnement des ressources sur un pool de disques donné et lance une opération asynchrone d'activation du provisionnement des ressources sur chaque volume du pool de disques. Le provisionnement des ressources nécessite que tous les disques du pool de disques prennent en charge la fonctionnalité DULBE de NVMe.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les baies EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage EF600, EF300, EF50 et EF80, vous devez disposer du rôle Storage Admin.



[[context]]
== Contexte

Pour désactiver le provisionnement des ressources sur un pool de disques, utilisez la commande de provisionnement complet avec l'option pour désactiver le provisionnement des ressources. Un pool de disques est provisionné en ressources lorsqu'il est créé si tous les disques sont compatibles DULBE et ceux de la baie de stockage `resourceProvisionedVolumes` le paramètre est `true`.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
start diskPoolpass:quotes[[_diskPoolName_]] resourceProvisioning
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`diskPoolName`
 a| 
Le pool de disques que vous souhaitez activer la fonction de provisionnement de ressources. Placez le nom du pool de disques entre crochets ([ ]).

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

11.73
