---
permalink: commands-a-z/start-snmptrapdestination.html 
sidebar: sidebar 
keywords: test, snmp, trap, destination 
summary: 'La commande start snmpTrapDestination teste la connexion et l"identification du récepteur d"interruption pour une communauté ou un utilisateur SNMP (simple Network Management Protocol) spécifique. Cette commande teste la destination de l"interruption en envoyant un message d"interruption au récepteur d"interruption.' 
---
= Tester la destination des traps SNMP - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start snmpTrapDestination` Commande teste la connexion et l'identification du récepteur d'interruption pour une communauté ou un utilisateur SNMP (simple Network Management Protocol) spécifique. Cette commande teste la destination de l'interruption en envoyant un message d'interruption au récepteur d'interruption.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique aux baies de stockage individuelles E4000, E2800, E5700, EF600, EF300, EF50 et EF80. Elle ne fonctionne pas sur les baies de stockage E2700 ou E5600.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin ou Support Admin.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
start snmpTrapDestination trapReceiverIP=ipAddress
    pass:quotes[(communityName="_communityName_" | (userName="_userName_"] [engineId=(local | engineId)]))
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`trapReceiverIP`
 a| 
Adresse IP du gestionnaire SNMP auquel vous souhaitez envoyer des messages d'interruption.



 a| 
`communityName`
 a| 
Nom de la communauté SNMP pour laquelle vous voulez envoyer des messages d'interruption.



 a| 
`userName`
 a| 
Nom de l'utilisateur SNMP pour lequel vous voulez envoyer des messages d'interruption.



 a| 
`engineId`
 a| 
ID du moteur de l'utilisateur SNMP pour lequel vous voulez envoyer des messages d'interruption. L'ID du moteur est requis si plusieurs utilisateurs USM ont le même nom d'utilisateur. La valeur peut être «[.code]``local``" Pour spécifier l'agent SNMP local est l'agent faisant autorité ou une chaîne de chiffres hexadécimal pour spécifier un ID de moteur d'agent SNMP distant.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

8.30
