---
permalink: commands-a-z/start-diskpool-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, resource, provision 
summary: 'La commande start DISKPOOL resourceProvisioning active le provisionnement des ressources sur un pool de disques donné et lance une opération asynchrone d"activation du provisionnement des ressources sur chaque volume du pool de disques. Le provisionnement des ressources nécessite que tous les disques du pool prennent en charge la fonction DULBE de NVMe.' 
---
= Démarrer le provisionnement de ressources de pool de disques
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `start diskPool resourceProvisioning` la commande active le provisionnement des ressources sur un pool de disques donné et lance une opération asynchrone d'activation du provisionnement des ressources sur chaque volume du pool de disques. Le provisionnement des ressources nécessite que tous les disques du pool de disques prennent en charge la fonctionnalité DULBE de NVMe.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage, y compris aux baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage EF600 et EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

Pour désactiver le provisionnement des ressources sur un pool de disques, utilisez la commande de provisionnement complet avec l'option pour désactiver le provisionnement des ressources. Un pool de disques est provisionné en ressources lorsqu'il est créé si tous les disques sont compatibles DULBE et ceux de la baie de stockage `resourceProvisionedVolumes` le paramètre est `true`.



== Syntaxe

[listing, subs="+macros"]
----
start diskPoolpass:quotes[[_diskPoolName_]] resourceProvisioning
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`diskPoolName`
 a| 
Le pool de disques que vous souhaitez activer la fonction de provisionnement de ressources. Placez le nom du pool de disques entre crochets ([ ]).

|===


== Niveau minimal de firmware

11.73
