---
permalink: commands-a-z/start-volumegroup-import.html 
sidebar: sidebar 
keywords: start, volume, group, import 
summary: 'La commande start Volume Volume Group Import déplace un groupe de volumes dans un état complet pour qu"un groupe de volumes nouvellement introduit soit à la disposition de sa nouvelle baie de stockage.' 
---
= Démarrer l'importation du groupe de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `start volumeGroup import` Cette commande déplace un groupe de volumes dans un état complet pour mettre à disposition un nouveau groupe de volumes pour sa nouvelle baie de stockage.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Le groupe de volumes doit être à l'état exporté ou forcé avant d'exécuter cette commande. Une fois la commande exécutée, le groupe de volumes est opérationnel.

[NOTE]
====
Au sein du groupe de volumes, vous ne pouvez pas déplacer les volumes associés aux fonctions d'une matrice de stockage vers une autre matrice de stockage.

====


== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] import
----


== Paramètre

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`volumeGroup`
 a| 
Nom du groupe de volumes à importer. Placez le nom du groupe de volumes entre crochets ([ ]).

|===


== Remarques

Les volumes de niveau supérieur spécifiquement associés aux fonctionnalités (mise en miroir synchrone, copie de volume, mappage et réservations permanentes) sont supprimés dans le cadre de l'opération d'importation.

Vous devez exécuter le `show volumeGroup importDependencies` avant d'exécuter le `start volumeGroup import` commande.



== Niveau minimal de firmware

7.10
