---
permalink: commands-a-z/stop-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: stop, drive, channel, fault, isolation, diagnostics 
summary: 'La commande STOP rageChannel fault Diagnostics arrête le diagnostic d"isolation de défaut du canal d"entraînement, ce qui arrête la commande de diagnostic d"isolation de défaut du canal d"entraînement avant la fin.' 
---
= Diagnostic d'isolement des défauts du canal d'arrêt du lecteur - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop driveChannel faultDiagnostics` la commande arrête le diagnostic d'isolation de panne du canal d'entraînement, qui arrête le `start drive channel fault isolation diagnostics` avant la fin de la commande.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

[NOTE]
====
Avec la version 8.10 du micrologiciel, le `stop driveChannel faultDiagnostics` la commande est obsolète.

====


[[syntax]]
== Syntaxe

[source, cli]
----
stop driveChannel faultDiagnostics
----


[[parameters]]
== Paramètres

Aucune.



[[notes]]
== Remarques

Utilisez le `start driveChannel faultDiagnostics` commande et le `save driveChannel faultDiagnostics` commande avec `stop driveChannel faultDiagnostics` commande. Ces commandes sont nécessaires pour lancer le test de diagnostic et enregistrer les résultats du test de diagnostic dans un fichier.

Vous pouvez également arrêter le `start driveChannel faultDiagnostics` commande à tout moment en appuyant sur `Ctrl+C`.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.15
