---
permalink: commands-a-z/stop-volumecopy-target-source.html 
sidebar: sidebar 
keywords: stop, volume, copy 
summary: La commande stop VolumeCopy target source arrête une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot. 
---
= Arrêter la copie du volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop volumeCopy target source` la commande arrête une opération de copie de volume. Cette commande est valide pour les paires de copies de volume de snapshot.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[stop volumeCopy target [_targetName_]] source pass:quotes[[_sourceName_]]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`target`
 a| 
Nom du volume cible pour lequel vous souhaitez arrêter une opération de copie de volume. Placez le nom du volume cible entre crochets ([ ]). Si le nom du volume cible contient des caractères spéciaux ou des chiffres, vous devez inclure le nom du volume cible entre guillemets (" ") entre crochets.



 a| 
`source`
 a| 
Nom du volume source pour lequel vous souhaitez arrêter une opération de copie de volume. Placez le nom du volume source entre crochets ([ ]). Si le nom du volume source contient des caractères ou des chiffres spéciaux, vous devez inclure le nom du volume source entre guillemets (" ") à l'intérieur de crochets.

|===