---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: 'La commande stop storageArray driveFirmwareDownload arrête un téléchargement de micrologiciel sur les lecteurs d"une matrice de stockage qui a été lancé avec la commande download storageArray driveFirmware.' 
---
= Arrêter le téléchargement du micrologiciel du lecteur de matrice de stockage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop storageArray driveFirmwareDownload` la commande arrête le téléchargement d'un micrologiciel vers les lecteurs d'une matrice de stockage qui a été démarrée avec le `download storageArray driveFirmware` commande.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Cette commande n'arrête pas le téléchargement du firmware déjà en cours d'exécution sur un disque. Cette commande arrête tous les téléchargements de micrologiciel vers les lecteurs en attente de téléchargement.



[[syntax]]
== Syntaxe

[source, cli]
----
stop storageArray driveFirmwareDownload
----


[[parameters]]
== Paramètres

Aucune.



[[minimum-firmware-level]]
== Niveau minimal de firmware

6.10
