---
permalink: commands-a-z/stop-snapvolume.html 
sidebar: sidebar 
keywords: stop, snapshot, volume 
summary: La commande STOP snapVolume arrête une opération de volume instantané. 
---
= Arrêter le volume d'instantané - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop snapVolume` la commande arrête une opération de volume de snapshot.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[stop snapVolume ["_snapVolumeName_"]]
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume de snapshot que vous souhaitez arrêter. Placez le nom du volume de snapshot entre guillemets (" ") entre crochets ([ ]).

|===


[[notes]]
== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



[[minimum-firmware-level]]
== Niveau minimal de firmware

7.83
