---
permalink: commands-a-z/stop-snapvolume.html 
sidebar: sidebar 
keywords: stop, snapshot, volume 
summary: La commande STOP snapVolume arrête une opération de volume instantané. 
---
= Arrêter le volume snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop snapVolume` la commande arrête une opération de volume de snapshot.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Syntaxe

[source, cli, subs="+macros"]
----
pass:quotes[stop snapVolume ["_snapVolumeName_"]]
----


== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`snapVolume`
 a| 
Nom du volume de snapshot que vous souhaitez arrêter. Placez le nom du volume de snapshot entre guillemets (" ") entre crochets ([ ]).

|===


== Remarques

Vous pouvez utiliser n'importe quelle combinaison de caractères alphanumériques, de traits de soulignement (_), de traits d'Union (-) et de livres (#) pour les noms. Les noms peuvent comporter un maximum de 30 caractères.



== Niveau minimal de firmware

7.83
