---
permalink: commands-a-z/stop-consistencygroup-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, images, consistency, group 
summary: La commande STOP ConsistenceGroup pendingSnapImageCreation arrête toutes les images de snapshot en attente qui doivent être créées sur un groupe de cohérence de snapshot. 
---
= Arrêter les images instantanées en attente sur le groupe de cohérence - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop consistencyGroup pendingSnapImageCreation` commande arrête toutes les images de snapshot en attente qui doivent être créées sur un groupe de cohérence de snapshot.



[[supported-arrays]]
== Baies prises en charge

Cette commande s'applique à n'importe quelle baie de stockage individuelle, y compris les E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 et EF80, à condition que tous les packages SMcli soient installés.



[[roles]]
== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600, EF300, EF50 ou EF80, vous devez avoir le rôle Storage Admin.



[[context]]
== Contexte

Si le groupe de cohérence de snapshot ne contient aucune image snapshot en attente, le logiciel de gestion du stockage affiche un message d'erreur et n'exécute pas la commande.



[[syntax]]
== Syntaxe

[source, cli, subs="+macros"]
----
stop consistencyGroup pass:quotes[[_consistencyGroupName_]]pendingSnapImageCreation
----


[[parameters]]
== Paramètres

[cols="2*"]
|===
| Paramètre | Description 


 a| 
`consistencyGroupName`
 a| 
Nom du groupe de cohérence dont vous souhaitez arrêter une opération de snapshot en attente. Placez le nom du groupe de cohérence entre crochets ([ ]). Si le nom du groupe de cohérence contient des caractères ou des chiffres spéciaux, vous devez inclure le nom du groupe de cohérence entre guillemets (") dans les crochets.

|===


[[minimum-firmware-level]]
== Niveau minimal de firmware

7.83
