---
permalink: commands-a-z/stop-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: stop, drive, channel, fault, isolation, diagnostics 
summary: 'La commande STOP rageChannel fault Diagnostics arrête le diagnostic d"isolation de défaut du canal d"entraînement, ce qui arrête la commande de diagnostic d"isolation de défaut du canal d"entraînement avant la fin.' 
---
= Arrêter les diagnostics d'isolation des défauts du canal d'entraînement
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le `stop driveChannel faultDiagnostics` la commande arrête le diagnostic d'isolation de panne du canal d'entraînement, qui arrête le `start drive channel fault isolation diagnostics` avant la fin de la commande.



== Baies prises en charge

Cette commande s'applique à toute baie de stockage individuelle, notamment les systèmes E2700, E5600, E2800, E5700, Baies EF600 et EF300, tant que tous les packages SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E2800, E5700, EF600 ou EF300, vous devez disposer du rôle d'administrateur du stockage.



== Contexte

[NOTE]
====
Avec la version 8.10 du micrologiciel, le `stop driveChannel faultDiagnostics` la commande est obsolète.

====


== Syntaxe

[listing]
----
stop driveChannel faultDiagnostics
----


== Paramètres

Aucune.



== Remarques

Utilisez le `start driveChannel faultDiagnostics` commande et le `save driveChannel faultDiagnostics` commande avec `stop driveChannel faultDiagnostics` commande. Ces commandes sont nécessaires pour lancer le test de diagnostic et enregistrer les résultats du test de diagnostic dans un fichier.

Vous pouvez également arrêter le `start driveChannel faultDiagnostics` commande à tout moment en appuyant sur `Ctrl+C`.



== Niveau minimal de firmware

7.15
