---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: 'La commande stop storageArray driveFirmwareDownload arrête un téléchargement de micrologiciel sur les lecteurs d"une matrice de stockage qui a été lancé avec la commande download storageArray driveFirmware.' 
---
= Arrêtez le téléchargement du micrologiciel du lecteur de la matrice de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `stop storageArray driveFirmwareDownload` la commande arrête le téléchargement d'un micrologiciel vers les lecteurs d'une matrice de stockage qui a été démarrée avec le `download storageArray driveFirmware` commande.



== Baies prises en charge

Cette commande s'applique à toutes les baies de stockage, y compris les baies E4000, E2700, E5600, E2800, E5700, EF600 et EF300, tant que tous les packs SMcli sont installés.



== Rôles

Pour exécuter cette commande sur une baie de stockage E4000, E2800, E5700, EF600 ou EF300, vous devez avoir le rôle d'administrateur du stockage.



== Contexte

Cette commande n'arrête pas le téléchargement du firmware déjà en cours d'exécution sur un disque. Cette commande arrête tous les téléchargements de micrologiciel vers les lecteurs en attente de téléchargement.



== Syntaxe

[source, cli]
----
stop storageArray driveFirmwareDownload
----


== Paramètres

Aucune.



== Niveau minimal de firmware

6.10
